			N-AWIPS 5.4.3.m Patch Release Notes
				3/19/99	

Patch 5.4.3.m covers development from February 26, to March 19, 1999.

		  Product Generation Changes
		  --------------------------

Improvements to NMAP product generation functions include:

	o  Improved the modify action.  Modify now starts at the closest point
	   on the line instead of the closest vertex.  Also, improved the 
	   algorithm so that modify will eliminate the smaller loop when 
	   modifying closed lines.

	o  Improved the increment/decrement function. The pop-up window 
	   has been simplified by removing the increment and decrement radio
	   buttons.  The up and down arrows now control the increment/decrement 
	   value which can be positive or negative.  The increment/decrement 
	   value can also be entered from the keyboard without the cursor 
	   being in the text box.  Finally, text is automatically de-selected 
	   after the function is executed to avoid unintended 
	   increment/decrements.

	o  Added capability to blank out symbols.  Also added capability
	   to plot a symbol at a user specified latitude and longitude.

	o  Changed the default to sort files by file name for the open action.

	o  Added streamline line type.

The following improvements have been made to product generation post-processing
capabilities:

	o  Created a new program, SFVGSF to read a VG file, extract values,
	   and write them to a GEMPAK surface file.

	o  Added quality control thresholding to the surface objective analysis
	   program, OABSFC.  A new parameter, qcntl, allows the user to enter
	   a threshold value to compare the data against the first guess grid.
	   If the difference exceeds qcntl, the data point is not used in the
	   objective analysis.  Any data points eliminated by this threshold
	   check are listed.  Also improved OABSFC to perform the objective
	   analysis if one of the input data sets is missing or data are not 
	   available for the user-specified time.  Previously, the program
	   would not continue the analysis under these conditions.

	o  Renamed text files generated by NMAP for the HPC.


Product generation bug fixes:

	o  Fixed a problem with partial delete when lines are nearly closed.

	o  Fixed problems with increment/decrement function when roaming and
	   zooming.

	o  Fixed problems with different line types remembering previous
	   settings.



			NMAP Display Improvements	
			-------------------------

        o  Added distance and direction information to the ANCHOR and VOR cursor
	   displays.


NMAP bug fixes:

	o  Corrected errors in the seek function when roaming or zooming.

	o  Fixed the set time and current time functions for the time line.



			Other Improvements included in this patch
			-----------------------------------------

        o  Added the capability to display certain station data based on the
	   priority value set in station tables.  A new station parameter,
           SPRI, has been added.  To plot stations of a specified priority,
	   set SPRI equal to that priority value.  Alternatively, the AREA 
	   parameter can be set to SPRI:lower_value:upper_value to specify a 
	   range of priorities to display.  Lower value and upper value can be 
	   the same to specify a particular priority to display.

	o  Added sfparm to SFMOD program to allow selected parameters to be
	   extracted from a surface data set.

	o  NWX was improved to eliminate the listing of duplicate bulletins.

	o  Made corrections to problems discovered during Y2K testing of range
	   and increment processing of the GEMPAK variable DATTIM.  Also
	   fixed routine TI_SORT to return GEMPAK times ordered correctly
	   (year 99 preceding year 00).


	 		General bug fixes in this patch
			-------------------------------

	o  Fixed a fatal bug in NSAT found by the SPC with some types of
	   radar data. 


                   Patch m and j incompatibilities
		   -------------------------------

Patch m VG files are incompatible with version j.  The conversion program, 
convcvg, MUST be run, to properly handle combination symbols in version j if 
they are generated by version m.  

To run the program enter: convcvg 3m3j m_file_name new_file_name, where 
m_file_name is the patch m version of the file, and new_file_name is 
the converted file that may be accessed by patch j.



The necessary compiling and linking instructions are contained in
the following file:

	patch_build_5.4.3.m 


	To execute the script and save its output in a file type:

		cd $GEMPAK/build
		patch_build_5.4.3.m >&! PATCH_$OS & ; tail -f PATCH_$OS

The output of the script will be written to PATCH_$OS.
