#!/bin/sh
#-----------------------------------------------------------------------
# lprint
#
# This utility aids in printing the chapter files for one of the GEMPAK
# books.
#
# Command-line options:
#
#  -P	Printer name
#
# Example:
#
#       lprint  .../TOC.out  .../ch01.out
#       lprint  .../ch07*  .../appx*
#       lprint  -P qms1700d  .../ch02*
#       lprint  .../appxb.out  -P hp5simxPS .../appxd.out
##
# Log:
# M. Linda/GSC		11/97	Original
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Get command line options.

cmdLine=`echo $* | tr "	 " " " | tr -s " " `

printr=`echo $cmdLine | sed 's/^.*-P *\([^ ]*\).*$/\1/' `

if  [ "$printr" = "$cmdLine" ] ; then
    printr=""
fi

#-----------------------------------------------------------------------
# Get the files from the command line.

files=`echo $cmdLine | sed 's/^\(.*\)\(-P *[^ ]*\)\(.*\)$/\1 \3/' `

#-----------------------------------------------------------------------
# Process one file at a time.

if  [ "$printr" != "" ] ; then
    pcmd="-P$printr"
else
    pcmd="-P$NPRINTER"
fi

for oneFile in $files ; do
    unset MPAGE
    mpage -2 -L60 -t -m50lr -z$LP -Z$LPFLAG $pcmd $oneFile
done

#-----------------------------------------------------------------------
