			NAWIPS 5.4.3+ Changed Files Log

007a.   10/3/97         gempak/source/driver/active/utf/utfinita.c, usdatt.c,
			uclosp.c, utfcmn.h

018a.   10/3/97         nprogs/nmap/source/nmap_mcanvw.c

010a.	10/6/97		gempak/source/gemlib/ss/ssvers.f

021a.	10/6/97		gempak/source/cgemlib/cds/cdsspln.c
			nprogs/nmap/source/vgf/NxmLines.c, NxmStoDspVG.c

=========================== Patch 5.4.3.a ==================================

010b.	10/8/97		gempak/source/gemlib/ss/ssvers.f

018b.	10/8/97		NEW:gempak/source/nxmlib/NxmMarkA.c
			icons/marker/mark1.bxm - mark21.bxm

			nprogs/nmap/source/nmap_mapw.c, nmap_map.h
			gempak/source/nxmlib/Nxmlib.h
			include/Nxm.h
			gempak/tables/nmap/mapovl.nmap

021b.	10/8/97		gempak/source/cgemlib/cvq/cvqgetginf.c, cvqhigp.c,
			cvqnxtgnm.c, cvqscangrp.c
			gempak/error/cvq.err

018c.	10/8/97		nprogs/nmap/source/vgf/NxmBtnCb.c, NxmFileDlg.c
			gempak/source/nxmlib/NxmConfirm.c

018d.	10/8/97		NEW:gempak/source/nxmlib/NxmLabel.c

			nprogs/nmap/source/nmap_uairw.c, nmap_stnmw.c,
			nmap_mpcstw.c, nmap_mapw.c, nmap_dslw.c, 
			nmap_dataw.c
			gempak/source/nxmlib/NxmPrt.c, NxmLineA.c, 
			NxmMarkA.c

021c.	10/10/97	gempak/source/cgemlib/cds/cdsline.c, cdsspln.c

021d.	10/10/97	nprogs/nmap/source/vgf/NxmPlaceText.c

007b.	10/14/97	gempak/source/driver/active/utf/hinita.f, hsdatt.f,
			uinita.c, usdatt.c
			gempak/tables/pgen/afosprod.tbl
			gempak/help/device.hl2

=========================== Patch 5.4.3.b ==================================

010c.	10/15/97	gempak/source/gemlib/ss/ssvers.f

010d.	10/16/97	gempak/source/gemlib/pc/testpc.f

012a.	10/16/97	NEW:nprogs/guitst/source/guitst.c, user.c,
			Makefile, readme
			resource/Guitst

012b.	10/16/97	NEW:gempak/source/nxmlib/NxmCtlBtn.c

			gempak/source/nxmlib/NxmLineA.c, NxmMarkA.c,
			Nxmlib.h
			nprogs/nmap/source/nmap_dataw.c, nmap_dslw.c,
			nmap_mapw.c, nmap_mpcsw.c, nmap_roamw.c, 
			nmap_sfmw.c, nmap_stnmw.c, nmap_uairw.c,
			nmap_vgfw.c
			nprogs/nmap/source/vgf/NxmLines.c, NxmPlaceText.c
			include/Nxm.h

014a.	10/16/97	NEW:gempak/source/nxmlib/NxmRes.c

			nprogs/ntrans/source/ntrans.c

011a.	10/16/97	NEW:gempak/source/programs/gp/gpmap/gpmafs.f
			gempak/help/afosf1.hl1, afosf1.hl2

			gempak/source/programs/gp/gpmap/gpmap.f,
			gpminp.f

			gempak/parm/gpmap.prm
			gempak/pdf/gemglb.pdf
			gempak/txt/programs/gpmap.txt

011b.	10/17/97	gempak/source/programs/gp/gpmap/gpmap.f,
			gpmafs.f

009a.	10/17/97	gempak/build/cgemlib_link, util_link

014b.	10/20/97	gempak/source/nxmlib/NxmRes.c

021e.	10/20/97	NEW:nprogs/nmap/source/vgf/nmap_gpevt.c,
			nmap_pgfilw.c, nmap_pgfrtw.c, nmap_pgrpw.c,
			nmap_pghdlb.c, nmap_pghot.c, nmap_pgline.c,
			nmap_pgpalw.c, nmap_pgvgf.c, nmap_gpwndw.c
			gempak/source/driver/active/xw/xpgpaste.c,
			xpgrfrsh.c, xpgsvfrm.c

			nprogs/nmap/source/vgf/NxmPlaceText.c
			nprogs/nmap/source/nmap.c, nmap_dsp.c, 
			nmap_mainw.c, nmap_mapw.c, nmap_mbtnw.c,
			nmap_mcanvw.c, nmap_zoomw.c
			gempak/source/cgemlib/cvg/cvgsetginf.c
			resource/Nmap
			gempak/build/cgemlib_compile

010e.	10/20/97	gempak/source/cgemlib/cst/testcst.c, cstrxbl.c,
			cstrmst.c, cstrmbl.c, cstrlst.c, cstnocc.c,
			cstilst.c, cstflst.c, cstclst.c, cstcins.c
			gempak/source/cgemlib/cpg/cpgldgrps.c, cpgfndgrp.c
			gempak/source/cgemlib/ces/cesrstng.c
			gempak/source/driver/active/fax/rsdatt.c, rinita.c
			nprogs/nmap/source/nmap_stnmw.c, nmap_mdl.c, 
			nmap_dslw.c, nmap_dataw.c
			gempak/include/gemprm.h

			NEW:gempak/error/cst.err

021f.	10/21/97	NEW:gempak/source/cgemlib/cds/cdsgetfil.c,
			cdssetfil.c

			gempak/source/cgemlib/cds/cdsinit.c, cdslinke.c,
			cdsspln.c, cds.h
			nprogs/nmap/source/nmap_vgfw.c

010f.	10/21/97	gempak/source/cgemlib/ces/cesrstng.c

007c.	10/21/97	gempak/source/device/plot/dwthr.f, dctyp.f,
			dicng.f, dptnd.f, dpwth.f, dsky.f, dspcl.f

010g.	10/21/97	gempak/source/cgemlib/cst/cstclst.c

021g.	10/22/97	NEW:nprogs/nmap/source/vgf/nmap_pgtxt.c
			gempak/source/nxmlib/NxmTxtA.c
			include/NxmTxt.h

			nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgevt.c,
			nmap_pgvgf.c
			gempak/source/cgemlib/crg/crgtxtrng.c

021h.	10/23/97	NEW:nprogs/nmap/source/nmap_data.h

			nprogs/nmap/source/nmap_vgfw.c, nmap_dataw.c, 
			nmap_dsp.c

018e.	10/23/97	nprogs/nmap/source/nmap_stnmw.c
			nprogs/nmap/source/vgf/nmap_pgpalw.c

=========================== Patch 5.4.3.c ==================================

010h.	10/27/97	gempak/source/gemlib/ss/ssvers.f

018f.	10/27/97	nprogs/nmap/source/nmap_stnmw.c
			gempak/tables/nmap/gemparms.tbl

006a.	10/28/97	gempak/source/gplt/transform/mcidas/mcnav.f
			nvxgoes.f, nvxgvar.f

001a.	10/28/97	NEW:gempak/source/programs/dc/dcacft/dcacft.f,
			dcacft_link
			gempak/source/bridge/af/*
			gempak/tables/pack/acft.pack
			gempak/tables/stns/airep_waypnts.tbl,
			pirep_navaids.tbl
			gempak/error/af.err, dcacft.err
			gempak/help/dcacft.hlp

			gempak/build/dc_link, bridge_compile
			gempak/help/sfparm.hl2
			gempak/txt/apx/parms.apx

014c.	10/29/97	NEW:icons/busy/stpins.bxm

			gempak/source/nxmlib/NxmBusy.c
			nprogs/ntrans/source/menubar.c

021i.	10/29/97	NEW:gempak/source/cgemlib/clo/*
			gempak/source/cgemlib/cds/cdswbox.c
			gempak/source/cgemlib/crg/crgwbxrng.c
			nprogs/nmap/source/vgf/nmap_pgwbxw.c,
			nmap_pgwlst.c
			gempak/tables/pgen/spcbtn.tbl
			icons/nmap/ctylst.xbm, spc.xbm

			gempak/source/cgemlib/cds/cdsdspvg.c
			gempak/source/cgemlib/ces/ceschng.c,
			ceselset.c, cesrstng.c
			gempak/source/cgemlib/cgr/cgrinpoly.c
			gempak/source/cgemlib/cvgwbsto.c
			nprogs/nmap/source/nmap.c, nmap_mmenuw.c,
			nmap_zoomw.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, 
			nmap_pgpalw.c, nmap_pgvgf.c
			gempak/tables/pgen/classbtn.tbl, newdraw.tbl
			gempak/tables/stns/county.tbl
			gempak/build/cgemlib_compile

011c.	10/29/97	gempak/source/programs/gd/gdcross/gdcross.f,
			gdxsdl.f

021j.	10/29/97	gempak/source/nxmlib/NxmTxtA.c
			gempak/source/cgemlib/crg/crgsptrng.c
			nprogs/nmap/source/vgf/nmap_pgtxt.c
			include/NxmTxt.h

021k.	10/29/97	gempak/source/cgemlib/cvg/cvgsetginf.c, 
			cvgdump.c

010i.	10/30/97	NEW:gempak/source/gemlib/sfacny.f, sfcrcn.f,
			sfrbox.f, sfwbox.f

			gempak/source/gemlib/sf/sfofil.f, testsf.f, 
			sfcmn.cmn
			gempak/source/gemlib/dm/dmlssf.f, testdm.f
			gempak/include/gemprm.*

007a.	10/30/97	gempak/source/driver/active/xw/xslwid.c

011d.	10/30/97	gempak/source/programs/gp/gpmap/gpmap.f

012c.	10/30/97	nprogs/viewfax/viewfax.c
			nprogs/ntrans/source/ntrans.c
			nprogs/ntl/source/ntl.c
			nprogs/nsat/source/nsat.c
			nprogs/nwx/source/nwx.c, mapw.c
			gempak/source/programs/gui/nafos/nafos.c
			gempak/source/programs/gui/nalarm/naltxt.c,
			nalarm.c, nalarm_link
			resource/Nwx

021l.	10/31/97	nprogs/nmap/source/vgf/nmap_pgevt.c

010j.	11/03/97	gempak/source/gemlib/in/intxtn.f, testin.f
			gempak/source/gemlib/st/strmst.f
			gempak/source/gemlib/st/AIX/strmst.f
			gempak/source/programs/gp/gpmap/gpmap.f

008a.	11/03/97	
			gempak/source/cgemlib/cgr/cgrbounds.c
			gempak/source/cgemlib/cgr/cgrdang.c
			gempak/source/cgemlib/cgr/cgrdist.c		
			gempak/source/cgemlib/cgr/cgrgetmtrx.c		
			gempak/source/cgemlib/cgr/cgrmtrxmult.c		
			gempak/source/cgemlib/cgr/cgrtorad.c		
			gempak/source/cgemlib/cgr/cgrundomtrx.c		
			gempak/source/cgemlib/cgr/cgrxformpt.c		
			gempak/source/cgemlib/cmd/cmdgetcls.c		
			gempak/source/cgemlib/cmd/cmdgetfnc.c		
			gempak/source/cgemlib/cmd/cmdgetobj.c		
			gempak/source/cgemlib/cmd/cmdidcls.c		
			gempak/source/cgemlib/cmd/cmdidfnc.c		
			gempak/source/cgemlib/cmd/cmdidobj.c		
			gempak/source/cgemlib/cmd/cmdinit.c
			gempak/source/cgemlib/cpg/cpgdmpct.c		
			gempak/source/cgemlib/cpg/cpgprint.c		
			gempak/source/cgemlib/cpg/cpgreadcuts.c		
			gempak/source/cgemlib/cpg/cpgrindex.c		
			gempak/source/cgemlib/cpg/cpgrlst.c	
			gempak/source/cgemlib/crg/crgposclr.c
			gempak/source/gemlib/dg/dgplll.f		
			gempak/source/gemlib/gb/gbrindx.c
			gempak/source/gemlib/im/prnlon.f		
			gempak/source/gemlib/mr/mrchkw.f
			gempak/source/gemlib/pc/pcckpm.f
			gempak/source/gemlib/pr/prcfct.f		
			gempak/source/gemlib/pr/prclcx.f		
			gempak/source/gemlib/pr/prclhx.f		
			gempak/source/gemlib/pr/prp03c.f		
			gempak/source/gemlib/pr/prp03d.f		
			gempak/source/gemlib/pr/prptsy.f		
			gempak/source/gemlib/pr/prwccv.f		
			gempak/source/gemlib/pr/prwtnd.f		
			gempak/source/gemlib/pr/prwvis.f		
			gempak/source/gemlib/ss/ssexit.f		
			gempak/source/gemlib/df/dffcnt.f		
			gempak/source/gemlib/dg/dgazst.f		
			gempak/source/gemlib/dg/dgclal.f		
			gempak/source/gemlib/dg/dgdriv.f		
			gempak/source/gemlib/dv/dvmsfc.f		
			gempak/source/gemlib/er/erinit.c		
			gempak/source/gemlib/er/erwbuf.c		
			gempak/source/gemlib/gb/gbdiag.c		
			gempak/source/gemlib/gb/gbensemble.c		
			gempak/source/gemlib/gb/gbgbdh.c		
			gempak/source/gemlib/gb/gbges.c			
			gempak/source/gemlib/gb/gbggds.c		
			gempak/source/gemlib/gb/gbgpds.c		
			gempak/source/gemlib/gb/gbnext.c		
			gempak/source/gemlib/gb/gbsspk.c		
			gempak/source/gemlib/gd/gdswrt.f		
			gempak/source/gemlib/gr/grsubx.f		
			gempak/source/gemlib/im/imlutf.f		
			gempak/source/gemlib/in/inaxis.f		
			gempak/source/gemlib/in/incbar.f		
			gempak/source/gemlib/in/incint.f		
			gempak/source/gemlib/in/incolr.f		
			gempak/source/gemlib/in/inhilo.f		
			gempak/source/gemlib/in/inline.f	
			gempak/source/gemlib/in/instyp.f		
			gempak/source/gemlib/in/intxtn.f		
			gempak/source/gemlib/ip/ipsavf.f		
			gempak/source/gemlib/lc/lcuare.f		
			gempak/source/gemlib/mv/AIX/mvei32.f
			gempak/source/gemlib/mv/OSF1/mvei32.f		
			gempak/source/gemlib/mv/ULTRIX/mvei32.f		
			gempak/source/gemlib/mv/mvei32.f	
			gempak/source/gemlib/mv/vms/mvei32.f		
			gempak/source/gemlib/oa/oabarn.f	
			gempak/source/gemlib/oa/oaigrd.f		
			gempak/source/gemlib/oa/oasint.f		
			gempak/source/gemlib/oa/oawgrd.f		
			gempak/source/gemlib/oa/oawrms.f		
			gempak/source/gemlib/pc/pccmdt.f		
			gempak/source/gemlib/pc/pccmlv.f		
			gempak/source/gemlib/pc/pccmst.f		
			gempak/source/gemlib/pc/pccmvr.f		
			gempak/source/gemlib/pc/pccmvs.f		
			gempak/source/gemlib/pc/pcdpth.f		
			gempak/source/gemlib/pc/pcflvl.f
			gempak/source/gemlib/pc/pcfndl.f		
			gempak/source/gemlib/pc/pcftop.f		
			gempak/source/gemlib/pc/pclyrd.f		
			gempak/source/gemlib/pc/pcmeth.f		
			gempak/source/gemlib/pc/pcmvrt.f		
			gempak/source/gemlib/pc/pcsfcz.f		
			gempak/source/gemlib/pr/prwceq.f		
			gempak/source/gemlib/ps/psbrch.f		
			gempak/source/gemlib/ps/pscape.f		
			gempak/source/gemlib/ps/pscins.f		
			gempak/source/gemlib/ps/pseqlv.f		
			gempak/source/gemlib/ps/pslfcv.f		
			gempak/source/gemlib/ps/pslift.f		
			gempak/source/gemlib/ps/psmlmr.f		
			gempak/source/gemlib/ps/psmlth.f	
			gempak/source/gemlib/ps/psprcl.f		
			gempak/source/gemlib/sf/sfrspc.f		
			gempak/source/gemlib/sf/sfrstr.f		
			gempak/source/gemlib/ss/csleep.c		
			gempak/source/gemlib/ti/tirtim.f
			gempak/source/cgemlib/ces/cescng.c
			gempak/source/cgemlib/ces/ceseldmp.c		
			gempak/source/cgemlib/ces/ceselset.c		
			gempak/source/cgemlib/ces/cesindex.c		
			gempak/source/cgemlib/ces/cesinit.c		
			gempak/source/cgemlib/ces/cesrstng.c		
			gempak/source/cgemlib/cfl/cflrdir.c		
			gempak/source/cgemlib/cfl/cflscnd.c		
			gempak/source/cgemlib/cst/cstcrnm.c		
			gempak/source/cgemlib/cst/cstnocc.c		
			gempak/source/cgemlib/cst/cstnumb.c		
			gempak/source/cgemlib/cst/cstptmt.c		
			gempak/source/cgemlib/cst/cstsrch.c		
			gempak/source/cgemlib/cst/cststoi.c		
			gempak/source/cgemlib/utf/utfdtext.c		
			gempak/source/cgemlib/utf/utfdump.c		
			gempak/source/cgemlib/utf/utfdvctr.c	
			gempak/source/cgemlib/utf/utfgphgd.c		
			gempak/source/cgemlib/utf/utfptext.c		
			gempak/source/cgemlib/utf/utfpvctr.c

011e.	11/4/97		gempak/source/programs/sf/sfmap/sfmplt.f

			gempak/help/sfparm.hl2
			gempak/tables/config/data.tbl
			gempak/tables/parms/pcconv.tbl
			gempak/txt/apx/parms.apx

=========================== Patch 5.4.3.d =================================

010k.	11/10/97	gempak/source/gemlib/ss/ssvers.f

021m.	11/10/97	NEW:gempak/source/cgemlib/cvg/cvgsptsto.c

			nprogs/nmap/source/vgf/nmap_pgevt.c, 
			nmap_pgvgf.c, nmap_pgpalw.c
			gempak/source/cgemlib/cvg/cvglinsto.c,
			cvgtxsto.c
			gempak/source/cgemlib/ces/ceselset.c, 
			cesrstng.c
			gempak/tables/pgen/newdraw.tbl
			resource/Nmap

021n.	11/10/97	NEW:gempak/source/nxmlib/NxmClrW.c

			gempak/source/nxmlib/NxmTxtA.c
			nprogs/nmap/source/vgf/nmap_pgpalw.c,
			nmap_pgline.c

002a.	11/10/97	gempak/source/gemlib/gb/gbgpds.c

010l.	11/12/97	NEW:gempak/source/gemlib/df/dfthwc.f
			gempak/source/gemlib/pd/pdthwc.f
			gempak/source/gemlib/pr/prthwc.f

			gempak/source/gemlib/dg/dgdriv.f
			gempak/source/gemlib/pr/testpr.f
			gempak/help/gparm.hl2
			gempak/txt/gfunc.apx
			gempak/tables/parms/pcconv.tbl

018g.	11/13/97	nprogs/nmap/source/nmap_mtbl.h

007e.	11/13/97	gempak/source/device/attribute/dsfrnt.f
			gempak/source/driver/active/gn/hrtxsy.f

017a.	11/14/97	gempak/source/programs/gui/nalarm/list.c,
			nalarm.h

021o.	11/14/97	gempak/source/cgemlib/ces/ceschng.c,
			ceselset.c, cesrstng.c
			nprogs/nmap/source/vgf/nmap_pgwndw.c
			gempak/tables/pgen/newdraw.tbl

012d.	11/17/97	NEW:gempak/source/nxmlib/NxmPrompt.c

			gempak/source/nxmlib/NxmColorTable.c
			include/Nxm.h

021p.	11/17/97	gempak/source/cgemlib/cds/cdsfrnt.c

010m.	11/18/97	gempak/source/cgemlib/cst/cstnumb.c, 
			cstcrnm.c

010n.	11/18/97	gempak/source/gemlib/pc/pcftop.f

006b.	11/18/97	NEW:gempak/source/driver/active/vg/htext.f,
			hstext.f

			gempak/source/appl/attribute/gstext.f, 
			gqtext.f
			gempak/source/gplt/attribute/gstext.f, 
			gqtest.f, gsattr.f
			gempak/source/gplt/plot/gtext.f
			gempak/source/gplt/main/gplt.f
			gempak/source/gplt/access/ginit.f
			gempak/source/gplt/device/attribute/dstext.f
			gempak/source/device/attribute/dstext.f
			gempak/source/device/plot/dtext.f
			gempak/source/device/main/device.f
			gempak/source/driver/active/gn/hstext.f,
			htext.f
			gempak/source/driver/active/nc/mstext.c,
			mtext.c, htext.f
			gempak/source/driver/active/ps/hstext.f,
			pstext.c, ptext.c, htext.f, pscmn.h, 
			psopen.c
			gempak/source/driver/active/utf/hstext.f,
			ustext.c, utext.c, htext.f, utfcmn.h
			gempak/source/driver/active/xw/hstext.f,
			xstext.c, xtext.c, htext.f
			gempak/source/driver/active/xwp/hstext.f,
			htext.f
			gempak/source/driver/active/vg/vstext.c,
			vtext.c, vgcmn.h
			gempak/source/programs/testprog/atest.f,
			plotsyms.f
			gempak/source/cgemlib/utf/utfptext.c
			gempak/source/cgemlib/cds/cdscntr.c,
			cdstest.c
			gempak/source/gemlib/gg/ggrvec.f, ggwstr.f
			gempak/source/gemlib/in/intext.f
			gempak/source/programs/gui/nafos/nafgmpk.c
			gempak/source/programs/gd/gdcntr/gdnhlo.f
			gempak/source/programs/gd/gdplot/gdbhlo.f,
			gdplot.f
			gempak/source/programs/gd/gdplot2/gdbhlo.f,
			gdpltb.f
			gempak/source/programs/sf/sfgram/sfxchr.f,
			sfxgst.f, sfgram.f
			nprogs/ntrans/source/commands.c, ntrans.c,
			process_meta.c
			nprogs/ntrans/include/defs.h
			nprogs/nmap/source/nmap_gmpk.c, nmap_sat.c
			nmap_sfm.c, nmap_sfmap.f, nmap_snmap.f

			gempak/include/funccode.prm, devset.cmn, 
			devreq.cmn, devact.cmn, xwcmn.h

017b.	11/19/97	gempak/source/programs/gui/nalarm/nalarm.c,
			naltxt.c

018h.	11/20/97	nprogs/nmap/source/vgf/nmap_pgvgf.c

021q.	11/20/97	gempak/source/programs/util/avnbul/avnbul.c,
			bavcb.c, bavgetpoly.c, bavturb.c
			gempak/source/cgemlib/cgr/cgrpolyint.c,
			cgrsegint.c 

001b.	11/20/97	NEW:gempak/source/bridge/ma/maiffp.f, maifmp.f,
			maifpt.f, maifsp.f
			gempak/error/ma.err

			gempak/source/programs/dc/dcmsfc.c
			gempak/source/bridge/ma/mabst0.f, mabtyp.f, mackrp.f,
			macld1.f, maclds.f, maccmn.cmn, macst0.f, macwnd.f,
			madcd1.f, madcd2.f, madcod.f, maddff.f, mads4q.f, 
			mads4r.f, madst0.f, madsvs.f, maelev.f, maerrs.f, 
			magemp.f, magrpt.f, maicea.f, maiihv.f, mainit.f, 
			maintf.f, malscb.f, mamawx.f, manddf.f, maobst.f,
			mapkwd.f, mapr24.f, maprec.f, mapres.f, maprs3.f,
			maprelh.f, martim.f, masc1b.f, masc1d.f, masc3d.f,
			masc4d.f, masec2.f, masec3.f, masec5.f, mastbl.f,
			maswld.f, maswld.f, matdur.f, matemp.f, matesa.f,
			mawgem.f, mawspd.f, mawvh1.f, mawvph.f
			gempak/error/dcmsfc.err
			gempak/tables/pack/msfc.pack
			gempak/tables/stns/msfstns.tbl

006b1.	11/21/97	gempak/source/device/plot/dptnd.f

021r.	11/24/97	NEW:icons/nmap/modify.xbm

			nprogs/nmap/source/vgf/nmap_pgpalw.c,
			nmap_pgpgevt.c
			gempak/include/drwids.h
			gempak/tables/pgen/funcbtn.tbl

008b.	11/24/97	NEW:gempak/txt/bridge/Chap01.txt, aflib.txt,
			avlib.txt, dclib.txt, fflib.txt, malib.txt, 
			metarlib.txt, mmlib.txt, mnlib.txt, mtlib.txt,
			sclib.txt
			gempak/txt/cgemlib/cdslib.txt, ceslib.txt, cgrlib.txt,
			clolib.txt, cpglib.txt, crglib.txt, csslib.txt,
			cstlib.txt, ctblib.txt, cvglib.txt, cvqlib.txt,
			utflib.txt
			gempak/txt/gemlib/AppxA.txt, AppxB.txt, Chap01.txt,
			dflib.txt, dvlib.txt, gblib.txt, gdulib.txt,
			imlib.txt, nalib.txt
			gempak/txt/gemplt/AppxA.txt, AppxB.txt, AppxC.txt,
			AppxD.txt, AppxE.txt, Chap01.txt, Chap02.txt,
			Chap01.txt.old, Chap02.txt.old, Chap17.txt,
			Chap18.txt, access.txt, attribute.txt, bounds.txt,
			color.txt, contour.txt, control.txt, curve.txt,
			graph.txt, grid.txt, map.txt, plot.txt, 
			satellite.txt, transform.txt, utility.txt

			gempak/txt/bridge/rslib.txt, rulib.txt, ralib.txt
			gempak/txt/cgemlib/cfllib.txt
			gempak/txt/gemlib/fllib.txt

009b.	11/24/97	gempak/source/cgemlib/cgr/testcgr_link

021s.	11/25/97	NEW:gempak/source/cgemlib/clo/cloancin.c, 
			cloancinpoly.c, cloancrd.c, clocntygpoly.c,
			clotclsst.c, clotgid.c, clotgltln.c, 
			clovorgall.c, clovorgltln.c, clovorin.c, 
			clovorinpoly.c, clovorrd.c

			gempak/source/cgemlib/clo/cloclosest.c, 
			clocntygall.c, clocntygltln.c, clocntyin.c, 
			clocntyinpoly.c, clocntyrd.c, cloinit.c,
			clolonin.c
			nprogs/nmap/source/vgf/nmap_pgwlst.c
			nprogs/nmap/source/nmap.c
			gempak/source/cgemlib/cds/cdswbox.c
			gempak/tables/nmap/mapovl.nmap
			gempak/include/clocmn.h
			gempak/install/setup_links, remove_links

007f.	11/25/97	NEW:gempak/source/driver/active/xw/xinitclr.c,
			xupdclr.c
			gempak/source/driver/active/ps/pinitclr.c, pupdclr.c, 
			pcvtclr.c
			gempak/tables/colors/coltbl.xwp

			gempak/source/driver/active/xw/hinita.f, hsctbl.f,
		 	xinita.c, xscin.c
			gempak/source/driver/active/xwp/hinita.f, hsctbl.f
			gempak/source/driver/active/gn/csctbl.c
			gempak/source/driver/active/ps/hinita.f, pinita.c
			gempak/source/gplt/control/gsdeva.f
			gempak/source/nxmlib/NxmColorBar.c, NxmColorEdit.c,
			NxmColorPalette.c, NxmColorSliders.c, NxmColorBlink.c,
			NxmColorTable.c
			gempak/include/uscore.h

021t.	11/26/97	gempak/source/cgemlib/clo/cloancinpoly.c,
			clocntyinpoly.c, clovorinpoly.c

013a.	11/26/97	nprogs/ntl/source/ntl.c, colr.c

007g.	11/26/97	gempak/source/driver/active/ps/ptext.c
			gempak/source/device/plot/dlogo.f

012e.	11/26/97	nprogs/nsat/source/file.c
			nprogs/nwx/source/draw.c, fosd.c, srchb.c,
			srcho.c, srchw.c, guid.h
			nprogs/nmap/source/nmap_vtbl.c, nmap_mtbl.c,
			nmap_dataw.c, nmap_domt.c, nmap_dsp.c, nmap_stbl.c,
			nmap_sfmap.f, nmap_snmap.f
			gempak/source/gemlib/gr/testgr.f
			gempak/source/gemlib/st/AIX/stcrnd.f
			gempak/source/gemlib/in/testin.f
			gempak/source/testprog/atest.f
			gempak/source/programs/gui/nafos/naffile.c
			gempak/source/nxmlib/NxmHelpPopup.c

001c.	11/26/97	gempak/source/programs/dc/dcacft/dcacft_link
			gempak/source/programs/dc/dcamos/dcamos_link
			gempak/source/programs/dc/dcffg/dcffg_link
			gempak/source/programs/dc/dchrly/dchrly_link
			gempak/source/programs/dc/dcmetr/dcmetr_link
			gempak/source/programs/dc/dcmmos/dcmmos_link
			gempak/source/programs/dc/dcmsfc/dcmsfc_link
			gempak/source/programs/dc/dcnmos/dcnmos_link
			gempak/source/programs/dc/dcscd/dcscd_link
			gempak/source/programs/dc/dcuair/dcuair_link

010o.	11/26/97.	NEW:gempak/source/cgemlib/css/sunos5/scandir.c
	
			gempak/build/cgemlib_compile

021u.	12/1/97		NEW:gempak/source/cgemlib/cvg/dumpvgf.c,
			dumpcvg_link

			gempak/source/cgemlib/cvg/cvgctddel.c, cvgdeall.c,
			cvgdelet.c, cvgfndhl.c, cvgrdrec.c, cvgrdsel.c,
			cvgscan.c
			gempak/build/cgemlib_link 
			

014d.	12/1/97		nprogs/ntrans/source/autogroup.c

008c.	12/1/97		gempak/txt/bridge/Chap01.txt
			gempak/txt/gemplt/Chap02.txt, Chap17.txt,
			grid.txt

011p.	12/1/97		gempak/source/gemlib/fl/flmfls.f, flmfil.f
			gempak/help/cpyfil.hl2, gdfile.hl2, sffile.hl2,
			snfile.hl2

018i.	12/1/97		nprogs/nmap/source/nmap_mapw.c

012f.	12/1/97		gempak/source/programs/gd/gddiag/gdgwrt.f
			gempak/help/grdnam.hl2

001d.	12/2/97		NEW:gempak/source/bridge/dc/dcbsrc.f,
			dcbsrh.f, dccrid.f, dciffp.f, dcifmp.f, 
			dcrtim.f

			gempak/error/dc.err

007h.	12/3/97		gempak/source/driver/active/gn/csctbl.c

021v.	12/4/97.	gempak/source/cgemlib/cds/cdstext.c

=========================== Patch 5.4.3.e =================================

010r.	12/5/97		gempak/source/gemlib/ss/ssvers.f

021w.	12/5/97		nprogs/nmap/source/vgf/nmap_pgtxt.c

010s.	12/5/97		gempak/source/gemlib/gr/grfixa.f

010t.	12/5/97		NEW:gempak/source/gemlib/ti/titzdf.f

			gempak/source/gemlib/ti/testti.f
			gempak/error/ti.err

001e.	12/8/97		gempak/source/bridge/ff/ffdecd.f, ffglin.f,
			ffgtim.f
			gempak/source/programs/dc/dcffg/dcffcd.f

001f.	12/8/97		gempak/source/bridge/ma/mabst0.f, macsto.f,
			madcod.f, maelev.f, magrpt.f maifsp.f
			gempak/tables/stns/msfstns.tbl

001g.	12/8/97		gempak/source/bridge/af/afawpt.f, afifsp.f,
			afpnbd.f, afrtim.f, afxbif.f

006c.	12/9/97		gempak/source/gemlib/gg/ggwstr.f
			gempak/source/driver/active/nc/htext.f
			gempak/source/driver/active/ps/ptext.c
			gempak/source/driver/active/utf/utext.c
			gempak/source/driver/active/xw/htexst.f, 
			xtext.c
			gempak/source/driver/active/xwp/htext.f
			gempak/source/appl/attribute/gstext.f
			gempak/source/gplt/attribute/gstext.f
			gempak/source/gplt/device/attribute/dstext.f
			gempak/source/device/attribute/dstext.f
			gempak/source/device/plot/dtext.f
			nprogs/ntrans/source/process_meta.c

021x.	12/9/97		NEW:gempak/source/cgemlib/cvg/cvgrndef.c,
			cvgrest.c
			gempak/source/driver/active/xw/xpgrest.c
			icons/nmap/saveas.xbm, restore.xbm

			nprogs/nmap/source/nmap_mmenuw.c, nmap_mbotw.c
			nprogs/nmap/source/vgf/nmap_pgpalw.c, 
			nmap_pgfilw.c
			gempak/include/drwids.h
			gempak/tables/pgen/funcbtn.tbl
			icons/nmap/open.xbm, save.xbm

007i.	12/9/97		gempak/source/device/plot/dturb.f

021y.	12/10/97	nprogs/nmap/vgf/nmap_pgpalw.c, nmap_pgevt.c, 
			nmap_pgline.c, nmap_pgfrtw.c, nmap_pgwndw.c

021z.	12/10/97	nprogs/nmap/vgf/nmap_pgpalw.c

			icons/nmap/*
			NEW:gempak/utilities/xbm.nmapxbms.csh

008d.	12/10/97	gempak/source/gemlib/tb/tbastn.f
			gempak/source/cgemlib/ctb/ctbastn.c

005a.	12/11/97	gempak/source/gemlib/im/imunhd.f

005b.	12/11/97	gempak/source/gemlib/im/imar2gm.f

006d.	12/11/97	NEW:gempak/source/gplt/attribute/gqsizd.f
			gempak/source/appl/attribute/gqsizd.f

			gempak/source/testprog/atest.f
			gempak/source/gplt/main/gplt.f

			gempak/include/funccode.prm, devchr.cmn
			gemprm.*

010u.	12/15/97	gempak/source/gemlib/ip/iprest.f, testip.f

007j.	12/15/97	gempak/source/device/draw/itxsy.f
			gempak/source/cgemlib/cds/cdstext.c

018j.	12/15/97	NEW:nprogs/nmap/source/nmap_image.c, nmap_rad.c
			gempak/source/cgemlib/cfl/cflffil.c
			gempak/source/gemlib/im/imqlut.f
			gempak/tables/luts/enhance.tbl

			nprogs/nmap/source/nmap_data.h, nmap_dataw.c, 
			nmap_domt.c, nmap_dslw.c, nmap_dsp.c, 
			nmap_dsrc.c, nmap_mapw.c, nmap_mmenuw.c,
			nmap_sat.c, nmap_sfm.c, nmap_snm.c, nmap_vgf.c,
			nmap_vtbl.c, nmap_mbotw.c
			gempak/source/nxmlib/NxmEnhw.c
			gempak/tables/nmap/dcatg.nmap, dsrc.nmap

010v.	12/16/97	gempak/source/gemlib/ip/iprest.f

018k.	12/16/97	gempak/source/nxmlib/NxmMarkA.c
			nprogs/nmap/source/nmap_map.h, nmap_mapw.c
			include/Nmx.h
			gempak/tables/nmap/mapovl.nmap

018l.	12/16/97	nprogs/nmap/source/nmap_image.c, nmap_dataw.c
			nprogs/nmap/source/vgf/nmap_pgvgf.c,
			nmap_pgwbxw.c
			gempak/source/cgemlib/cvg/cvgsvwbx.c

008e.	12/17/97	gempak/txt/apx/gfunc.apx

010w.	12/17/97	gempak/source/gemlib/pt/testpt.f

021aa.	12/17/97	nprogs/nmap/source/vgf/nmap_pgpalw.c, 
			nmap_pgvgf.c, nmap_pgtxt.c
			gempak/source/cgemlib/cvg/cvgsvfnt.c,
			cvgsvlin.c, cvgsvsln.c, cvgsvstx.c,
			cvgsvsym.c, cvgsvtxt.c, cvgsvwbx.c,
			cvgsvwnd.c
			gempak/source/cgemlib/crg/crgtxtrng.c
			gempak/source/nxmlib/NxmTxtA.c

021bb.	12/18/97	gempak/source/cgemlib/cvg/cvgsvtxt.c,
			cvgrdele.c

021cc.	12/19/97	gempak/source/nxmlib/NxmTxtA.c
			nprogs/nmap/source/vgf/nmap_pgevt.c,
			nmap_pgtxt.c
			include/NxmTxt.h 

010x.	12/22/97	gempak/source/gemlib/in/intxtn.f, intext.f,
			testin.f
			nprogs/nmap/source/nmap_sfm.c, nmap_snm.c


012f.	12/22/97	NEW:gempak/source/nxmlib/NxmHelp.c

			gempak/source/nxmlib/NxmPrt.c
			gempak/source/programs/gui/nafos/nafprefw.c,
			nafmenuw.c, nafmainw.c, nafdslw.c
			nprogs/nmap/source/nmap_mpcstw.c, nmap_mmenuw.c,
			nmap_mapw.c, nmap_mainw.c, nmap_dataw.c
			nprogs/ntrans/source/mainw.c, man_group.c,
			select_group.c, select_frame.c, models.c, 
			menubar.c gp_callbks.c, file.c
			nprogs/nwx/source/dslw.c, nwx.c, mapw.c
			nprogs/nsat/source/dslw.c, prefw.c, mainw.c,
			mmenuw.c

008f.	12/23/97	NEW:

			doc/Prog_guide/bridge/tables/af.sub, ff.sub, mm.sub,
			ra.sub, sc.sub, av.sub, ma.sub, mn.sub, rs.sub
			dc.sub, metar.sub, mt.sub, ru.sub

			doc/Prog_guide/bridge/toc/Chap1.toc

			doc/Prog_guide/bridge/tools/build, clean_exe, lists,
			run, clean_all, dxfoot.f, lprint

			doc/Prog_guide/gemlib/tables/cds.sub, cvg.sub, gd.sub,
			mv.sub, ss.sub, ces.sub, cvq.sub, gdu.sub, na.sub,
			st.sub, cfl.sub, df.sub, gg.sub, oa.sub, tb.sub,
			cgr.sub, dg.sub, gr.sub, pc.sub, testclib.sub,
			clo.sub, dm.sub, im.sub, pd.sub, tg.sub,
			cpg.sub, dp.sub, in.sub, pr.sub, ti.sub,
			crg.sub, dv.sub, ip.sub, ps.sub, tm.sub,
			css.sub, er.sub, lc.sub, pt.sub, utf.sub,
			cst.sub, fl.sub, lv.sub, sf.sub, ctb.sub,
			gb.sub,  mr.sub, sn.sub

			doc/Prog_guide/gemlib/toc/Chap1.toc, ChapN.toc

			doc/Prog_guide/gemlib/tools/build, clean_exe, lists,
			run, clean_all, dxfoot.f, lprint

			doc/Prog_guide/gemplt/tables/access.sub, color.sub, 
			curve.sub, map.sub, transform.sub, attribute.sub,
			contour.sub, graph.sub,  plot.sub, utility.sub,
			bounds.sub, control.sub, grid.sub, satellite.sub

			doc/Prog_guide/gemplt/toc/Chap1.toc, ChapN.toc

			doc/Prog_guide/gemplt/tools/build, clean_exe, lists,
			run, clean_all, dxfoot.f, lprint

			doc/Prog_guide/shared/dx/build, dxcerr.f, dxgetf.f,
			dxptxt.f, dxw1ln.f, dxwfin.f, clean_exe,
			dxchsb.f, dxgln1.f, dxstrp.f, dxwanm.f, dxwpro.f,
			dx.err, dxcint.f, dxgtnm.f, dxtext.f, dxwblk.f,
			dxwtoc.f, dxcbod.f dxclst.f, dxhdft.f, dxtoc.cmn,
			dxwbln.f, dxcbr1.f, dxcmn.cmn, dxmain.f, dxtoce.f
			dxwcnm.f, dxccvr.f, dxfter.f, dxnewp.f, dxtocs.f,
			dxwctr.f

			doc/Prog_guide/shared/tools/checkSrc.sh, cmpprolo.sh,  
			paramcmp.sh, prolocmp.sh, unisub.sh, chkList.sh,
			lprint, pcode, ptypcmpc.sh, chkSub.sh, makelist.sh,
			phead, ptypcmpf.sh

001h.	12/23/97	gempak/source/bridge/dc/dcwlog.f

001i.	12/23/97	gempak/source/bridge/ma/maprs3.f, maswld.f, mawvph.f

021dd.	12/23/97	nprogs/nmap/source/vgf/nmap_pgevt.c

021ee.	12/30/97	nprogs/nmap/source/vgf/nmap_pgevt.c, 
			nmap_pgwndw.c

005c.	12/30/97	NEW:gempak/source/gemlib/tb/tbnids.f
			gempak/tables/rad/ nidprd.tbl
			gempak/tables/stns/nextrad.tbl
			gempak/tables/luts/nids_cmref.tbl, nids_csher.tbl,
			nids_rsher.tbl, nids_swid.tbl, nids_vel16.tbl,
			nids_vel8.tbl, nids_wecho.tbl

			gempak/source/gemlib/gg/ggsttl.f
			gempak/source/gemlib/im/imar2gm.f, imdrop.f,
			imgi2gm.f, imnihd.f, imnohd.f, imrtbl.f, imsimg.f,
			imunhd.f, testim.f
			gempak/source/gemlib/tb/testtb.f
			gempak/source/driver/active/gn/crgini.c, crnids.c,
			crnowr.c, crarea.c
			nprogs/nmap/source/nmap_image.c
			nprogs/nsat/source/gmpk.c
			gempak/include/imgdef.cmn
			gempak/tables/sat/imgtyp.tbl
			gempak/tables/luts/enhance.tbl
			gempak/tables/nmap/mapovl.nmap
			gempak/error/tb.err

022ff.	12/30/97	nprogs/nmap/source/vgf/nmap_pgevt.c,
			nmap_pgpalw.c

010y.	12/31/97	gempak/source/gemlib/pd/pdthwc.f
			gempak/source/gemlib/pr/prthwc.f

010z.	12/31/97	gempak/source/gemlib/pc/testpc.f

010aa.	12/31/97	gempak/source/gemlib/ip/iprest.f

010bb.	12/31/97	gempak/source/gemlib/testin.f, intxtn.f
			gempak/help/text.hl2

021gg.	1/5/98		nprogs/nmap/source/vgf/nmap_pgevt.c

=========================== Patch 5.4.3.f =================================

010cc.	1/7/98		gempak/source/gemlib/ss/ssvers.f

001j.	1/7/98		gempak/source/programs/dc/dcffg/dcffcd.f
			gempak/help/sfparm.hl2
			gempak/txt/apx/parms.apx

008g.	1/7/98		gempak/help/notae.hlp

001k.	1/8/98		NEW:gempak/source/bridge/sc/sccmn.cmn, scifpt.f, 
			scifsp.f, scinit.f, scintf.f

			gempak/source/bridge/sc/sccltp.f, scdcod.f, scdecd.f,
			scdttm.f, scgemp.f, scgrpt.f, scprrm.f, scrptm.f, 
			sctprm.f, scwea3.f
			gempak/source/programs/dc/dcscd/dcscd.c
			gempak/tables/pack/scd.pack
			gempak/tables/stns/scdstn.tbl
			gempak/txt/apx/parms.apx
			gempak/help/sfparm.hl2

020a.	1/8/98		NEW:gempak/source/programs/util/freeColors/
			freeColors.c, Makefile

			gempak/build/util_link

021hh.	1/9/98		nprogs/nmap/source/vgf/nmap_pgfilw.c, nmap_pgpalw.c

021ii.	1/21/98		nprogs/nmap/source/vgf/nmap_pgpalw.c, 
			nmap_pgfilw.c, nmap_pgevt.c

021jj.	1/21/98		nprogs/nmap/source/vgf/nmap_pgevt.c

011g.	1/21/98		gempak/source/programs/sf/sfmap/sfmclr.f

018m.	1/22/98		nprogs/nmap/source/nmap_sfmap.f, nmap_snmap.f,
			nmap_sfm.c, nmap_snm.c, smfltm.f
			gempak/tables/config/data.tbl

021kk	1/22/98		nprogs/nmap/source/vgf/nmap_pgevt.c

007k.	1/23/98		NEW:gempak/source/driver/active/ps/pcvtclr.c
			gempak/tables/colors/cvtclr.psc

007l.	1/27/98		gempak/source/driver/active/ps/pcvtclr.c

018n.	1/27/98		nprogs/nmap/source/nmap_dsp.c, nmap_image.c,
			nmap_mapw.c, nmap_sfm.c, nmap_snm.c, nmap_zoomw.c,
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pghdlb.c
			gempak/source/driver/active/xw/xpgsvfrm.c
			gempak/source/device/draw/idash.f

021ll.	1/27/98		nprogs/nmap/source/vgf/nmap_pgevt.c

010dd.	1/27/98		NEW:gempak/source/gemlib/fl/fltmpl.f

			gempak/source/gemlib/fl/flmfil.f, flmfls.f,
			flmnam.f, testfl.f
			gempak/tables/config/data.tbl

010l.	1/27/98		gempak/source/bridge/ma/malscb.f

021mm.	1/28/98		nprogs/nmap/source/vgf/nmap_pgevt.c

018o.	1/28/98		nprogs/nmap/source/nmap_image.c

007m.	1/28/98		NEW:gempak/source/device/draw/itxbox.f

			gempak/source/device/plot/dtext.f
			gempak/source/driver/active/xw/xtext.c
			gempak/source/driver/active/ps/ptext.c
			gempak/source/driver/active/nc/htext.c
			gempak/source/driver/active/utf/utext.c
			gempak/source/device/draw/itxsy.f
			nprogs/ntrans/source/commands.c
			gempak/help/text.hl1, text.hl2

			(Doc changes only):
			gempak/source/appl/attribute/gstext.f
			gempak/source/gplt/attribute/gstext.f
			gempak/source/gplt/device/attribute/dstext.f
			gempak/source/device/attribute/dstext.f

007n.	2/2/98		gempak/source/device/draw/idraw.f
			gempak/source/testprog/plotsyms.f
			gempak/source/driver/active/fax/hinit.f, 
			rbrescirc.c, rcircpts.c, rdots.c, rline.c

010ee.	2/2/98		gempak/source/gemlib/dg/dgclal.f, dgclos.f,
			dgofil.f

001m.	2/3/98		NEW:gempak/source/bridge/ls/*
			gempak/source/programs/dc/dclsfc/dclsfc.c
			gempak/source/bridge/dc/dctmst.f
			gempak/error/dclsfc.err, ls.err
			gempak/tables/pack/lsfc.pack
			gempak/tables/stns/lsfstns.tbl
			gempak/help/dclsfc.hlp

			gempak/build/bridge_compile, dc_link
			gempak/error/sf.err
			gempak/tables/config/data.tbl

018p.	2/3/98		nprogs/nmap/source/nmap_dsp.c, nmap_image.c,
			nmap_rad.c

021nn.	2/3/98		nprogs/nmap/source/vgf/nmap_pgpalw.c

010ff.	2/3/98		NEW:gempak/source/gemlib/gd/gdgcyc.f

			gempak/source/gemlib/fl/flmfls.f, flmdat.f,
			testfl.f
			gempak/source/gemlib/gd/gdgtmf.f, testgd.f

			gempak/tables/config/data.tbl

021oo.	2/4/98		gempak/source/cgemlib/cvg/cvgrdele.c, cvgrdrec.c,
			cvgrdsel.c, cvgrfrsh.c, cvgscan.c, dumpvgf.c
			gempak/error/cvg.err

021pp.	2/4/98		gempak/source/cgemlib/cds/cdsline.c
			gempak/source/driver/active/utf/ufill.c

011h.	2/4/98		NEW:gempak/source/programs/gp/gptext/*
			gempak/error/gptext.err
			gempak/parm/gptext.prm
			gempak/txt/programs/gptext.txt
			gempak/help/txtfil.hl1, txtfil.hl2, txtloc.hl1,
			txtloc.hl2, column.hl1, column.hl2

			gempak/build/gp_compile, gp_link
			gempak/utilities/hlpbld/gp_hlpbld
			gempak/utilities/hlpbld/gp_pdfbld

001n.	2/4/98		gempak/source/bridge/ma/maiihv.f
			gempak/tables/pack/sfship.pack

011i.	2/4/98		gempak/source/gemlib/im/imsimg.f
			gempak/tables/rad/nidprd.tbl
			gempak/tables/sat/imgtyp.tbl

022a.	2/4/98		gempak/source/cgemlib/cpg/cpgrdhdr.c

020b.	2/4/98		NEW:gempak/utilities/hlpbld/hlpbld_link
			gempak/utilities/pdfbld/pdfbld_link

			gempak/utilities/hlpbld/hlpbld.f
			gempak/utilities/pdfbld/pdfbld.f

001o.	2/5/98		gempak/source/bridge/ls/lsintf.f, lswgem.f
			gempak/tables/pack/lsfc.pack

021qq.	2/5/98		NEW:icons/nmap/undo.xbm, redo.xbm

			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgpalw.c
			gempak/source/cgemlib/cvg/cvgfrsto.c, cvgsplsto.c
			gempak/include/drwids.h
			gempak/tables/pgen/functbl.tbl

010gg.	2/5/98		gempak/source/cgemlib/cst/cstnocc.c, testcst.c

007o.	2/5/98		gempak/source/driver/active/fax/hinit.f

021rr.	2/9/98		gempak/source/nxmlib/NxmTxtA.c
			gempak/source/driver/active/xw/xaiclr.c
			nprogs/nmap/source/nmap_gmpk.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_papalw.c,
			nmap_pgtxt.c

021ss.	2/9/98		NEW:gempak/source/gemlib/sf/sfcacny.f, sfcgtim.f,
			sfcopnf.f
			gempak/source/cgemlib/clo/clocntyghot.c, 
			clocntyphot.c, clocntyrhot.c
			gempak/source/nxmlib/NxmTxtIn.c

			gempak/source/gemlib/sf/sfcrcn.f
			gempak/source/cgemlib/cds/cdswbox.c
			gempak/source/cgemlib/ces/ceschng.c, ceselset.c,
			cesrstng.c
			gempak/source/cgemlib/clo/clocntygall.c,
			clocntyinpoly.c
			gempak/source/cgemlib/cvg/cvgsvwbx.c, cvgwbsto.c
			cvgdump.c, testcvg.c
			nprogs/nmap/source/vgf/nmap_pghdlb.c, nmap_pgvgf.c,
			nmap_pgwlst.c
			gempak/include/vgstruct.h

021tt.	2/17/98		NEW:gempak/source/cgemlib/crg/crgclroffst.c,
			crgget.c, crggetinx.c, crggoffset.c, crgnewinx.c,
			crgsave.c, crgset.c, crgsetltln.c, crgsetsym.c, 
			crgsettxt.c, crgsetwnd.c
			gempak/include/pgprm.h

			gempak/source/cgemlib/crg/crgclear.c, crginit.c
			gempak/source/cgemlib/cvg/cvgload.c, cvgrfrsh.c,
			cvgscan.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgfilw.c,
			nmap_pghdlb.c, nmap_pgpalw.c, nmap_pgvgf.c, 
			nmap_pgwlst.c
			gempak/error/crg.err
			gempak/include/crgcmn.h
			gempak/install/setup_links, remove_links

021uu.	2/17/98		gempak/source/cgemlib/cvg/cvgsvtxt.c
			nprogs/nmap/source/vgf/nmap_pgtxt.c

011i.	2/17/98		gempak/source/gemlib/in/incclr.f, inccol.f,
			testin.f
			gempak/source/programs/sf/sfmap/sfmap.f, sfmclr.f,
			sfmopt.f, sfmplt.f, sfmprm.f
			nprogs/nmap/source/nmap_sfmap.f
			gempak/error/in.err
			gempak/tables/config/prmlst.tbl

007p.	2/17/98		gempak/source/device/plot/dtext.f
			gempak/source/device/draw/itxbox.f
			gempak/source/driver/active/xw/xstext.c

021vv.	2/18/98		nprogs/nmap/source/vgf/nmap_pgevt.c

018q.	2/18/98		nprogs/nmap/source/nmap_image.c

010hh.	2/18/98		gempak/source/gemlib/fl/flmfil.f, flmfls.f, 
			flmnam.f, fltmpl.f, testfl.f

007r.	2/18/98		gempak/source/driver/active/utf/uinita.c, uopen.c

007s.	2/18/98		NEW:gempak/source/driver/active/ps/hscolb.f	

			gempak/source/driver/active/ps/hscolr.f, pscolr.c

007t.	2/18/98		gempak/source/driver/active/xw/xstext.c

021ww.	2/18/98		nprogs/nmap/source/vgf/nmap_pgevt.c

021xx.	2/18/98		NEW:nprogs/nmap/source/vgf/nmap_pbobj.c

			nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgvgf.c

018r.	2/19/98		NEW:gempak/tables/nmap/ffg_stn.tbl

			nprogs/nmap/source/nmap_dataw.c, nmap_domt.c,
			nmap_dslw.c, nmap_dsp.c, nmap_dsrc.c, nmap_sfm.c,
			nmap_stbl.c, nmap_data.h, nmap_stbl.h
			gempak/tables/nmap/sfc_stn.tbl, ship_stn.tbl,
			dcatg.nmap, dsrc.nmap, master.nmap

007u.	2/20/98		gempak/source/driver/active/ps/pdots.c, pfill.c, 
			pline.c, pscnam.c, ptext.c
			gempak/source/driver/active/xwp/hscolb.f, hscolr.f

018s.	2/23/98		nprogs/nmap/source/nmap_sfmap.f
			gempak/tables/config/prmlst.tbl
			gempak/tables/nmap/ffg_stn.tbl, ship_stn.tbl
			gempak/help/colors.hl2
			gempak/txt/programs/sfmap.txt

018t.	2/23/98		nprogs/nmap/source/nmap_image.c

008n	2/23/98		gempak/help/txtloc.hl2

001p.	2/24/98		NEW:gempak/source/bridge/ls/lssec1.f

			gempak/source/bridge/ls/lsdcd1.f, lsdcod.f, 
			lsgrpt.f, lsiihb.f, lslscb.f, lsnddf.f

015a.	2/24/98		NEW:nprogs/nsat/source/nsat_compile

			nprogs/nsat/source/dslw.c, Makefile

=========================== Patch 5.4.3.g =================================

010ii.	2/27/98		gempak/source/gemlib/ss/ssvers.f

021yy.	2/27/98		NEW:gempak/tables/pgen/frontbtn.tbl, linebtn.tbl,
			windbtn.tbl
			icons/nmap/cold_diss.xbm, cold_forming.xbm, dryline.xbm,
			exit.xbm, front.xbm, line.xbm, occl_diss.xbm, 
			occl_forming.xbm, stat_diss.xbm, stat_forming.xbm,
			warm_diss.xbm, warm_forming.xbm, wind.xbm

			nprogs/nmap/source/vgf/nmap_pgpalw.c
			gempak/tables/pgen/classbtn.tbl, funcbtn.tbl

018u.	2/27/98		nprogs/nmap/source/nmap_mapw.c

021zz.	2/27/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgwndw.c,
			nmap_pgfrtw.c, nmap_pgline.c

010jj.	2/27/98		gempak/source/cgemlib/crg/testcrg.c, testcrg_link

006e.	3/2/98		NEW:gempak/source/testprog/atest.f
			gempak/source/gplt/attribute/gqsmth.f, gssmth.f
			gempak/source/appl/attribute/gqsmth.f, gssmth.f
			gempak/source/device/attribute/dssmth.f
			gempak/source/device/curve/dcgaus.f, despln.f, dgauss.f,
			dmatrx.f, dsplin.f
			gempak/source/driver/active/gn/hssmth.f
			gempak/source/driver/active/vg/hssmth.f, vssmth.c

			gempak/source/gplt/access/ginit.f
			gempak/source/gplt/attribute/gsattr.f
			gempak/source/gplt/main/gplt.f
			gempak/source/device/main/device.f
			gempak/source/device/plot/dfill.f, dfrnt.f, dline.f, 
			dspln.f
			gempak/source/driver/active/fax/hinit.f
			gempak/source/driver/active/gn/hinit.f, hssmth.f
			gempak/source/driver/active/nc/hinit.f
			gempak/source/driver/active/ps/hinit.f
			gempak/source/driver/active/utf/hinit.f
			gempak/source/driver/active/vg/hinit.f, vgcmn.h
			gempak/source/driver/active/xw/hinit.f
			gempak/source/driver/active/xwp/hinitps.f, hinitxw.f
			gempak/build/device_compile
			gempak/include/devact.cmn, devchr.cmn, devreq.cmn,
			devset.cmn, funccode.prm, uscore.h

021aaa.	3/3/98	 	NEW:gempak/source/cgemlib/cgr/cgrsegdist.c
			icons/nmap/prtdel.xbm

			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgpal.c
			gempak/source/cgemlib/cgr/cgrdist.c
			gempak/include/drwids.h
			gempak/tables/pgen/funcbtn.tbl

010kk.	3/3/98		NEW:gempak/source/gemlib/dg/dgmfil.f, dgufil.f

			gempak/source/gemlib/dg/dgclal.f, dgclos.f, dgrdat.f,
			testdg.f, testdg_link
			gempak/include/dgcmn.cmn

010ll.	3/4/98		gempak/source/cgemlib/cfl/cfltrln.c

010mm.	3/5/98		gempak/source/gemlib/sn/testsn.f

010nn.	3/5/98		gempak/source/cgemlib/cfl/cvltrln.c
			gempak/error/cfl.err

007v.	3/5/98		gempak/source/device/draw/ifpips.c, ifrnt.c
			gempak/source/device/plot/dfrnt.f

021bbb.	3/9/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgvgf.c,
			nmap_pgpal.c, nmap_pgfil.c
			gempak/source/cgemlib/cvg/cvgwndsto.c, cvgsymsto.c,
			cvgwbsto.c

021ccc.	3/9/98		NEW:icons/turb/turb00.xbm, turb01.xbm, turb02.xbm,
			turb03/xbm, turb04.xbm, turb05.xbm, turb06.xbm,
			turb07.xbm, turb08.xbm, turb46.xbm, turb67.xbm

			gempak/source/nxmlib/NxmTxtA.c
			gempak/utilities/xbm/nmapxbms.csh

011j.	3/10/98		gempak/source/programs/sf/sfmap/sfmplt.f

001q.	3/10/98		NEW:gempak/source/bridge/dc/dcifpc.f, dcifpr.f

021ddd.	3/10/98		gempak/source/nxmlib/NxmTxtA.c

010oo.	3/10/98		gempak/source/gemlib/dg/dgufil.f

021eee.	3/10/98		nprogs/nmap/source/vgf/nmap_pgfilw.c

016a.	3/11/98		NEW:nprogs/nwx/source/interface.h, nwx_compile

			nprogs/nwx/source/Makefile, nwx.c

002b.	3/11/98		NEW:gempak/source/gemlib/gb/gbtdlens.c

			gempak/source/gemlib/gb/gbpds.c

021fff.	3/12/98		gempak/source/nxmlib/NxmClrW.c
			nprogs/nmap/source/vgf/nmap_pgline.c

021ggg. 3/12/98		nprogs/nmap/source/vgf/nmap_pgevt.c, 
			nmap_pgpal.c

010pp.	3/12/98		NEW:gempak/source/cgemlib/ctb/ctbpldump.c,
			ctbplget.c, ctbpllist.c, ctbplrd.c, ctbplset.c

			gempak/source/cgemlib/ctb/testctb.c
			gempak/include/ctbcmn.h
			gempak/tables/config/prmlst.tbl

021hhh.	3/12/98		NEW:gempak/source/cgemlib/cds/cdsress.c, cdsscal.c
			gempak/tables/pgen/scale.fix

			gempak/source/cgemlib/cds/cdsfrnt.c, cdsinit.c,
			cdsline.c, cdsspln.c, cdssymb.c, cdstext.c,
			cdswind.c
			gempak/source/programs/gp/gpmap/gpmap.f
			gempak/help/vgfile.hl1, vgfile.hl2
			

006f.	3/16/98		NEW:gempak/source/appl/attribute/gsdash.f, 
			gqdash.f
			gempak/source/gplt/attribute/gsdash.f, gqdash.f
			gempak/source/gplt/device/attribute/dsdash.f
			gempak/source/driver/active/vg/vsdash.c, hsdash.f
			gempak/source/driver/active/gn/hsdash.f

			gempak/source/testprog/atest.f, plotsyms.f
			gempak/source/gplt/main/gplt.f
			gempak/source/gplt/attribute/gsattr.f
			gempak/source/gplt/access/ginit.f
			gempak/source/device/main/device.f
			gempak/source/device/draw/idash.f
			gempak/source/driver/active/vg/vgcmn.h
			gempak/source/driver/active/xw/hinit.f
			gempak/source/driver/active/nc/hinit.f
			gempak/include/funccode.prm, devreq.cmn,
			devset.cmn, devact.cmn, uscore.h

006g.	3/16/98		gempak/source/device/attribute/dstext.f
			gempak/source/device/plot/dtext.f
			gempak/help/text.hl2

021iii.	3/16/98		gempak/source/nxmlib/NxmTxtA.c

008i.	3/16/98		gempak/help/device.hl2

021jjj.	3/16/98		gempak/source/cgemlib/cvg/cvgsvfnt.c,
			cvgsvsln.c, cvgsvlin.c, testcvg.c

001r.	3/16/98		gempak/source/bridge/ls/lsdcod.f, lsgemp.f, 
			lsint.f, lstemp.f, lswgem.f
			gempak/tables/pack/lsfc.pack

021kkk.	3/17/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgpalw.c,
			nmap_pgsymb.c

010rr.	3/17/98		NEW:gempak/source/cgemlib/ctb/ctbplgcc.c, ctbplsdef.c

			gempak/source/cgemlib/ctb/ctbpldump.c, ctbplget.c, 
			ctbplrd.c, ctbplset.c, testctb.c

			gempak/include/ctbcmn.h
			gempak/tables/config/prmlst.tbl

006h.	3/18/98		NEW:icons/nmap/lgtssicing.xbm, modtstmsnw.xbm, 
			hvyssicing.xbm, hvyrain.xbm, hvsnow.xbm

			gempak/source/driver/active/vg/vgsymb.c
			gempak/source/driver/active/utf/usymb.c
			gempak/source/device/draw/iicng.f
			gempak/source/testprog/plotsyms.f
			gempak/utilities/xbm/nmapxbms.csh

001s.	3/18/98		NEW:gempak/source/bridge/ua/*
			gempak/tables/snstns_land.tbl, snstns_ship.tbl
			gempak/error/ua.err

			gempak/build/bridge_compile

021lll.	3/18/98		gempak/source/cgemlib/ces/ceschng.c, ceselset.c,
			cesrstng.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgvgf.c,
			nmap_pgwndw.c
			gempak/tables/pgen/newdraw.tbl

007w.	3/23/98		NEW:gempak/source/driver/active/xw/hsfill.f, xsfill.c
			gempak/source/driver/active/ps/hsfill.f, psfill.c
			gempak/source/driver/active/nc/hsfill.f, msfill.c
			gempak/source/driver/active/xwp/hsfill.f
			gempak/source/driver/active/vg/hsfill.f, vgfill.c
			gempak/source/driver/active/fax/pattern.h
			gempak/source/driver/active/xw/stipple.h

			gempak/source/driver/active/fax/rsfill.c, rscnfll.c,
			rinita.c
			gempak/source/driver/active/xw/xfill.c
			gempak/source/driver/active/ps/psopen.c, pfill.c
			gempak/source/driver/active/nc/mfill.c
			gempak/source/driver/active/vg/vfill.c
			gempak/source/device/draw/imark.f, iquad.f, itrif.f,
			isymb.f
			gempak/source/device/plot/dfrnt.f, dlogo.f
			gempak/source/cgemlib/cds/cdsline.c, cdsspln.c, cdscntr.c
			gempak/source/cgemlib/cvg/cvgdump.c
			nprogs/ntrans/source/commands.c, process_meta.c
			gempak/include/xwcmn.h, uscore.h
			gempak/source/driver/active/ps/pscmn.h
			gempak/source/driver/active/nc/nccmn.h
			gempak/source/driver/active/vg/vgcmn.h
			nprogs/ntrans/include/defs.h


007x.	3/24/98		gempak/source/driver/active/ps/pfill.c

001t.	3/25/98		gempak/source/bridge/af/afdcod.f, afdrco.f, afifpt.f,
			afxbif.f

010ss.	3/25/98		NEW:gempak/source/cgemlib/ctb/ctbtdump.c, ctbdtfcst.c,
			ctbdtget.c, ctbtpath.c, ctbdtrd.c, ctbttime.c,
			ctbdttmpl.c
			gempak/source/cgemlib/cfl/cfltbnr.c

			gempak/source/cgemlib/ctb/testctb.c
			gempak/source/cgemlib/cfl/testcfl.c
			gempak/include/ctbcmn.h
			gempak/tables/config/data.tbl

021mmm.	3/26/98		NEW:gempak/source/cgemlib/crg/crggsel.c, crgoffset.c, 
			crgssel.c
			icons/nmap/multisel.xbm
			gempak/source/cgemlib/crg/crgclear.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgfil.c, 
			nmap_pghdlb.c, nmap_pgpalw.c
			gempak/include/crgcmn.h, drwids.h
			gempak/tables/pgen/funcbtn.tbl

021nnn. 3/26/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgpalw.c

021ooo.	3/26/98		nprogs/nmap/source/vgf/nmap_pgsymb.c, nmap_pgevt.c,
			nmap_pgpalw.c, nmap_pgvgf.c

006i.	3/30/98		NEW:gempak/source/appl/plot/gdarr.f, ghash.f
			gempak/source/appl/attribute/gsdarr.f, gqdarr.f,
			gshash.f, gqhash.f
			gempak/source/appl/color/gsclr2.f, gqclr2.f
			gempak/source/gplt/plot/gdarr.f, ghash.f
			gempak/source/gplt/attribute/gsdarr.f, gqdarr.f, 
			gsdash.f, gqdash.f
			gempak/source/gplt/color/gsclr2.f, gqclr2.f, gscolr.f,
			gempak/source/gplt/device/plot/ddarr.f, dhash.f
			gempak/source/gplt/device/attribute/dsdarr.f, dshash.f
			gempak/source/gplt/device/color/dsclr2.f
			gempak/source/device/plot/ddarr.f, dhash.f
			gempak/source/device/attribute/dsdarr.f, dshash.f
			gempak/source/device/color/dscolr.f

			gempak/source/appl/color/gscolr.f
			gempak/source/gplt/color/gscolr.f
			gempak/source/gplt/device/color/dscolr.f
			gempak/source/device/color/dscolr.f
			gempak/source/gplt/main/gplt.f
			gempak/source/gplt/attribute/gsattr.f
			gempak/source/gplt/access/ginit.f
			gempak/source/device/main/device.f
			gempak/source/testprog/atest.f
			gempak/include/funccode.prm, devact.cmn, devset.cmn,
			devreq.cmn

021ppp.	3/30/98		nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgsymb.c,
			nmap_pgobj.c
			gempak/tables/pgen/symbolbtn.tbl
			gempak/include/drwids.h

001u.	3/31/98		gempak/source/bridge/dc/dcfcyl.f

010tt.	3/31/98		gempak/source/gemlib/in/inaxis.f

010uu.	3/31/98		gempak/source/gemlib/ti/tiitoc.f

010vv.	3/31/98		NEW:gempak/source/cgemlib/ctb/ctbplsdef.c

			gempak/source/cgemlib/ctb/testctb.c

018v.	3/31/98		NEW:gempak/source/gemlib/st/strnul.f
			gempak/tables/nmap/metar_parms.tbl, ship_parms.tbl,
			uair_parms.tbl

			nprogs/nmap/source/nmap_data.h, nmap.c, nmap_dataw.c,
			nmap_dslw.c, nmap_dsp.c, nmap_sfm.c, nmap_snm.c,
			nmap_sfmw.c, nmap_stnmw.c, nmap_uairw.c, nmap_sfmap.f,
			nmap_snmap.f
			gempak/source/cgemlib/ctb/ctbplget.c
			gempak/tables/config/prmlst.tbl

021qqq.	4/1/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgwndw.c

021rrr.	4/1/98		NEW:icons/nmap/all.xbm

			nprogs/nmap/source/vgf/nmap_pgpal.c, nmap_pgevt.c, 
			nmap_pghdlb.c
			gempak/include/drwids.h
			gempak/tables/pgen/classbtn.tbl

021sss.	4/1/98		NEW:icons/nmap/srainsh_ssnowsh.xbm, srainsh_smtstrm.xbm,
			iceplts_sfdrzl.xbm, cssnow_ssnowsh.xbm, csrain_srainsh.xbm,
			csrain_smtstrm.xbm, csrain_sfdrzl.xbm, csrain_cssnow.xbm,
			csrain_csdrzl.xbm, csdrzl_sfdrzl.xbm

021ttt.	4/1/98		NEW:gempak/source/cgemlib/crg/crgggbnd.c, crggginx.c, 
			crgggnel.c, crgggnxt.c, crgggrp.c, crgsgrp.c

			gempak/source/cgemlib/crg/crgclear.c, crgset.c, 
			testcrg.c
			gempak/source/cgemlib/cvg/cvgsetginf.c
			gempak/include/crgcmn.h

010ww	4/3/98		gempak/source/gemlib/fltmpl.f

001v.	4/3/98		NEW:gempak/source/bridge/dc/dcwthr.f

			gempak/source/bridge/af/afbltp.f, afdcod.f, afpwxv.f, 
			afslat.f, afslon.f

021uuu. 4/3/98		NEW:icons/nmap/any.xbm 

			nprogs/nmap/source/vgf/nmap_pgpal.c, nmap_pgevt.c
			gempak/include/drwids.h
			gempak/tables/pgen/classbtn.tbl

021vvv. 4/3/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgpalw.c, 
			nmap_pghdlb.c, nmap_pggrpw.c
			gempak/include/pgprm.h

007y.	4/6/98		gempak/source/device/draw/itxsy.f

007z. 	4/6/98		gempak/source/device/draw/itxbox.f

007aa.	4/6/98		gempak/source/device/plot/dhash.f

021www. 4/6/98		NEW:icons/nmap/combsymb.xbm

001w.	4/6/98		gempak/source/bridge/af/afbltp.f

010xx.	4/7/98		gempak/source/cgemlib/cfl/cfltbnr.c, testcfl.c
			gempak/source/cgemlib/ctb/ctbdtrd.c
			nprogs/nmap/source/vgf/nmap_pgprpw.c

010yy.	4/7/98		gempak/source/gemlib/im/imsimg.f
			gempak/source/gemlib/sf/sfacny.f
			gempak/source/bridge/sc/scifpt.f
			gempak/source/bridge/dc/dcb.c
			gempak/source/bridge/ls/lssec1.f
			gempak/source/nxmlib/NxmHelp.c

018w.	4/7/98		nprogs/nmap/source/nmap_snmap.f

018x	4/7/98		nprogs/nmap/source/nmap_stnm.h, nmap_sfmap.f, 
			nmap_snmap.f, nmap_stnmw.c, nmap_uairw.c
			gempak/source/gemlib/in/inprmc.f
			gempak/include/ctbcmn.h
			gempak/tables/nmap/metar_parms.tbl, ship_parms.tbl
			gempak/tables/config/parmlst.tbl

021xxx.	4/7/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pghdlb.c 

021yyy.	4/7/98		gempak/source/cgemlib/cds/cdsfrnt.c, cdsinit.c, 
			cdsline.c, cdsspln.c
			gempak/source/cgemlib/cvg/cvgfrsto.c, cvglinsto.c, 
			cvgsplsto.c, cvgsvfnt.c, cvgsvlin.c, cvgsvsln.c,
			testcvg.c
			gempak/source/driver/active/vg/vfill.c, vfrnt.c, 
			vline.c, vspln.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgfrtw.c,
			nmap_pgline.c, nmap_pgvgf.c
			gempak/include/vgstruct.h
			gempak/source/cgemlib/cds/cds.h

021zzz. 4/8/98		nprogs/nmap/source/nmap_mbtnw.c, nmap_mmenuw.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgpalw.c

010zz.	4/8/98		NEW:gempak/source/cgemlib/clo/clocompass.c, clodirect.c,
			clodist.c, clorolseg.c, testclo.c, testclo_link

005d.	4/8/98		gempak/source/gemlib/im/imcbar.f
			gempak/source/gemlib/gg/ggcbar.f

006j.	4/9/98		gempak/source/device/curve/dsplin.f, dcgaus.f

021a1a.	4/9/98		gempak/source/cgemlib/cpg/cpgdmpct.c

021a1b. 4/9/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgwndw.c
			resource/Nmap

021a1c.	4/10/98		gempak/include/vgstruct.h

021a1d.	4/14/98		NEW:icons/fillPatt/patt00.xbm, patt01.xbm, patt02.xbm

			nprogs/nmap/source/vgf/nmap_pgline.c

010aaa. 4/14/98		gempak/source/cgemlib/clo/testclo.c

001x.	4/14/98		gempak/source/bridge/ls/lsdcod.f, lsintf.f
			gempak/tables/pack/lsfc.pack
			gempak/error/dclsfc.err

010bbb.	4/15/98		NEW:gempak/tables/nmap/acft_parms.tbl, synop_parms.tbl
			
			gempak/source/gemlib/pc/pcfunc.tbl
			gempak/tables/config/prmlst.tbl
			gempak/tables/parms/pcconv.tbl

010ccc.	4/15/98		gempak/source/gemlib/dm/dmrhda.f, dmwclh.f, dmwrwh.f

021a1e. 4/16/98		NEW:gempak/source/driver/active/gn/hhash.f, hshash.f
			gempak/source/driver/active/vg/vhhash.f,vhash.c, vshash.c

			gempak/source/device/plot/dhash.f
			gempak/source/driver/active/vg/vswind.c, vwind.c
			gempak/source/driver/active/fax/hinit.f
			gempak/source/driver/active/vg/hinit.f, vgcmn.h
			gempak/source/driver/active/xwp/hinitps.f, hinitxw.f
			gempak/source/driver/active/nc/hinit.f
			gempak/source/driver/active/ps/hinit.f
			gempak/source/driver/active/utf/hinit.f
			gempak/source/driver/active/xw/hinit.f
			gempak/source/driver/inactive/hp/hinit.f
			gempak/source/driver/inactive/vc/hinit.f
			gempak/source/driver/inactive/vt/hinit.f
			gempak/source/cgemlib/cds/cdsdspvg.c, cdswind.c
			gempak/source/cgemlib/cvg/cvgdump.c
			gempak/include/uscore.h, devchr.cmn

021a1f.	4/16/98		gempak/source/cgemlib/cvg/cvgcp.c, cvgrdele.c

006k.	4/20/98		NEW:gempak/source/device/draw/iarc.f, ispln.f, 
			ipatln.f
			gempak/tables/draw/splpat.tbl

			gempak/source/testporg/plotsyms.f
			gempak/source/appl/attribute/gsspln.f
			gempak/source/gplt/attribute/gsspln.f
			gempak/source/gplt/plot/gspln.f, gfrnt.f
			gempak/source/device/attribute/dsspln.f,
			dsfrnt.f
			gempak/source/device/plot/dspln.f, dfrnt.f
			gempak/source/device/draw/iarrw.f, icirc.f
			gempak/source/driver/active/fax/hinit.f
			gempak/source/driver/active/gn/hinit.f
			gempak/source/driver/active/nc/hinit.f
			gempak/source/driver/active/ps/hinit.f
			gempak/source/driver/active/utf/hinit.f
			gempak/source/driver/active/vg/hinit.f
			gempak/source/driver/active/xw/hinit.f
			gempak/source/driver/active/xwp/hinitxw.f, hinitps.f
			gempak/build/device_compile


018y.	4/21/98		NEW:nprogs/nmap/source/nmapprm.h
			gempak/include/xwprm.h

			nprogs/nmap/source/nmap_data.h, nmap.c, nmap_dataw.c,
			nmap_domt.c, nmap_dslw.c, nmap_dsp.c, nmap_dsrc.c,
			nmap_image.c, nmap_loopw.c, nmap_mapw.c, nmap_mbotw.c,
			nmap_mdl.c, nmap_rad.c, nmap_sfm.c, nmap_sfmw.c, 
			nmap_snm.c, nmap_stnmw.c, nmap_uairw.c, nmap_vgf.c
			gempak/include/xwcmn.h
			gempak/tables/nmap/dcatg.nmap, dsrc.nmap, master.nmap
			gempak/install/setup_links, remove_links

021a1g.	4/21/98		NEW:icons/nmap/textud.xbm

			nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgvgf.c,
			nmap_pgobj.c, nmap_pgtxt.c
			gempak/include/drwids.h
			gempak/tables/pgen/textbtn.tbl

021a1h.	4/21/98		gempak/source/cgemlib/crg/crgsetwnd.c

021a1i. 4/21/98		nprogs/nmap/source/vgf/nmap_pgline.c
			gempak/source/nxmlib/NxmClrW.c

010ddd.	4/21/98		gempak/source/gemlib/dg/dgclos.f

018x.	4/22/98		nprogs/nmap/source/nmap_mbtnw.c, nmap_uairw.c

006l.	4/22/98		gempak/source/device/plot/ddarr.f
			gempak/source/device/attribute/dshash.f

021a1j.	4/22/98		gempak/source/cgemlib/cvg/cvgcp.c

001y.	4/22/98		NEW:gempak/source/bridge/mt/mtifpt.f, mtinit.f, mtinf.f,
			mtelog.f

			gempak/source/bridge/mt/*
			gempak/source/programs/dc/dcmetr/dcmetr.c
			gempak/source/bridge/dc/dcifpc.f, dcifpr.f
			gempak/source/bridge/ra/rartim.f
			gempak/error/dcmetr.err, mt.err
			gempak/tables/pack/metar.pack

021a1k.	4/22/98		NEW:icons/nmap/spln1.xbm,spln2.xbm, spln3.xbm,
			spln4.xbm, spln5.xbm, spln6.xbm, spln7.xbm,
			spln8.xbm, spln9.xbm, spln10.xbm, spln11.xbm,
			spln12.xbm, spln13.xbm, spln14.xbm, spln15.xbm,
			spln16.xbm, spln17.xbm, spln18.xbm, spln19.xbm

021a1l.	4/22/98		NEW:gempak/source/cgemlib/crg/crggtyp.c, crgstyp.c
			gempak/source/cgemlib/crg/crgset.c, testcrg.c
			gempak/include/crgcmn.h

021a1m.	4/23/98		NEW:icons/nmap/ungroup.xbm

			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgfilw.c,
			nmap_pggrpw.c, nmap_pghdlb.c, nmap_pgpalw.c
			gempak/tables/pgen/funcbtn.tbl
			gempak/include/drwids.h

006m.	4/23/98		gempak/source/device/curve/dcgaus.f, dsplin.f

011k.	4/23/98		gempak/source/programs/sf/sfmap/sfmcof.f, snmcof.f

006n.	4/23/98		gempak/source/device/draw/ipatln.f
			gempak/source/driver/active/xw/htext.f
			gempak/source/driver/active/nc/htext.f
			gempak/source/driver/active/xwp/htext.f

021a1n.	4/23/98		NEW:gempak/tables/pgen/combsymbbtn.tbl

			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgobj.c,
			nmap_pgpalw.c, nmap_pgvgf.c
			gempak/include/drwids.c
			gempak/tables/pgen/newdraw.tbl, classbtn.tbl, linebtn.tbl

019a.	4/24/98		NEW:gempak/tables/stns/nwscity1.tbl, nwscity2.tbl,
			nwscity3.tbl, cwa.tbl

			gempak/maps/loznus.nws, hiznus.nws, cwa.nws
			gempak/maps/ascii/ascloznus.nws, aschiznus.nws,
			ascdcwa.nws

021a1o.	4/24/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgline.c,
			nmap_pgtxt.c, nmap_pgfrtw.c, nmap_pgpalw.c, 
			nmap_pgvgf.c
			gempak/source/nxmlib/NxmTxtA.c

021a1p.	4/24/98		NEW:icons/nmap/label.xbm

001z.	4/24/98		gempak/source/bridge/af/afintf.f
			gempak/source/bridge/ls/lsintf.f
			gempak/tables/config/prmlst.tbl
			gempak/tables/nmap/acft_parms.tbl, synop_parms.tbl
			gempak/tables/pack/acft.pack, lsfc.pack

001aa.	4/24/98		NEW:gempak/source/bridge/dc/dctmck.f

			gempak/source/bridge/af/afdcod.f

018aa.	4/27/98		nprogs/nmap/source/nmap_rad.c

021a1q.	4/27/98		NEW:gempak/source/cgemlib/ces/cesget.c, cesgetinx.c,
			cesrtbl.c, cesset.c

			gempak/source/cgemlib/ces/testces.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgfrtw.c,
			nmap_pgline.c, nmap_pgpalw.c, nmap_pgsymb.c, 
			nmap_pgvgf.c, nmap_pgwndw.c
			gempak/source/programs/util/avnbul/avnbul.c,
			bavcntr.c, bavline.c
			gempak/error/ces.err
			gempak/include/cescmn.h, pgprm.h
			gempak/tables/pgen/newdraw.tbl


006o.	4/27/98		gempak/source/device/plot/ddarr.f

006p.	4/28/98		gempak/source/device/draw/ipatln.f
			gempak/source/device/curve/dcgaus.f, dsplin.f

021a1r.	4/28/98		nprogs/nmap/source/vgf/nmap_pgvgf.c, nmap_pgobj.c

021a1s.	4/28/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgline.c
			gempak/source/nxmlib/NxmTxtA.c

021a1t.	4/28/98		NEW:icons/nmap/copy.xbm

			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgpalw.c
			gempak/tables/pgen/funcbtn.tbl
			gempak/include/drwids.h
			icons/nmap/copy.xbm

021a1u.	4/28/98		gempak/source/cgemlib/cds/cdsfrnt.c
			gempak/tables/pgen/newdraw.tbl

021a1v.	4/28/98		NEW:icons/nmap/outlook.xbm
			nprogs/nmap/source/vgf/nmap_pgolk.c

			nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgevt.c,
			nmap_pggrpw.c, nmap_pghdlb.c, nmap_pgvgf.c
			gempak/include/drwids.h
			gempak/tables/pgen/funcbtn.tbl, grptyp.h, spcbtn.h

021a1w.	4/29/98		NEW:icons/nmap/iceplts_sfrain.xbm

			nprogs/nmap/source/vgf/nmap_pgpalw.c
			gempak/tables/pgen/combysymbbtn.tbl

021a1x.	4/29/98		gempak/source/cgemlib/ces/cesrtbl.c, cesset.c, cesget.c
			gempak/source/cgemlib/crg/crgclear.c

021a1y.	4/29/98		nprogs/nmap/source/vgf/nmap_pgolk.c
			resource/Nmap
			icons/nmap/outlook.xbm

006r.	4/29/98		gempak/source/device/draw/ipatln.f

021a1z.	4/29/98		gempak/source/cgemlib/crg/crgsetwnd.c, crgset.c

006s.	4/29/98		NEW:gempak/source/device/curve/dprmtc.f

			gempak/source/device/plot/dfill.f, dline.f, dspln.f
			gempak/source/cgemlib/ces/cdsfrnt.c, cdsline.c, cdsspln.c

			(Documentation only):
			gempak/source/device/attribute/dssmth.f
			gempak/source/gplt/device/attribute/dssmth.f
			gempak/source/gplt/attribute/gssmth.f
			gempak/source/appl/attribute/gssmth.f

021a2a.	4/29/98		nprogs/nmap/source/vgf/nmap_pgpalw.c

006t.	4/30/98		gempak/source/device/curve/dprmtc.f
			gempak/source/cgemlib/cds/cdsinit.c

021a2b.	4/30/98		NEW:icons/nmap/darr.xbm, hash.xbm

			nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgobj.c,
			nmap_pgwndw.c, nmap_pgevt.c
			gempak/source/cgemlib/cds/cdswind.c
			gempak/source/cgemlib/ces/cesset.c, cesget.c, cesrtbl.c
			gempak/source/cgemlib/cvg/cvgtodev.c
			gempak/include/drwids.h
			gempak/tables/pgen/newdraw.tbl, windbtn.tbl

018bb.  4/30/98		nprogs/nmap/source/nmap_dataw.c

021a2c.	4/30/98		nprogs/nmap/source/vgf/nmap_pgevt.c

006u.	4/30/98		gempak/source/device/plot/ddarr.f

021a2d.	5/1/98		gempak/source/cgemlib/crg/crgsetwnd.c

010eee.	5/1/98		gempak/source/gemlib/dg/testdg.f

021a2e.	5/1/98		nprogs/nmap/source/vgf/nmap_pgevt.c

010fff.	5/4/98		gempak/source/cgemlib/cfl/testcfl.c

021a2f.	5/4/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgline.c,
			nmap_pgpalw.c

021a2g.	5/4/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgfrtw.c,
			nmap_pgline.c, nmap_pgpalw.c, nmap_pgwndw.c

021a2h.	5/4/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pghdlb.c
			NEW: gempak/source/cgemlib/crg/crgdeselect.c

006v.	5/4/98		gempak/source/device/plot/dhash.f

021a2i.	5/4/98		nprogs/nmap/source/vgf/nmap_pgpalw.c
			resource/Nmap
			gempak/tables/pgen/classbtn.tbl, combsymbbtn.tbl,
			frontbtn.tbl, funcbtn.tbl, linebtn.tbl, newdraw.tbl,
			symbolbtn.tbl, textbtn.tbl
			NEW: icons/nmap/vector.xbm
			     gempak/tables/pgen/vectorbtn.tbl

011l.	5/5/98		gempak/source/gemlib/in/inpwnd.f
			gempak/source/programs/sf/sfmap/sfmplt.f, sfmprm.f
			gempak/source/programs/sf/sfgram/sfxprm.f, sfxwnd.f
			gempak/source/programs/sn/snmap/sfnplt.f
			gempak/tables/parms/pcconv.tbl
			gempak/tables/nmap/ship_parms.tbl
			gempak/help/sfparm.hl2
			gempak/txt/apx/parms.apx

021a2j.	5/5/98		NEW:nprogs/nmap/source/vgf/nmap_pgprd.c, 
			nmap_pgsfp.c
			icons/nmap/sfcprg.xbm, prod.xbm
			gempak/tables/pgen/prodbtn.tbl

			nprogs/nmap/source/vgf/nmap_pgolk.c, nmap_pgpalw.c
			gempak/include/drwids.h
			gempak/tables/pgen/classbtn.tbl
			resource/Nmap

021a2k.	5/5/98		NEW:gempak/tables/pgen/setting.tbl

			gempak/include/pgprm.h 

018cc.	5/6/98		nprogs/nmap/source/nmap_dataw.c

021a2l.	5/6/98		nprogs/nmap/source/vgf/nmap_pgevt.c

=========================== Patch 5.4.3.h ==================================

010ggg.	5/11/98		gempak/source/gemlib/ss/ssvers.f

021a2m.	5/11/98		gempak/source/cgemlib/cvg/cvgload.c, cvgrfrsh.c
			nprogs/nmap/source/vgf/nmap_pghdlb.c

021a2n.	5/11/98		nprogs/nmap/source/vgf/nmap_pgfrtw.c, nmap_pgline.c,
			nmap_pgwndw.c

021a2o.	5/11/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pggrpw.c,
			nmap_pgpalw.c

010hhh.	5/11/98		gempak/source/cgemlib/ces/testces.c
			gempak/source/cgemlib/cvg/testcvg.c, dumpcvg.c

011m.	5/11/98		gempak/source/programs/gd/gdplot2/gdpltb.f, gdpwnd.f
			gempak/source/gemlib/in/intype.f
			gempak/help/type.hl2, wind.hl2

007bb.	5/13/98		gempak/source/cgemlib/ctb/ctbprod.c, testctb.c
			gempak/source/driver/active/fax/rinita.c, rsdatt.c,
			risched.c, rmapid.c, rclosp.c, rcvt6bt.c, rwrpxl.c
			gempak/include/faxcmn.h
			gempak/tables/pgen/faxprod.tbl

021a2p.	5/13/98		NEW:nprogs/nmap/source/vgf/nmap_pgundo.c

			nprogs/nmap/source/nmap_mmenuw.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgpal.c,
			nmap_pgvgf.c, nmap_pgfilw.c

012g.	5/13/98		NEW:gempak/include/undscr.h

			nprogs/guitst/source/guitst.c
			nprogs/nsat/source/enhw.c, gmpk.c, mcanvw.c, 
			mmenuw.c, pxm.c

021a2q.	5/13/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pghdlb.c

012h.	5/13/98		nprogs/ntrans/source/commands.c, drawingw.c, 
			gp_callbks.c, multipanel.c, ntrans.c, process_meta.c,
			select_frame.c, select_group.c, dsply.c, graf_init.c,
			NxmGmpk.c, ntrans_spool.c
			nprogs/ntl/source/colr.c
			gempak/include/undscr.h

012i.	5/14/98		nprogs/nwx/source/dir.c, draw.c, dslw.c, gmpk.c,
			mapw.c, srcho.c
			gempak/include/undscr.h

010iii.	5/14/98		gempak/source/cgemlib/cfl/cflscnd.c, cflmnam.c
			testcfl.c
			gempak/source/cgemlib/cpg/testcpg.c
			gempak/source/cgemlib/cgr/cgrinpoly.c, cgrpolyint.c,
			cgrsegint.c, testcgr.c
			gempak/include/undscr.h
			gempak/install/setup_links, remove_links

021a2r.	5/14/98		nprogs/nmap/source/vgf/nmap_pgpwndw.c

010jjj.	5/14/98		gempak/source/cgemlib/ctb/testctb.c, ctbplget.c,
			ctbdtdump.c, ctbdtfcst.c, ctbdtget.c, ctbdtpatch.c,
			ctbdtrd.c, ctbdttime.c, ctbdttmpl.c

021a2s.	5/14/98		gempak/source/cgemlib/cpg/cpggetmnuid.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pggrpw.c,
			nmap_pgpalw.c
			gempak/install/setup_links, remove_links

011n.	5/14/98		gempak/source/programs/gp/gptext/gptext.f
			gempak/help/txtloc.hl2

021a2t. 5/14/98		gempak/source/cgemlib/crg/crgsetwnd.c

010kkk.	5/18/98		gempak/source/cgemlib/cds/cdscntr.c, cdsfrnt.c, cdsgetfil.c,
			cdsinit.c, cdsline.c, cdsress.c, cdsscal.c, cdssetcol.c,
			cdssetfil.c, cdsspln.c
			gempak/include/undscr.h

010lll.	5/18/98		gempak/source/cgemlib/utf/testutf.c, utfdump.c, utfplot.c,
			utfptext.c, utfpvctr.c, utfpvev.c
			gempak/include/undscr.h

010mmm.	5/18/98		gempak/source/cgemlib/cvq/cvqgetginf.c, cvqhigp.c,
			cvqnxtgnm.c, cvqscangrp.c, testcvq.c,
			gempak/source/cgemlib/ces/testces.c,
			gempak/source/cgemlib/crg/crginit.c, crgsetltln.c,
			crgsetsym.c, crgsettxt.c, crgsetwnd.c, testcrg.c
			gempak/source/cgemlib/clo/cloancinpoly.c,
			clocntyinpoly.c, clovorinpoly.c
			gempak/include/undscr.h

010nnn.	5/18/98		gempak/source/driver/active/utf/uinita.c, usdatt.c
			gempak/include/undscr.h

010ooo.	5/18/98		gempak/source/gemlib/im/imrgin.c, imsbgn.c, imwgin.c
			gempak/source/programs/gui/nafos/nafgmpk.c, nafmcnvw.c,
			nafmenuw.c, nafpxm.c
			gempak/include/undscr.h

021a2u.	5/18/98		nprogs/nmap/source/vgf/nmap_pgpwndw.c, nmap_pgline.c

021a2v.	5/18/98		nprogs/nmap/source/nmap_image.c

001bb.	5/18/98		NEW: gempak/source/bridge/af/afcpas.f

			gempak/source/bridge/af/afalon.f, afploc.f, afpnbd.f

001cc.	5/18/98		NEW: gempak/source/bridge/mt/mtceil.f, mtgmsk.f

			gempak/source/bridge/dc/dcwthr.f
			gempak/source/bridge/ls/lscmn.cmn,
			lsifpt.f, lsintf.f, lstemp.f
			gempak/source/bridge/ma/macmn.cmn, maifpt.f, matemp.f,
			mtcmtn.f, mtdcod.f, mtgemp.f, mtintf.f, mtrmks.f
			gempak/source/gemlib/pr/testpr.f
			gempak/source/gemlib/pt/ptwnmt.f
			gempak/help/sfparm.hl2
			gempak/txt/apx/parms.apx
			gempak/tables/pack/metar.pack

021a2w.	5/18/98		nprogs/nmap/source/vgf/nmap_pgpalw.c

002c.	5/18/98		gempak/source/gemlib/gb/gbgpbd.c

002d.	5/18/98		gempak/source/gemlib/gb/gblamb.c

010ppp.	5/19/98		gempak/include/undscr.h
			gempak/source/bridge/dc/dcinit.c
			gempak/source/programs/dc/dcuair/dcuair.c
			gempak/source/programs/dc/dcnmos/dcnmos.c
			gempak/source/programs/dc/dcffg/dcffg.c
			gempak/source/programs/dc/dcmmos/dcmmos.c
			gempak/source/programs/dc/dchrly/dchrly.c
			gempak/source/programs/dc/dcamos/dcamos.c
			gempak/source/programs/dc/dcmetr/dcmetr.c
			gempak/source/programs/dc/dcscd/dcscd.c
			gempak/source/programs/dc/dcmsfc/dcmsfc.c
			gempak/source/programs/dc/dcacft/dcacft.c
			gempak/source/programs/dc/dclsfc/dclsfc.c

010qqq.	5/19/98		gempak/include/undscr.h
			gempak/source/programs/util/avnbul/avnbul.c,
			bavcb.c, bavextrtinfo.c, bavline.c, bavgetpoly.c,
			bavinitgplt.c, bavsplin.c, bavturb.c, bavcntr.c
			gempak/source/programs/util/vgfcvt/ocvgrdhdr.c

001dd.	5/19/98		gempak/source/bridge/af/afdadr.f

010rrr.	5/19/98		gempak/include/undscr.h
			gempak/source/nxmlib/NxmColrP.c, NuiColorInit.c,
			NxmColorBar.c, NxmColorBlink.c, NxmColorEdit.c,
			NxmColorTable.c, NxmColorPalette.c, NxmColorSliders.c,
			NxmEnhw.c, NxmErr.c

010sss.	5/19/98		gempak/source/cgemlib/cvg/cvgcntsto.c,
			cvgcp.c, cvgctddel.c, cvgctdsto.c, cvgdeall.c,
			cvgdelet.c, cvgdump.c, cvgfndhl.c, cvgfrsto.c,
			cvgindex.c, cvglinsto.c, cvgload.c, cvgrdctd.c,
			cvgrdhdr.c, cvgrdrec.c, cvgrdsel.c, cvgrfrsh.c,
			cvgscan.c, cvgsetginf.c, cvgsplsto.c, cvgsptsto.c,
			cvgsvcnt.c, cvgsvctd.c, cvgsvfhed.c, cvgsvfnt.c,
			cvgsvlin.c, cvgsvsln.c, cvgsvstx.c, cvgsvsym.c,
			cvgsvtxt.c, cvgsvwbx.c, cvgsvwnd.c, cvgsymsto.c,
			cvgtodev.c, cvgtxsto.c, cvgwbsto.c, cvgwndsto.c,
			dumpvgf.c, testcvg.c

008j.	5/19/98		gempak/source/appl/attribute/gqfrnt.f,
			gqptnd.f, gqsysz.f, gsfrnt.f
			gempak/source/appl/color/gsclr2.f
			gempak/source/appl/contour/gcboxx.f,
			gcfill.f, gclgrn.f, gcspln.f
			gempak/source/appl/control/ggtpnt.f
			gempak/source/appl/graph/gaaxis.f
			gempak/source/appl/grid/gsgmap.f
			gempak/source/appl/plot/gcircl.f
			gempak/source/appl/satellite/gsicmn.f
			gempak/source/appl/utility/gstrml.f

011o.	5/20/98		gempak/source/programs/gp/gptext/gptext.f

018dd.	5/20/98		nprogs/nmap/source/nmap_uairw.c

021a2x.	5/20/98		nprogs/nmap/source/vgf/nmap_pgevt.c
			gempak/source/cgemlib/cgr/cgrsegdist.c

021a2y.	5/20/98		nprogs/nmap/source/vgf/nmap_pgevt.c,
			nmap_pggrpw.c, nmap_pgpal.c

021a2z.	5/21/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgwlst.c

021a3a.	5/21/98		nprogs/nmap/source/vgf/nmap_pgline.c

018ee.	5/21/98		gempak/include/undscr.h
			nprogs/nmap/source/nmap.c, nmap_dataw.c, nmap_domt.c,
			nmap_dslw.c, nmap_dsp.c, nmap_dttmw.c, nmap_gmpk.c,
			nmap_image.c, nmap_mapw.c, nmap_mbotw.c, nmap_mcanvw.c,
			vgf/nmap_pgevt.c, vgf/nmap_pgfilw.c, vgf/nmap_pgfrtw.c,
			vgf/nmap_pghdlb.c, vgf/nmap_pgline.c, vgf/nmap_pgolk.c,
			vgf/nmap_pgpalw.c, vgf/nmap_pgsfp.c, vgf/nmap_pgvgf.c,
			vgf/nmap_pgwlst.c, vgf/nmap_pgwndw.c

007cc.	5/21/98		gempak/source/driver/active/xw/xpgsvfrm.c


007dd.	5/26/98		gempak/source/device/draw/ipatln.f

010ttt. 5/26/98		NEW:gempak/source/cgemlib/clo/clodltln.c

			gempak/source/cgemlib/clo/testclo.c

018ff.	5/26/98		nprogs/nmap/source/nmap_image.c, nmap_domt.c, 
			nmap_dataw.c
			gempak/source/cgemlib/cvg/cvgrsfsh.c
			gempak/tables/nmap/master.nmap

010uuu.	5/26/98		gempak/source/cgemlib/clo/clodltln.c

001ee.	5/26/98		gempak/source/bridge/af/afpnbd.f, afalon.f

021a3b.	5/27/98		nprogs/nmap/source/vgf/nmap_pgfrtw.c, nmap_pline.c

021a3c.	5/27/98		gempak/source/cgemlib/crg/crggtyp.c, crgset.c,
			crgstyp.c, testcrg.c
			gempak/source/cgemlib/cvg/cvgscan.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgolk.c, 
			nmap_pgpalw.c, nmap_pgsfp.c
			gempak/include/crgcmn.h

021a3d.	5/27/98		gempak/include/vgstruct.h

001ff.	5/27/98		gempak/source/bridge/sc/scifpt.f, scwea3.f

010vvv.	5/27/98		gempak/source/cgemlib/cgr/testcgr.c
			gempak/install/setup_links, remove_links

010www.	5/27/98		gempak/include/uscore.h, undscr.h

018gg.	5/27/98		nprogs/nmap/source/nmap_dsp.c, nmap_roamw.c

018hh.	5/28/98		nprogs/nmap/source/smfltm.f
			gempak/tables/nmap/master.nmap

021a3e.	5/28/98		NEW:gempak/source/cgemlib/cds/cdsdspelm.c, cdsgfill.c,
			cdsscol.c, cdssfill.c

			gempak/source/cgemlib/cds/cdsfrnt.c, cdsinit.c, 
			cdsline.c, cdsress.c, cdsscal.c, cds.h
			gempak/source/cgemlib/cvg/cvgload.c, cvgrfrsh.c
			nprogs/nmap/source/nmap.c
			nprogs/nmap/source/vgf/nmap_pgundo.c, nmap_pgvgf.c
			gempak/include/undscr.h
			gempak/error/cds.err

018ii.	5/28/98		nprogs/nmap/source/nmap_dsp.c
			gempak/source/driver/active/xw/xmloop.c

015b.	6/2/98		nprogs/nsat/source/dslw.c, gmpk.c, pxm.c

018jj.	6/4/98		NEW:gempak/source/gemlib/im/imqtim.f
	
			nprogs/nmap/source/nmap_data.h, nmap_dataw.c, nmap_dsp.c,
			nmap_image.c, nmap_mbotw.c

021a3f.	6/5/98		NEW:icons/nmap/testcloud.xbm, textfrzlvl.xbm, textgen.xbm,
			textturb.xbm

			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgobj.c, 
			nmap_pgpalw.c, nmap_pgtxt.c, nmap_pgvgf.c
			gempak/source/cgemlib/cds/cdstext.c
			gempak/source/Nxmlib/NxmTxtA.c
			gempak/tables/pgen/textbtn.tbl
			gempak/include/drwids.h
			include/NxmTxt.h

021a3g.	6/8/98		nprogs/nmap/source/vgf/nmap_pgolk.c, nmap_pgsfp.c

018kk.	6/8/98		nprogs/nmap/source/nmap_mapw.c
			gempak/source/nxmlib/NxmMarkA.c
			include/Nxm.h
			gempak/tables/nmap/mapovl.nmap

021a3h.	6/9/98		NEW:nprogs/nmap/source/vgf/nmap_pgactv.c, nmap_pgdel.c,
			nmap_pgedit.c, nmap_pggst.c, nmap_pgmdfy.c, nmap_pgmodv.c,
			nmap_pgmvcp.c, nmap_pgnew.c, nmap_pgpgdel.c, namp_pgrot.c,
			nmap_pgutls.c

021a3i.	6/9/98		gempak/source/testprog/atest.f, plotsyms.f
			gempak/source/cgemlib/cds/cdsfrnt.c
			gempak/source/appl/attribute/gqfrnt.f, gsfrnt.f
			gempak/source/gplt/access/ginit.f
			gempak/source/gplt/attribute/gqfrnt.f, gsattr.f, gsfrnt.f
			gempak/source/gplt/device/attribute/dsfrnt.f
			gempak/source/device/attribute/dsfrnt.f
			gempak/source/device/plot/dfrnt.f
			gempak/source/driver/active/gn/hsfrnt.f
			gempak/source/driver/active/vg/hsfrnt.f, vsfrnt.c
			gempak/include/devact.cmn, devreq.cmn, devset.cmn

021a3j. 6/9/98		nprogs/nmap/source/nmap_dataw.c, nmap_dslw.c, 
			nmap_dttmw.c, nmap_mapw.c, nmap_mbotw.c, nmap_roamw.c,
			nmap_stnmw.c, nmap_tmln.c, nmap_uairw.c
			nprogs/nmap/source/vgf/nmap_pgfrtw.c, nmap_pgprd.c,
			nmap_pgwlst.c, nmap_pgwndw.c
			gempak/source/cgemlib/cvg/testcvg.c
			gempak/source/cgemlib/cgr/testcgr.c

011p.	6/11/98		gempak/source/gemlib/gg/ggsplt.f
			gempak/help/gdcntr.hlp, gdmap.hlp, gdplot.hlp, gdplot2.hlp,
			gdstream.hlp, gdwind.hlp, gpmap.hlp, sfmap.hlp, snmap.hlp,
			stnplt.hl1, stnplt.hl2

021a3k.	6/11/98		nprogs/nmap/source/nmap_dsp.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pggrp.c,
			nmap_pgnew.c

021a3l.	6/11/98		gempak/source/nmxlib/NxmTxtA.c
			nprogs/nmap/source/nmap_mmenuw.c
			nprogs/nmap/source/vgf/nmap_pgedit.c, nmap_pgpalw.c,
			nmap_pgtxt.c
			gempak/tables/pgen/setting.tbl

021a3m.	6/11/98		NEW:icons/nmap/dsline9.xbm, dsline8.xbm, dsline7.xbm,
			dsline6.xbm, dsline5.xbm, dsline4.xbm, dsline3.xbm,
			dsline2.xbm

021a3n.	6/11/98		nprogs/nmap/source/vgf/nmap_pgobj.c, nmap_pgpalw.c
			gempak/include/drwids.h
			gempak/tables/pgen/setting.tbl, linebtn.tbl

006w.	6/11/98		NEW: (moved from the control areas) 
			gempak/source/appl/color/gsctbl.f
			gempak/source/color/gsctbl.f
			gempak/source/gplt/device/color/dsctbl.f
			gempak/source/device/color/dsctbl.f

			gempak/source/testprog/atest.f
			gempak/source/gplt/main/gplt.f
			gempak/source/device/main/device.f
			gempak/source/programs/gui/nafos/nafmenuw.c
			nprogs/nmap/source/nmap_zoomw.c
			nprogs/nsat/source/mmenuw.c
			nprogs/nwx/source/mapw.c
			gempak/source/gemlib/ip/ipgtpt.f
			gempak/source/appl/control/ggtpnt.f
			gempak/source/gplt/control/ggtpnt.f
			gempak/source/gplt/device/control/dgtnpt.f
			gempak/source/device/control/dgtpnt.f
			gempak/source/driver/active/gn/hgtpnt.f
			gempak/source/driver/active/xw/hgtpnt.f, xgtpnt.c
			gempak/source/driver/active/xwp/hgtpnt.f


			gempak/include/funccode.prm, uscore.h

018ll.	6/12/98		nprogs/nmap/source/nmap_mapw.c
			gempak/source/nxmlib/NxmMarkA.c

021a3o.	6/12/98		nprogs/nmap/source/vgf/nmap_pgnew.c

021a3p.	6/12/98		NEW:gempak/tables/nmap/outlook.tbl

			nprogs/nmap/source/vgf/nmap_pgolk.c

021a3q.	6/15/98		nprogs/nmap/source/vgf/nmap_pgdel.c, nmap_pgedit.c,
			nmap_pgevt.c, nmap_pghdlb.c, nmap_pgmvcp.c, nmap_pgnew.c,
			nmap_pgutls.c

021a3r.	6/15/98		NEW:nprogs/nmap/source/vgf/nmap_pgqpf.c

001gg.	6/15/98		gempak/source/bridge/dc/dcgpil.f (documentation only)

			gempak/source/bridge/mt/mtcmtn.f, mtgmsk.f
			gempak/source/bridge/sc/sccltp.f, sccmn.cmn, scdcod.f,
			scdecd.f, scifpt.f, scifsp.f, scwea3.f
			gempak/tables/pack/scd.pack

014e.	6/15/98		nprogs/ntrans/source/commands.c

021a3s.	6/15/98		icons/dsline8.xbm

008k.	6/15/98		gempak/source/appl/map/gsmprj.f
			gempak/source/gplt/map/gsmprj.f
			gempak/help/proj.hl2

018mm.	6/15/98		nprogs/nmap/source/nmap_mbotw.c
			resource/Nmap

021a3t.	6/15/98		gempak/source/device/draw/ipatln.f, itxsy.f

021a3u.	6/15/98		nprogs/nmap/source/vgf/nmap_pgprd.c, nmap_pgsfp.c

021a3v.	6/15/98		nprogs/nmap/source/vgf/nmap_pgolk.c

021a3w. 6/15/98		gempak/source/nxmlib/NxmTxtA.c

021a3x. 6/15/98		gempak/include/vgstruct.h

021a3y. 6/16/98		NEW:icons/nmap/qpf.xbm

			nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgprd.c
			gempak/include/drwids.h
			gempak/tables/pgen/prodbtn.tbl

021a3z.	6/16/98		nprogs/nmap/source/vgf/nmap_pgsfp.c

011q.	6/16/98		gempak/source/programs/oa/oabsfc/oabsfc.f
			gempak/source/programs/oa/oabsnd/oabsnd.f
			gempak/source/gemlib/oa/oabarn.f

018nn.	6/16/98		nprogs/nmap/source/nmap_sfmap.f, nmap_snmap.f

010xxx. 6/16/98		gempak/source/gemlib/fl/fltbop.f

010yyy.	6/16/98		NEW:gempak/source/cgemlib/cgr/cgrlindist.c

			gempak/source/cgemlib/cgr/testcgr.c

021a4a.	6/16/98		NEW:nprogs/nmap/source/vgf/nmap_pgwbx.c

			gempak/source/cgemlib/cds/cdswbox.c
			gempak/source/cgemlib/cvg/cvgwbsto.c, cvgsvwbx.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgmodv.c,
			nmap_pgnew.c, nmap_pgvgf.c,  nmap_pgwbxw.c,
			nmap_pgwlst.c

010zzz.	6/16/98		NEW:gempak/source/gemlib/tg/tgcrinc.f

			gempak/source/gemlib/tg/testtg.f
			gempak/include/underscr.h

018oo.	6/17/98		gempak/source/gemlib/gd/gdgcyc.f
			nprogs/nmap/source/nmap_dslw.c, nmap_mdl.c
			gempak/tables/nmap/dcatg.nmap
			gempak/tables/config/data.tbl

011r.	6/17/98		gempak/source/programs/gd/gdcross/gdxsdl.f

021a4b. 6/17/98		nprogs/nmap/source/vgf/nmap_pgfrtw.c
			gempak/source/cgemlib/cds/cdsfrnt.c
			gempak/source/cgemlib/ces/cesrtbl.c
			gempak/tables/pgen/setting.tbl

021a4c.	6/17/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgnew.c, 
			nmap_pgpalw.c

007ee.	6/17/98		gempak/source/device/access/dinit.f
			gempak/source/device/draw/ipatln.f
			gempak/include/devchr.cmn

008l.	6/17/98	        gempak/source/appl/access/gendp.f 
			gempak/source/appl/access/ginitp.f 
			gempak/source/appl/access/gqmode.f 
			gempak/source/appl/access/gsmode.f 

			gempak/source/appl/attribute/gqarrw.f 
			gempak/source/appl/attribute/gqbarb.f 
			gempak/source/appl/attribute/gqcntr.f 
			gempak/source/appl/attribute/gqctyp.f 
			gempak/source/appl/attribute/gqdarr.f 
			gempak/source/appl/attribute/gqdash.f 
			gempak/source/appl/attribute/gqfill.f 
			gempak/source/appl/attribute/gqfrnt.f 
			gempak/source/appl/attribute/gqhash.f 
			gempak/source/appl/attribute/gqicng.f 
			gempak/source/appl/attribute/gqline.f 
			gempak/source/appl/attribute/gqlpat.f 
			gempak/source/appl/attribute/gqmrkr.f 
			gempak/source/appl/attribute/gqptnd.f 
			gempak/source/appl/attribute/gqpwth.f 
			gempak/source/appl/attribute/gqsizd.f 
			gempak/source/appl/attribute/gqsky.f 
			gempak/source/appl/attribute/gqsmth.f 
			gempak/source/appl/attribute/gqspcl.f 
			gempak/source/appl/attribute/gqspln.f 
			gempak/source/appl/attribute/gqsysz.f 
			gempak/source/appl/attribute/gqtext.f 
			gempak/source/appl/attribute/gqturb.f 
			gempak/source/appl/attribute/gqwthr.f 
			gempak/source/appl/attribute/gsarrw.f 
			gempak/source/appl/attribute/gsbarb.f 
			gempak/source/appl/attribute/gscntr.f 
			gempak/source/appl/attribute/gsctyp.f 
			gempak/source/appl/attribute/gsdarr.f 
			gempak/source/appl/attribute/gsdash.f 
			gempak/source/appl/attribute/gsfill.f 
			gempak/source/appl/attribute/gsfrnt.f 
			gempak/source/appl/attribute/gshash.f 
			gempak/source/appl/attribute/gsicng.f 
			gempak/source/appl/attribute/gsline.f 
			gempak/source/appl/attribute/gslpat.f 
			gempak/source/appl/attribute/gsmrkr.f 
			gempak/source/appl/attribute/gsptnd.f 
			gempak/source/appl/attribute/gspwth.f 
			gempak/source/appl/attribute/gssky.f 
			gempak/source/appl/attribute/gssmth.f 
			gempak/source/appl/attribute/gsspcl.f 
			gempak/source/appl/attribute/gsspln.f 
			gempak/source/appl/attribute/gstext.f 
			gempak/source/appl/attribute/gstick.f 
			gempak/source/appl/attribute/gsturb.f 
			gempak/source/appl/attribute/gswthr.f 

			gempak/source/appl/bounds/gqbnd.f 
			gempak/source/appl/bounds/gsview.f 

			gempak/source/appl/color/gqclr2.f 
			gempak/source/appl/color/gqclrs.f 
			gempak/source/appl/color/gsbrgb.f 
			gempak/source/appl/color/gscint.f 
			gempak/source/appl/color/gsclr2.f 
			gempak/source/appl/color/gscnam.f 
			gempak/source/appl/color/gscolb.f 
			gempak/source/appl/color/gscolr.f 

			gempak/source/appl/contour/gcboxx.f 
			gempak/source/appl/contour/gcfill.f 
			gempak/source/appl/contour/gclgrn.f 

			gempak/source/appl/control/gclosp.f 
			gempak/source/appl/control/gclpnl.f 
			gempak/source/appl/control/gegrp.f 
			gempak/source/appl/control/geplot.f 
			gempak/source/appl/control/gloopc.f 
			gempak/source/appl/control/gmesg.f 
			gempak/source/appl/control/gqdev.f 
			gempak/source/appl/control/groam.f 
			gempak/source/appl/control/gsdeva.f 
			gempak/source/appl/control/gsgrp.f 
			gempak/source/appl/control/gslwin.f 
			gempak/source/appl/control/gsplot.f 
			gempak/source/appl/control/gsroam.f 

			gempak/source/appl/curve/gcurve.f 
			gempak/source/appl/curve/gcyevl.f 

			gempak/source/appl/graph/gaaxis.f 
			gempak/source/appl/graph/gdaxis.f 
			gempak/source/appl/graph/gqgraf.f 
			gempak/source/appl/graph/gsgmgn.f 
			gempak/source/appl/graph/gsgraf.f 

			gempak/source/appl/grid/gqggrf.f 
			gempak/source/appl/grid/gqgmap.f 
			gempak/source/appl/grid/gqgprj.f 
			gempak/source/appl/grid/gsggrf.f 
			gempak/source/appl/grid/gsgmap.f 
			gempak/source/appl/grid/gsgprj.f 

			gempak/source/appl/map/gqmmgn.f 
			gempak/source/appl/map/gsmmap.f 
			gempak/source/appl/map/gsmmgn.f 
			gempak/source/appl/map/gsmprj.f 

			gempak/source/appl/plot/garrw.f 
			gempak/source/appl/plot/gcircl.f 
			gempak/source/appl/plot/gdarr.f 
			gempak/source/appl/plot/gfill.f 
			gempak/source/appl/plot/gfrnt.f 
			gempak/source/appl/plot/ghash.f 
			gempak/source/appl/plot/gline.f 
			gempak/source/appl/plot/glogo.f 
			gempak/source/appl/plot/gtext.f 
			gempak/source/appl/plot/gtextc.f 
			gempak/source/appl/plot/gtxsy.f 

			gempak/source/appl/satellite/gqsatn.f 
			gempak/source/appl/satellite/gsatmg.f 

			gempak/source/appl/transform/gptvis.f 
			gempak/source/appl/transform/gtrans.f 

			gempak/source/appl/utility/gdrgrd.f 
			gempak/source/appl/utility/gdrmap.f 
			gempak/source/appl/utility/getmap.f 
			gempak/source/appl/utility/gqmfil.f 
			gempak/source/appl/utility/gsmfil.f 
			gempak/source/appl/utility/gstrml.f 


			gempak/txt/gemplt/AppxA.txt 
			gempak/txt/gemplt/AppxB.txt 
			gempak/txt/gemplt/Chap02.txt 
			gempak/txt/gemplt/Chap17.txt 
			gempak/txt/gemplt/Chap18.txt 
			gempak/txt/gemplt/attribute.txt 
			gempak/txt/gemplt/map.txt 
			gempak/txt/gemplt/utility.txt 

021a4d.	6/18/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgnew.c,
			nmap_pgrot.c
			gempak/source/nxmlib/NxmTxtA.c

018pp.	6/18/98		nprogs/nmap/source/nmap_mbotw.c, nmap_dsp.c

021a4e.	6/18/98		gempak/source/cgemlib/cvg/cvgcpy.c

021a4f. 6/18/98		nprogs/nmap/source/vgf/nmap_pgsymb.c

021a4g.	6/18/98		gempak/source/cgemlib/crg/crgsettxt.c

021a4h.	6/18/98		nprogs/nmap/source/nmap_zoomw.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgmdfy.c,
			nmap_pgnew.c

021a4i.	6/18/98		nprogs/nmap/source/vgf/nmap_pgfilw.c

021a4j.	6/18/98		NEW:gempak/source/cgemlib/cvg/cvg3i3h.c

			gempak/source/cgemlib/cvg/convcvg.c

021a4k.	6/22/98		nprogs/nmap/source/vgf/nmap_pgfrtw.c
			gempak/source/cgemlib/ces/testces.c

021a4l.	6/22/98		gempak/source/nxmlib/NxmTxtA.c

021a4m.	6/22/98		gempak/source/gemlib/cgemlib/cvg/cvgc3i3h.c

021a4n.	6/22/98		NEW:icons/box/box00.xbm, box01.xbm, box02.xbm,
			box03.xbm, box04.xbm, box05.xbm, box06.xbm

			gempak/source/nxmlib/NxmTxtA.c
			nprogs/nmap/source/vgf/nmap_pgfrtw.c

009c.	6/22/98		gempak/build/cgemlib_link

018qq.	6/23/98		nprogs/nmap/source/nmap_dataw.c, nmap_dslw.c, 
			nmap_stnmw.c

021a4o.	6/23/98		gempak/source/cgemlib/ces/testces.c

021a4p.	6/23/98		nprogs/nmap/source/nmap_zoomw.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgpalw.c

021a4q.	6/23/98		gempak/source/cgemlib/cds/cdssymb.c

021a4r.	6/23/98		gempak/source/programs/util/avnbul/bavsptx.c

021a4s.	6/23/98		gempak/include/drwids.h

021a4t.	6/23/98		gempak/source/cgemlib/cds/cdssymb.c

021a4u.	6/23/98		gempak/source/cgemlib/cvg/cvgrdele.c

021a4v.	6/23/98		nprogs/nmap/source/vgf/nmap_pgfilw.c

023a.	6/24/98		icons/box/box01.xbm, box02.xbm, box03.xbm,
			box04.xbm, box05.xbm, box06.xbm

021a4w.	6/24/98		gempak/source/cgemlib/cvg/convcvg.c, cvgc3i3h.c

021a4x.	6/24/98		nprogs/nmap/source/vgf/nmap_pgfilw.c

008m.	6/24/98		NEW:help/nmap/WhatsNew.hlp

			help/nmap/nmapHlp.index, ProdGen.hlp

021a4y.	6/24/98		nprogs/nmap/source/vgf/nmap_pgsfp.c

010a1a.	6/25/98		gempak/source/cgemlib/cds/cds.h, cdsinit.c

010a1b.	6/25/98		gempak/source/cgemlib/cds/cds.h, cdsinit.c,
			cdsgfill.c

021a4z.	6/25/98		gempak/source/cgemlib/cvg/cvgc3i3h.c

021a5a.	6/25/98		gempak/source/cgemlib/cvg/cvgc3i3h.c

=========================== Patch 5.4.3.i ==================================

021a5b. 7/6/98		NEW:gempak/source/cgemlib/crg/crggrfrsh.c

			nprogs/nmap/source/vgf/nmap_pgdel.c, nmap_pgevt.c,
			nmap_pghdlb.c, nmap_pgmvcp.c, nmap_pgundo.c,
			nmap_pgutls.c

021a5c.	7/6/98		nprogs/nmap/source/vgf/nmap_pgedit.c, nmap_pgevt.c,
			nmap_pgpalw.c

021a5d.	7/6/98		gempak/source/nxmlib/NxmTxtA.c

021a5e.	7/6/98		nprogs/nmap/source/vgf/nmap_pgline.c

010a1c.	7/6/98		gempak/source/gemlib/mr/mrpwnd.f

021a5f.	7/7/98		nprogs/nmap/source/vgf/nmap_pgwndw.c, nmap_pgwlst.c,
			nmap_pgundo.c, nmap_pgpdel.c, nmap_pgpalw.c, 
			nmap_pgnew.c, nmap_pgmvcp.c, nmap_pgmdfy.c,
			nmap_pgfilw.c, nmap_pgevt.c, nmap_pgedit.c
			nprogs/nmap/source/nmap_mbotw.c
			gempak/source/nxmlib/NxmConfirm.c

010a1d.	7/7/98		gempak/include/dgcmn.cmn

006x.	7/7/98		NEW:gempak/source/gplt/transform/grottl.f

			gempak/source/gplt/coord/updcyl.f
			gempak/source/gplt/transform/gitoq.f, gltow.f, gqtoi.f,
			gwtol.f
			gempak/include/xydef.cmn
			gempak/help/proj.hl2

006y.	7/7/98		gempak/source/gplt/coord/updcyl.f

006z.	7/9/98		gempak/source/device/curve/dprmtc.f
			gempak/source/device/plot/dfill.f, dline.f, dspln.f

021a5g.	7/9/98		gempak/source/cgemlib/cgr/cgrsegdist.c

021a5h.	7/9/98		gempak/source/cgemlib/ces/testces.c
			gempak/source/cgemlib/cvg/testcvg.c
			gempak/tables/pgen/setting.tbl

001hh.	7/9/98		gempak/source/bridge/mt/mtvisb.f

021a5i.	7/13/98		nprogs/nmap/source/nmap_mbotw.c
			resource/Nmap

011s.	7/14/98		gempak/source/programs/gd/gdplot2/gdpltb.f, gdpskp.f

021a5j.	7/14/98		nprogs/nmap/source/vgf/nmap_pgdel.c, nmap_pgpalw.c

021a5k.	7/14/98		nprogs/nmap/source/vgf/nmap_pgolk.c

021a5l.	7/15/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgmodv.c,
			nmap_pgmvcp.c

021a5m.	7/15/98		gempak/include/cescmn.h
			gempak/source/cgemlib/ces/cesset.c, cesget.c,
			cesrtbl.c, testces.c
			gempak/source/nxmlib/NxmTxtA.c

011t.	7/16/98		gempak/include/devchr.cmn, gemprm.*

010a1e.	7/16/98		NEW:gempak/source/gemlib/df/dfmask.f
			gempak/source/gemlib/dg/dglncr.f, dglncx.f
			gempak/source/gemlib/dv/dvvmsk.f
			gempak/tables/grid/landsea.tbl

			gempak/source/gemlib/dg/dgchck.f, dgdriv.f,
			dginit.f
			gempak/help/gparm.hl2
			gempak/txt/apx/gparm.apx

018rr.	7/16/98		nprogs/nmap/source/nmap_dataw.c, nmap_domt.c, nmap_image.c

011u.	7/20/98		gempak/include/devchr.cmn, gemprm.*

008n.	7/21/98		gempak/help/proj.hl2

021a5n.	7/22/98		nprogs/nmap/source/vgf/nmap_pgfrtw.c, nmap_pgedit.c,
			nmap_pgvgf.c

006aa.	7/22/98		NEW:gempak/source/appl/attribute/gqcvsc.f
			gempak/source/gplt/attribute/gqcvsc.f

			gempak/source/gplt/main/gplt.f
			gempak/source/testprog/atest.f
			gempak/include/funccode.prm

023b.	7/23/98		NEW:icons/nmap/pwtstorm.xbm

			gempak/utilities/xbm/nmapxbms.csh

001ii.	7/23/98		gempak/source/bridge/dc/dcwthr.f
			gempak/source/gemlib/pt/ptwnmt.f
			gempak/source/gemlib/pc/pccmst.f, pcdfst.f
			gempak/help/sfparm.hl2
			gempak/tables/nmap/acft_parms.tbl
			gempak/txt/apx/parms.apx

021a5o.	7/24/98		NEW:gempak/source/cgemlib/crg/crggettxtbox.c

			gempak/source/cgemlib/crg/crgsettxt.c
			gempak/source/nxmlib/NxmTxtA.c
			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pggst.c,
			nmap_pghdlb.c, nmap_pgmvcp.c, nmap_pgpalw.c, 
			nmap_pgrot.c

007ff.	7/27/98		NEW:gempak/source/gemlib/tb/tbfont.f
			gempak/source/driver/active/vg/htxsy.f
			gempak/source/driver/active/vg/htextc.f
			gempak/source/driver/active/ps/ptextc.c
			gempak/source/driver/active/utf/htextc.f
			gempak/tables/config/fontsz.tbl

			(* indicates calling sequence change)

			gempak/source/testprog/atest.f
			gempak/source/appl/plot/gtextc.f*
			gempak/source/gplt/main/gplt.f
			gempak/source/gplt/attribute/gstext.f
			gempak/source/gplt/plot/gtext.f
			gempak/source/gplt/plot/gtxsy.f
			gempak/source/gplt/plot/gtextc.f*
			gempak/source/gplt/device/plot/dtextc.f
			gempak/source/device/main/device.f
			gempak/source/device/attribute/dstext.f
			gempak/source/device/draw/iptnd.f
			gempak/source/device/draw/isky.f
			gempak/source/device/draw/isymb.f
			gempak/source/device/draw/itxsy.f
			gempak/source/device/draw/itxbox.f
			gempak/source/device/plot/dtextc.f*
			gempak/source/device/plot/dtxsy.f
			gempak/source/device/plot/dtext.f
			gempak/source/device/plot/dlogo.f
			gempak/source/device/plot/dptnd.f
			gempak/source/gemlib/gg/ggwstr.f
			gempak/source/gemlib/in/intxtn.f
			gempak/source/gemlib/tb/testtb.f
			gempak/source/cgemlib/cds/cdstext.c
			gempak/source/cgemlib/utf/utfptext.c
			gempak/source/driver/active/vg/vtxsy.c
			gempak/source/driver/active/vg/hstext.f*
			gempak/source/driver/active/gn/htext.f
			gempak/source/driver/active/gn/hstext.f*
			gempak/source/driver/active/gn/htextc.f*
			gempak/source/driver/active/gn/htxsy.f*
			gempak/source/driver/active/nc/htext.f
			gempak/source/driver/active/nc/mtext.c*
			gempak/source/driver/active/nc/htextc.f*
			gempak/source/driver/active/nc/hinit.f
			gempak/source/driver/active/nc/mtextc.c*
			gempak/source/driver/active/nc/minita.c
			gempak/source/driver/active/nc/nccmn.h
			gempak/source/driver/active/nc/mstext.c*
			gempak/source/driver/active/nc/hstext.f*
			gempak/source/driver/active/ps/ptext.c
			gempak/source/driver/active/ps/htextc.f*
			gempak/source/driver/active/ps/hinit.f
			gempak/source/driver/active/ps/pinita.c
			gempak/source/driver/active/ps/hstext.f*
			gempak/source/driver/active/ps/pstext.c*
			gempak/source/driver/active/utf/utext.c	
			gempak/source/driver/active/utf/hinit.f
			gempak/source/driver/active/utf/ustext.c*
			gempak/source/driver/active/utf/hstext.f*
			gempak/source/driver/active/utf/uinita.c*
			gempak/source/driver/active/utf/usymb.c
			gempak/source/driver/active/xw/htext.f
			gempak/source/driver/active/xw/xtext.c*
			gempak/source/driver/active/xw/xinita.c
			gempak/source/driver/active/xw/htextc.f*
			gempak/source/driver/active/xw/hinit.f
			gempak/source/driver/active/xw/hinita.f
			gempak/source/driver/active/xw/xstext.c*
			gempak/source/driver/active/xw/hstext.f*
			gempak/source/driver/active/xw/xtextc.c*
			gempak/source/driver/active/xwp/htext.f
			gempak/source/driver/active/xwp/htextc.f*
			gempak/source/driver/active/xwp/hinitxw.f
			gempak/source/driver/active/xwp/hinitps.f
			gempak/source/driver/active/xwp/hstext.f*
			gempak/source/driver/active/xwp/hinita.f
			nprogs/ntrans/source/process_meta.c
			nprogs/ntrans/source/ntrans.c
			gempak/include/uscore.h
			gempak/include/xwcmn.h
			gempak/include/devchr.cmn
			

			gempak/error/tb.err

			gempak/help/text.hl2

006bb.	7/28/98		NEW:gempak/source/gemlib/cv/cvprmt.f
			gempak/error/cv.err

			gempak/source/device/plot/dfill.f, dline.f, dspln.f
			gempak/build/gemlib_compile

021a5p.	7/29/98		nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgobj.c
			gempak/tables/pgen/symbolbtn.tbl
			gempak/include/drwids.h

006cc.	7/29/98		gempak/source/driver/active/utf/usymb.c
			gempak/source/testprog/plotsyms.f
			gempak/source/device/draw/ispcl.f

006dd.	7/29/98		gempak/include/undscr.h

007gg.	7/29/98		gempak/source/driver/active/xw/xtextc.c
			nprogs/ntrans/source/commands.c

007hh.	7/30/98		gempak/source/driver/active/xw/xstext.c

021a5q.	8/4/98		nprogs/nmap/source/vgf/nmap_pgsymb.c

008o.	8/4/98		gempak/source/gemlib/tb/tbfront.f

010a1f.	8/5/98		gempak/source/gemlib/fl/flmfls.f

010a1g.	8/5/98		NEW:gempak/source/gemlib/tg/tgqrng.f

			gempak/source/gemlib/tg/testtg.f

016b.	8/6/98		NEW:nprogs/nwx/source/wbox.c, wwctim.f, wwdcod.f,
			wwrtim.f, wwus9.f

			nprogs/nwx/source/gui.h, draw.c, dslw.c, fosd.c,
			mapw.c, nwx.c, txtw.c
			gempak/include/undscr.h
			tables/nwx/guidata.tbl, master.tbl

018ss.	8/6/98		NEW:gempak/source/cgemlib/ctb/ctbfszrd.c, ctbfszqn.c, 
			ctbfszval.c, ctbfszxvl.c, ctbfsznam.c,
			ctbfszfnt.c

			nprogs/nmap/source/nmap.c, nmap_mapw.c, nmap_stnmw.c
			gempak/source/nxmlib/NxmMarkA.c, NxmTxtA.c
			gempak/source/cgemlib/ctb/testctb.c
			gempak/source/gemlib/tb/tbfont.f
			include/Nxm.h, NxmTxt.h
			gempak/include/ctbcmn.h
			gempak/tables/nmap/mapovl.nmap
			gempak/tables/config/fontsz.tbl

021a5r.	8/6/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pggst.c,
			nmap_pgmdfy.c, nmap_modv.c, nmap_pgmvcp.c,
			nmap_pgnew.c, nmap_pgpalw.c, nmap_pgpdel.c,
			nmap_pgrot.c, nmap_pgutls.c
			gempak/include/vgstruct.h

021a5s.	8/6/98		nprogs/nmap/source/vgf/nmap_pgvgf.c

021a5t.	8/7/98		nprogs/nmap/source/vgf/nmap_pgtxt.c

021a5u.	8/10/98		NEW:nprogs/nmap/source/vgf/nmap_pgtrk.c
			icons/nmap/hcntrak.xbm

			nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgprd.c
			gempak/include/drwids.h
			gempak/tables/pgen/prodbtn.tbl

021a5v. 8/10/98		nprogs/nmap/source/nmap_dslw.c, nmap_mmenuw.c,
			nmap_stnmw.c
			gempak/source/nxmlib/NxmTxtA.c

021a5w.	8/11/98		nprogs/nmap/source/vgf/nmap_pgolk.c

021a5x.	8/11/98		NEW:nprogs/nmap/source/vgf/nmap_pgggc.c
			icons/nmap/ggcntr.xbm

			nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgprd.c
			gempak/include/drwids.h
			gempak/tables/pgen/prodbtn.tbl

018tt.	8/11/98		NEW:gempak/source/gemlib/gd/gdfltm.f

			gempak/source/gemlib/gd/gdcyc.f, gdgtmf.f*,
			testgd.f
			gempak/source/gemlib/gr/grtmfl.f*, testgr.f
			gempak/source/programs/gd/gdplot2/gdplot.f,
			gdptmc.f*, gdptms.f, testgdp.f
			gempak/tables/config/data.tbl
			gempak/nts/nmap/restore/modl/rucs/pmsl_and_dewpoint_al,
			pmsl_and_sfc_temp_al, sfc_moist_conv_al
			nprogs/nmap/source/nmap_dataw.c, nmap_mbotw.c,
			nmap_mdl.c

			(* indicates calling sequence change)

021a5y.	8/11/98		nprogs/nmap/source/vgf/nmap_pgpalw.c

007ii.	8/13/98		gempak/source/driver/active/ps/pinita.c, 
			psopen.c

021a5z.	8/24/98		nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgevt.c,
			nmap_pgmvcp.c

021a6a.	8/24/98		nprogs/nmap/source/vgf/nmap_pgnew.c

007jj.	8/25/98		gempak/source/device/plot/dpwth.f, dctyp.f

021a6b.	8/25/98		NEW:icons/nmap/trpdprsn.xbm, trpcycln.xbm, 
			stmcntr.xbm

			nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pbobj.c
			gempak/source/driver/active/utf/usymb.c
			gempak/source/testprog/plotsyms.f
			gempak/source/device/draw/ispcl.f
			gempak/tables/pgen/symbolbtn.tbl
			gempak/include/drwids.h

007kk.	8/25/98		gempak/source/device/draw/ibarb.f, iarrw.f
			gempak/source/device/plot/dbarb.f, darrw.f

			gempak/help/wind.hl2, sfparm.hl2, snparm.hl2

014f.	8/27/98		nprogs/ntrans/source/ntrans.c, legend.c, Makefile
			nprogs/ntrans/include/interface.h
			

021a6c.	8/27/98		nprogs/nmap/source/vgf/nmap_pgpalw.c,
			nmap_pgevt.c

010a1h.	8/27/98		NEW:gempak/source/gemlib/fl/flffil.f, flscnd.f
			gempak/source/gemlib/st/stclsl.f

			gempak/source/gemlib/fl/testfl.f
			gempak/source/gemlib/st/testst.f
			gempak/source/programs/gd/gdcntr/gdcntr.f,
			gdndsp.f, gdcntr_link
			gempak/error/fl.err
			gempak/help/gdfile.hl2, sffile.hl2

007ll.	8/27/98		gempak/source/device/draw/itxsy.f

010a1i.	8/27/98		gempak/source/cgemlib/ctb/ctbastn.c

021a6d.	8/27/98		nprogs/nmap/source/vgf/nmap_pgpalw.c, 
			nmap_pgnew.c

021a6e.	8/27/98		icons/nmap/spln20.xbm, spln21.xbm021

010a1j.	8/27/98		gempak/source/gemlib/gd/testgd.f

010a1k.	8/27/98		NEW:gempak/source/gemlib/cv/testcv.f, testcv_link
		
			gempak/build/gemlib_link

006ee.	8/27/98		gempak/source/gplt/transform/mcidas/nvxgvar.f
			gempak/tables/sat/imgtyp.tbl

006ff.	8/28/98		gempak/source/testprog/plotsyms.f
			gempak/tables/draw/splpat.tbl

018uu.	8/28/98		NEW:nprogs/nmap/source/nmap_obs.c, smgtim.f
			gempak/source/cgemlib/cst/csttims.c

			nprogs/nmap/source/nmap_tmln.c, nmapprm.h,
			nmap_dataw.c, nmap_domt.c, nmap_dsp.c,
			nmap_image.c, nmap_mdl.c
			nprogs/nmap/source/vgf/nmap_pgpalw.c

021a6f.	9/1/98		nprogs/nmap/source/vgf/nmap_pggc.c

021a6g.	9/2/98		NEW:nprogs/nmap/source/vgf/nmap_pgdelpt.c
			icons/nmap/delpoint.xbm

			nprogs/nmap/source/vgf/nmap_pgactv.c, 
			nmap_pgevt.c, nmap_pgpalw.c
			gempak/include/drwids.h
			gempak/tables/pgen/funcbtn.tbl

021a6h.	9/2/98		nprogs/nmap/source/vgf/nmap_pgpalw.c,
			nmap_pggrpw.c, nmap_pgevt.c, 
			nmap_pgvgf.c
			gempak/include/pgprm.h

006gg.	9/2/98		gempak/source/device/draw/ipatln.f

011v.	9/3/98		NEW:gempak/source/programs/gd/grphgd/gciijj.f,
			ggapsm.f, gggint.f, ggrads.f, ggrdln.f, gindex.f,
			gindx1.f, glastv.f, gnextv.f, gradls.f, grginp.f,
			gsmoot.f, gsortd.f, gweigs.f, lnsgin.f, grphgd.f
			grphgd.cmn, grphgd_link
			gempak/help/cntrfl1.hl1, cntrfl.hl2
			gempak/parm/grphgd.prm
			gempak/txt/programs/grphgd.txt
			gempak/error/grphgd.err

			gempak/pdf/gemglb.pdf
			gempak/build/gd_compile, gd_link

006hh.	9/3/98		gempak/source/gemlib/cv/cvprmt.f*, testcv.f
			gempak/source/device/plot/dfill.f, dline.f,
			dspln.f

			(* indicates calling sequence modified)

021a6i.	9/3/98		nprogs/nmap/source/vgf/nmap_pggst.c, 
			nmap_pgmdfy.c, nmap_pgmodv.c, nmap_pgmvcp.c,
			nmap_pgnew.c, nmap_pgdel.c, nmap_pgutls.c
			gempak/include/pgprm.h

010a1l.	9/3/98		NEW:gempak/source/gemlib/st/statoe.f
			gempak/source/gemlib/st/AIX/statoe.f

			gempak/source/gemlib/st/testst.f
			gempak/source/gemlib/AIX/testst.f

010a1m.	9/3/98		gempak/source/cgemlib/cst/testcst.c

021a6j.	9/8/98		NEW:nprogs/nmap/source/vgf/nmap_pgxrain.c
			icons/nmap/xrainf.xbm
			gempak/tables/stns/xrainsort.tbl

			nprogs/nmap/source/vgf/nmap_pgpalw.c, 
			nmap_pgobj.c, nmap_pgprd.c
			gempak/source/cgemlib/clo/cloancin.c, 
			cloancrd.c, cloinit.c, clotclss.t, 
			clotgid.c, clotgltln.c
			gempak/include/drwids.h, clocmn.h
			gempak/tables/pgen/prodbtn.tbl, linebtn.tbl,
			setting.tbl

021a6k.	9/8/98		nprogs/nmap/source/vgf/nmap_pgpdel.c

021a6l.	9/8/98		nprogs/nmap/source/vgf/nmap_pgevt.c, 
			nmap_pggrpw.c, nmap_pgundo.c

010a1n.	9/8/98		gempak/source/gemlib/ps/pscape.f

010a1o.	9/8/98		gempak/source/cgemlib/ces/testces.c
			gempak/source/cgemlib/cvg/dumpvgf.c

021a6m.	9/9/98		gempak/source/nxmlib/NxmTxtA.c
			gempak/source/cgemlib/crg/crggettxtbox.c
			nprogs/nmap/source/vgf/nmap_pgrot.c
			gempak/include/undscr.h
			icons/turb/turb00.xbm - turb08.xbm, turb46.xbm,
			turb67.xbm
			icons/box/box00.xbm - box06.xbm

021a6n.	9/9/98		NEW:nprogs/nmap/source/vgf/nmap_pgconn.c
			icons/nmap/connect.xbm

			nprogs/nmap/source/vgf/nmap_pgactv.c, 
			nmap_pgevt.c, nmap_pgpalw.c, nmap_pgutls.c
			gempak/include/drwids.h
			gempak/tables/pgen/funcbtn.tbl

001jj.	9/10/98		NEW:gempak/source/bridge/mm/mmtitl.f
			gempak/error/mm.err

			gempak/source/bridge/mm/mm3chr.f, mmdecc.f, 
			mmdecd.f, mmfctm.f, mmglic.f, mmglin.f, 
			mmgrpt.f
			gempak/help/sfparm.hl2
			gempak/tables/pack/mrfmos.pack
			gempak/txt/apx/parms.apx

021a6o.	9/10/98		nprogs/nmap/source/nmap_mbotw.c
			nprogs/nmap/source/vgf/nmap_pgedit.c,
			nmap_pgpalw.c

021a6p.	9/10/98		nprogs/nmap/source/vgf/nmap_pgpalw.c,
			nmap_pggrpw.c, nmap_pgevt.c

006ii.	9/10/98		gempak/source/device/draw/itxsy.f
			gempak/source/gplt/plot/gtxsy.f

010a1p.	9/11/98		gempak/source/gemlib/fl/flffil.f
			gempak/source/gemlib/st/stclsl.f

006jj.	9/11/98		gempak/source/device/draw/ipatln.f

006kk.	9/11/98		gempak/source/gplt/plot/gtxsy.f

021a6q.	9/14/98		nprogs/nmap/source/vgf/nmap_pgconn.c, 
			nmap_pgmodv.c, nmap_pgrot.c, nmap_pgnew.c,
			nmap_pgmvcp.c, nmap_pgmdfy.c, nmap_pggst.c,
			nmap_pgevt.c
			nprogs/nmap/source/nmap_mcanvw.c

021a6r.	9/14/98		NEW:icons/nmap/ungrpall.xbm

			nprogs/nmap/source/vgf/nmap_pghdlb.c,
			nmap_pgpalw.c
			gempak/include/drwids.h
			gempak/tables/pgen/funcbtn.tbl

010a1q.	9/14/98		NEW:gempak/source/gemlib/ti/tiitoj.f

			gempak/source/gemlib/ti/testti.f, tiaddd.f,
			tiaddm.f, tictoi.f, tidaym.f, tidayw.f, 
			tidifd.f, tisubm.f, tiitoc.f, tijtoi.f, 
			timdif.f, tisubd.f

010a1r.	9/14/98		gempak/source/gemib/cv/cvprmt.f

010a1s. 9/14/98		gempak/source/gemlib/st/testst.f, statoe.f
			gempak/source/gemlib/st/AIX/testst.f,
			statoe.f

001kk.	9/14/98		gempak/source/bridge/dc/dcwthr.f

010a1t.	9/14/98		gempak/source/gemlib/gb/gbbds.c, gbgmtx.c
			gbgpbd.c, gbgsec.c, gbgspk.c, gbgubd.c,
			gbscpk.c, gbsspk.c, gbunpk.c
			gempak/source/driver/active/xw/xsatim.c,
			xqclrs.c
			gempak/source/driver/active/ps/pqclrs.c
			gempak/source/nxmlib/NuiColorInit.c

021a6s.	9/14/98		nprogs/nmap/source/vgf/nmap_pgpalw.c,
			nmap_pgfrtw.c, nmap_pgline.c, nmap_pgvgf.c

			gempak/source/cgemlib/ces/cesrtbl.c, 
			cesget.c, cesset.c, testces.c
			gempak/include/cescmn.h
			gempak/tables/pgen/setting.tbl

021a6t.	9/15/98		nprogs/nmap/source/vgf/nmap_pgnew.c

021a6u. 9/15/98		nprogs/nmap/source/vgf/nmap_pgwndw.c, 
			nmap_pgedit.c, nmap_pgrot.c

010a1u.	9/15/98		gempak/source/gemlib/ti/tidayw.f, tiaddm.f,
			tisubm.f

021a6v.	9/15/98		nprogs/nmap/source/vgf/nmap_pgpalw.c

021a6w.	9/15/98		gempak/source/nxmlib/NxmTxtA.c

010a1v.	9/15/98		gempak/source/gemlib/ti/testti.f

018vv.	9/17/98		nprogs/nmap/source/nmap_dataw.c, nmap_tmln.c

010a1w.	9/17/98		gempak/source/gemlib/cv/cvprmt.f

001ll.	9/17/98		gempak/source/bridge/ra/rartim.f
			gempak/source/bridge/ff/ffrtim.f
			gempak/source/bridge/rs/rsrtim.f

021a6x. 9/17/98		nprogs/nmap/source/vgf/nmap_pgwndw.c

021a6y.	9/17/98		nprogs/nmap/source/vgf/nmap_pgdel.c,
			nmap_pgedit.c, nmap_pgevt.c, nmap_pgfilw.c,
			nmap_pghdlb.c, nmap_pgmvcp.c, nmap_pgpalw.c,
			nmap_pgundo.c
			gempak/include/pgprm.h

010a1x.	9/22/98		NEW:gempak/source/bridge/ww/wwctim.f, wwdcod.f,
			wwrtim.f, wwus9.f
			gempak/source/gemlib/gg/ggwtch.f

			gempak/source/gemlib/fl/fltmpl.f, flmfls.f,
			flmfil.f, flffil.f, testfl.f
			gempak/source/cgemlib/ctb/ctbdtdump.c, 
			testctb.c
			gempak/tables/config/data.tbl
			gempak/include/ctbcmn.h
			gempak/build/bridge_compile

010a1y.	9/22/98		gempak/source/gemlib/fl/flmfls.f

011w.	9/22/98		NEW:gempak/source/gemlib/aw/*
			gempak/source/programs/gp/gpmap/gpmaws.f
			gempak/help/awpsfl.hl1, awpsfl.hl2

			gempak/source/programs/gp/gpmap.f, gpminp.f,
			gpmap_link
			gempak/parm/gpmap.prm
			gempak/pdf/gemglb.pdf
			gempak/txt/programs/gpmap.txt
			gempak/tables/stns/geog.tbl
			gempak/build/gemlib_compile

021a6z.	9/22/98		nprogs/nmap/source/vgf/nmap_pgactv.c, 
			nmap_pgconn.c

021a7a.	9/22/98		nprogs/nmap/source/vgf/nmap_pgconn.c, 
			nmap_pgevt.c, nmap_pgmdfy.c, nmap_pgpalw.c

007mm.	9/22/98		gempak/source/driver/active/ps/pinita.c,
			psdatt.c, psopen.c
			gempak/source/driver/active/xwp/hscolr.f

006ll.	9/22/98		gempak/source/device/plot/ddarr.f

010a1z.	9/22/98		gempak/source/gemlib/tg/tgfind.f

021a7b.	9/22/98		nprogs/nmap/source/vgf/nmap_pgtrk.c

021a7c.	9/22/98		nprogs/nmap/source/vgf/nmap_pgggc.c
			gempak/source/programs/gd/grphgd/ggapsm.f,
			gggint.f, ggrads.f, grginp.f, grphgd.f,
			grphgd_link
			gempak/parm/grphgd.prm
			gempak/utilities/pdfbld/gd_pdfbld

010a2a.	9/23/98		gempak/source/gemlib/gd/gdgtim.f, testgd.f,
			gdfltm.f, gdgcyc.f, gdgtmf.f
			gempak/source/gemlib/in/intype/f, testin.f
			gempak/source/gemlib/gr/grtmfl.f
			gempak/source/programs/gd/gdplot2/gdptmc.f,
			gdptms.f

021a7d.	9/23/98		NEW:gempak/source/programs/util/sfcsplt.c, sfcsplt_link

			gempak/build/util_link
			gempak/tables/pgen/grptyp.tbl

021a7e.	9/23/98		nprogs/nmap/source/vgf/nmap_pgpalw.c

008p.	9/23/98		gempak/help/awpsfl.hl1

018ww. 	9/23/98		nprogs/nmap/source/nmap_tmln.c

021a7f. 9/23/98		nprogs/nmap/source/vgf/nmap_pgevt.c, 
			nmap_pgwbx.c, nmap_pgwbxw.c
			gempak/include/vgstruct.h

007nn.	9/23/98		NEW:gempak/source/driver/active/rbk/*
			gempak/source/cgemlib/ctb/ctbawdef.c, 
			ctbawmap.c
			gempak/tables/pgen/awdef.tbl, awsiz.tbl

			gempak/source/cgemlib/ctb/testctb.c
			gempak/source/device/draw/iarrw.f, idraw.f,
			ipatln.f
			gempak/source/device/plot/dctyp.f, dicng.f,
			dlogo.f, dptnd.f, dpwth.f, dsky.f, dspcl.f,
			dturb.f, dwthr.f
			gempak/source/gemlib/gg/ggsdev.f
			gempak/source/gplt/plot/glogo.f
			gempak/source/gplt/utility/gdrgrd.f, 
			gdrmap.f
			gempak/build/driver_compile, driver_link
			gempak/help/device.hl2
			gempak/include/uscore.h

021a7g.	9/24/98 	nprogs/nmap/source/vgf/nmap_pgfilw.c

010a2b.	9/24/98		gempak/source/gemlib/gr/grtlst.f

021a7h.	9/24/98		nprogs/nmap/source/vgf/nmap_pgpalw.c, 
			nmap_pgnew.c, nmap_pgevt.c

002e.	9/24/98		NEW:gempak/source/programs/na/nagrib/nagcut.f

			gempak/source/programs/na/nagrib/nagrib.f
			gempak/source/gemlib/gb/gbgds.f

021a7i.	9/24/98		nprogs/nmap/source/vgf/nmap_pggrpw.c,
			nmap_pgpalw.c, nmap_pgutls.c

021a7j.	9/24/98		nprogs/nmap/source/vgf/nmap_pgwbxw.c

021a7k.	9/24/98		gempak/source/programs/gd/grphgd/grphgd.f,
			grginp.f, grphgd.cmn
			gempak/txt/programs/grphgd.txt
			gempak/parm/programs/grphgd.parm

006mm.	9/24/98		gempak/source/gplt/contour/gclgrn.f


007oo.	9/25/98		gempak/source/driver/active/rbk/ardcmn.h,
			aline.c, aopen.c
			gempak/source/gemlib/aw/awread.f, awpmap.f
			gempak/tables/pgen/awsiz.tbl
			gempak/tables/stns/geog.tbl

018xx.	9/25/98		nprogs/nmap/source/nmap_tmln.c, nmap_dataw.c

007pp.	9/25/98		gempak/source/driver/active/rbk/ainita.c,
			asdatt.c

021a7l.	9/28/98		nprogs/nmap/source/vgf/nmap_pgxrain.c

011x.	9/29/98		gempak/source/gemlib/gg/ggwtch.f

011y.	9/30/98		gempak/source/gemlib/gg/ggwtch.f

001mm.	9/30/98		gempak/source/bridge/ww/wwrtim.f
			nprogs/nwx/source/wwrtim.f

008q.	9/30/98		help/nmap/ProdGen.hlp, WhatsNew.hlp

=========================== Patch 5.4.3.j ==================================

010a2c.	10/5/98		gempak/source/gemlib/ss/ssvers.f

001nn.	10/5/98		gempak/source/bridge/sc/scdcod.f, sccmn.cmn

021a7m.	10/5/98		nprogs/nmap/source/vgf/nmap_pggst.c
			gempak/source/cgemlib/crg/crggettxtbox.c

021a7n.	10/6/98		nprogs/nmap/source/vgf/nmap_pggrpw.c, 
			nmap_pgevt.c

021a7o.	10/6/98		nprogs/nmap/source/vgf/nmap_pgfrtw.c, 
			nmap_pgline.c, nmap_pgsymb.c, nmap_pgwndw.c,
			nmap_pgvgf.c
			gempak/source/nxmlib/NxmClrW.c

021a7p.	10/6/98		nprogs/nmap/source/vgf/nmap_pgrot.c
			gempak/source/nxmlib/NxmTxtA.c

021a7q.	10/7/98		nprogs/nmap/source/nmap_dsp.c, nmap_mmenuw.c,
			nprogs/nmap/source/vgf/nmap_pgfilw.c, nmap_pgpalw.c,
			nmap_pgundo.c

021a7r.	10/8/98		nprogs/nmap/source/vgf/nmap_pgedit.c

021a7s.	10/13/98	nprogs/nmap/source/vgf/nmap_pgdel.c,
			nmap_pgevt.c, nmap_pgpalw.c

010a2d.	10/16/98	gempak/source/gemlib/ti/tidifd.f, testti.f

010a2e.	10/16/98	gempak/source/gemlib/sf/sfwspc.f
			gempak/source/programs/sf/sflist/sflprt.f
			nprogs/nwx/source/srcho.c

001oo.	10/16/98 	NEW:gempak/source/bridge/ua/uadcod.f, uagemp.f,
			uagmst.f
			gempak/source/bridge/af/afcmn.cmn, afdcod.f,
			afifpt.f, afifsp.f, afint.f
			gempak/source/bridge/ls/lscmn.cmn, lsdcod.f,
			lsifpt.f, lsifsp.f, lsintf.f
			gempak/source/bridge/ma/macmn.cmn, madcod.f,
			maifpt.f, maifsp.f, maintf.f
			gempak/source/bridge/mt/mtcmn.cmn, mtdcod.f,
			mtifpt.f, mtifsp.f, mtintf.f
			gempak/source/bridge/sc/sccmn.cmn, scdcod.f,
			scifpt.f, scifsp.f, scintf.f
			gempak/source/bridge/ua/uacmn.cmn, uaifpt.f,
			uaifpsp.f

001pp.	10/16/98.	gempak/source/bridge/mm/mmglin.f
			gempak/source/programs/dc/dcmmos/dcmmdc.f

021a7t.	10/19/98	gempak/source/nxmlib/NxmTxtA.c

01qq.	10/19/98	NEW:gempak/source/bridge/av/avtitl.f
			gempak/error/av.err

			gempak/source/bridge/av/av3chr.f, avdecc.f,
			avdecd.f, avfctm.f, avglic.f, avglin.f,
			avgrpt.f, avtitl.f
			gempak/tables/pack/avnmos.pack

021a7u.	10/19/98	gempak/source/cgemlib/crg/crggettxtbox.c

021a7v.	10/19/98	gempak/include/vgstruct.h

021a7w.	10/21/98	nprogs/nmap/source/vgf/nmap_pgfrtw.c,
			nmap_pgline.c

021a7x.	10/21/98	gempak/source/cgemlib/crg/crggettxtbox.c

021a7y.	10/22/98	nprogs/nmap/source/vgf/nmap_pggst.c

010a2f.	10/22/98	NEW:gempak/source/gemlib/gp/gpazdr.f, 
			gpdraz.f

			gempak/source/cgemlib/crg/crggettxtbox.c
			gempak/include/undscr.h
			gempak/build/gemlib_compile

021a7z.	10/26/98	nprogs/nmap/source/nmap_dataw.c
			nprogs/nmap/source/vgf/nmap_pgpalw.c

021a8a.	10/26/98	gempak/source/cgemlib/cvg/cvgload.c, cvgrdrec.c*,
			cvgrdsel.c, cvgfndhl.c
			nprogs/nmap/source/vgf/nmap_pgedit.c, 
			nmap_pgevt.c, nmap_pgggc.c, nmap_pggrpw.c,
			nmap_pghdlb.c, nmap_pgmdfy.c, nmap_pgnew.c,
			nmap_pgolk.c

			(* indicates calling sequence change )

001rr.	10/26/98	gempak/source/bridge/mt/mtdcod.f

006nn.	10/26/98	gempak/source/gplt/plot/garrw.f, gbarb.f,
			gtext.f, gtextc.f, gtxsy.f, gdarr.f, 
			ghash.f
			nprogs/nmap/source/vgf/nmap_pgrot.c
			gempak/include/undscr.h

			gempak/source/gemlib/gp/gpdraz.f, gpazdr.f 
			(documentation only)

006oo.	10/28/98	NEW:gempak/source/appl/plot/gcmbo.f
			gempak/source/appl/attribute/gcmbo.f, gscmbo.f
			gempak/source/device/plot/cmbo.f
			gempak/source/device/attribute/dscmbo.f
			gempak/source/gplt/device/plot/dcmbo.f
			gempak/source/gplt/device/attribute/dscmbo.f
			gempak/source/gplt/plot/gcmbo.f
			gempak/source/gplt/attribute/gqcmbo.f, gscmbo.f
			gempak/tables/draw/combo.tbl

			gempak/source/device/main/device.f
			gempak/source/device/access/dinit.f
			gempak/source/driver/active/vg/vssymb.c, vsymb.c,
			vgcmn.h
			gempak/source/gplt/attribute/gsattr.f
			gempak/source/gplt/access/ginit.f
			gempak/source/gplt/main/gplt.f
			gempak/source/testprog/atest.f, plotsyms.f
			gempak/source/cgemlib/cvg/cvgdump.c, cvgtodev.c,
			dumpvgf.c
			gempak/source/cgemlib/cds/cdssymb.c
			gempak/source/cgemlib/ces/cesrtbl.c, cesset.c
			gempak/source/cgemlib/crg/crgset.c

001ss.	10/28/98	gempak/source/bridge/ru/rudecd.f, rurtim.f,
			rustms.f, rutmst.f

011z.	10/29/98	gempak/source/programs/gp/gptext/gptext.f
			gempak/help/txtloc.hl1, txtloc.hl2, txtfil.hl1, 
			txtfil.hl2
			gempak/txt/programs/gptext.txt
			gempak/error/gptext.err

008r.	10/29/98

			gempak/source/cgemlib/cds/cdsgfill.c
			gempak/source/cgemlib/cfl/cfliret.c
			gempak/source/cgemlib/cgr/cgrinpoly.c, cgrntrsct.c, 
			cgrpolyint.c, cgrsegdist.c, cgrsegint.c
			gempak/source/cgemlib/clo/cloancinpoly.c, clocntyghot.c, 
			clocompass.c, clodist.c, clocntygall.c, clocntyinpoly.c, 
			clodirect.c, clolonin.c
			gempak/source/cgemlib/cpg/cpgdmpct.c, cpggetfname.c, 
			cpgrdhdr.c, cpgsixrd.c, cpgfindstart.c, cpggetsix.c, 
			cpgreadcuts.c, cpgxplane.c, cpgfindstop.c,
			cpgmtch.c, cpgsetbits.c, cpggetfile.c, cpgprse.c, cpgshoct.c
			gempak/source/cgemlib/crg/crgdeselect.c, crgggbnd.c, crggtyp.c, 
			crgstyp.c, crggettxtbox.c, crggrfrsh.c, crgsave.c
			gempak/source/cgemlib/cst/cstfind.c, cstinch.c, cstnumb.c
			gempak/source/cgemlib/ctb/ctbawmap.c, ctbplgcc.c
			gempak/source/cgemlib/cvg/cvgcrvgf.c, cvgopen.c, cvgsplsto.c, 
			cvgsvsym.c, cvgwbsto.c, cvgdump.c, cvgrdsel.c, cvgsvcnt.c, 
			cvgsvtxt.c, cvgwndsto.c, cvgfrsto.c, cvgrest.c, cvgsvfhed.c, 
			cvgsvwnd.c, cvglinsto.c, cvgrndef.c, cvgsvfnt.c, cvgtodev.c, 
			cvgload.c, cvgscan.c, cvgsvstx.c, cvgtxsto.c
			gempak/source/cgemlib/cvq/cvqhigp.c, cvqnxtgnm.c, cvqscangrp.c
			gempak/source/cgemlib/utf/utfstrip.c

010a2g.	10/29/98	gempak/source/gemlib/gd/gdgcyc.f
			nprogs/nmap/source/nmap_mdl.c

021a8b.	10/29/98	nprogs/nmap/source/vgf/nmap_pgolk.c
			gempak/source/cgemlib/clo/clodist.c

007qq. 	11/2/98		gempak/source/driver/active/nc/mtextc.c

006pp.	11/2/98		gempak/source/gplt/contour/gclgrn.f, cldriv.f, ccdraw.f,
			gcfill.f, gcboxx.f, ffdriv.f

021a8c.	11/2/98		nprogs/nmap/source/vgf/nmap_pgwndw.c

010a2h.	11/2/98		NEW:gempak/source/cgemlib/cbf/cbfclos.c, cbfopen.c,
			cbfread.c, testcbf.c, cbfcmn.h, testcbf_link
			gempak/error/cbf.err

			gempak/include/uscore.h
			gempak/build/cgemlib_compile, cgemlib_link

021a8d.	11/2/98		NEW:gempak/source/cgemlib/cvg/cvgqkopen.c

			gempak/source/cgemlib/cvg/cvgcp.c, cvgdeall.c, cvgopen.c
			nprogs/nmap/source/vgf/nmap_pgdel.c, nmap_pgfilw.c,
			nmap_pgundo.c
			gempak/error/cvg.err

021a8e.	11/4/98		NEW:gempak/source/cgemlib/crg/crgrngpt.c

			gempak/source/cgemlib/crg/crgrngpt.c
			nprogs/nmap/source/vgf/nmap_pgevt.c

021a8f.	11/4/98		NEW:icons/nmap/flame.xbm

			gempak/source/device/draw/ispcl.f
			gempak/source/testprog/plotsyms.f
			gempak/source/driver/active/utf/usymb.c
			gempak/source/driver/active/rbk/asymb.c
			gempak/utilities/xbm/nmapxbms.csh
			nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgobj.c
			gempak/include/drwids.h
			gempak/tables/pgen/symbolbtn.tbl

021a8g.	11/4/98		NEW:gempak/include/hints.h

			nprogs/nmap/source/vgf/nmap_pgwlst.c, nmap_pgundo.c,
			nmap_pgpdel.c, nmap_pgpalw.c, nmap_pgnew.c, nmap_pgmvcp.c,
			nmap_pgmdfy.c, nmap_pggrp.c, nmap_pgfilw.c, nmap_pgevt.c,
			nmap_edit.c, nmap_pgdelpt.c, nmap_pgconn.c
			nprogs/nmap/source/nmap_mbotw.c

001tt.	11/4/98		NEW:gempak/source/bridge/mn/mnntdy.f, mnsls.f, mntitl.f

			gempak/source/bridge/mn/mn3chc.f, mn3chr.f, mndecd.f,
			mnfctm.f, mnglin.f, mngrpt.f
			gempak/tables/pack/ngmmos.pack
			gempak/help/sfpamr.hl2
			gempak/txt/apx/parms.apx

021a8h.	11/4/98		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgnew.c, 
			nmap_pgobj.c, nmap_pgvgf.c
			gempak/include/vgstruct.h
			gempak/tables/draw/combo.tbl

008s.	11/4/98		NEW:doc/Prog_guide/gemlib/tables/aw.sub, cv.sub, gp.sub

			doc/Prog_guide/gemlib/tables/cpg.sub, cds.sub, ces.sub, cfl.sub,
			cgr.sub, clo.sub, cvg.sub, crg.sub, css.sub, cst.sub, 
			ctb.sub, fl.sub, gb.sub, df.sub, dg.sub, dv.sub, im.sub,
			mv.sub, gd.sub, gdu.sub, gg.sub, sf.sub, sn.sub, ss.sub,
			pd.sub, pr.sub, pt.sub, ti.sub, tm.sub, st.sub, tb.sub,
			tg.sub

006qq. 	11/5/98		NEW:gempak/include/cvcmn.cmn

			gempak/include/funccode.prm
			gempak/install/setup_links, remove_links

006rr.	11/5/98		gempak/source/appl/plot/gcircl.f*
			gempak/source/gplt/graph/gdpaxs.f
			gempak/source/gplt/main/gplt.f
			gempak/source/gplt/plot/gcircl.f
			gempak/source/gplt/device/plot/dcircl.f
			gempak/source/device/main/device.f
			gempak/source/device/plot/dcircl.f
			gempak/source/testprog/atest.f

			(* calling sequence change)

007rr.	11/5/98		gempak/source/driver/active/xw/xopnew.c
			nprogs/nwx/source/mapw.c

001uu.	11/5/98		gempak/source/programs/dc/dcamos/dcavcd.f

			gempak/source/bridge/av/avfctm.f, avtitl.f 
			(documentation only)

008t.	11/5/98		Prolog changes only:
			gempak/source/gemlib/aw/aw2clg.f, aw2cst.f, awachr.f,
			awaplt.f, awgdef.f, awglsv.f, awpidb.f, awpinf.f,
			awplin.f, awpmap.f, awpplt.f, awprod.f, awread.f, 
			awrfil.c, awscom.f, awsdef.f, awsver.f, awwxsm.f
			gempak/source/gemlib/df/dfatn2.f, dfhilo.f
			gempak/source/gemlib/dg/dggobs.f, dgnxts.f, dgofil.f,
			dgorgn.f, dgscal.f, dgufil.f, dgupvg.f
			gempak/source/gemlib/dm/dmgetf.f, dmggpm.f, dmlssf.f,
			dmpack.f, dmunpk.f
			gempak/source/gemlib/dp/dpunmc.f, dpunpk.f
			gempak/source/gemlib/dv.dvlvdy.f, dvtngv.f
			gempak/source/gemlib/er/ermmsg.f
			gempak/source/gemlib/fl/flmfls.f, fltmpl.f
			gempak/source/gemlib/gb/gbbds.c, gbbtoi.c, gbclos.c,
			gbends.c, gbgds.c, gbgids.c, gbgmtx.c, gbgsec.c, 
			gbgspk.c, gbgubd.c, gbpds.c, gbscan.c, gbscpk.c,
			gbsphr.c, gbunpk.c
			gempak/source/gemlib/gd/gdgtmf.f
			gempak/source/gemlib/gdu/gduginp.f
			gempak/source/gemlib/gg/ggcbar.f, ggmaps.f
			gempak/source/gemlib/gr/grclvl.f, grintp.f, grlist.f, 
			grmbn2.f, grscal.f, grsscl.f, grvscl.f
			gempak/source/gemlib/im/imgm2gi.f, imnihd.f, imnohd.f,
			imqlut.f, imqtim.f, imsbgn.c
			gempak/source/gemlib/in/inctyp.f, inintc.f, inprmf.f, 
			inskip.f, intype.f
			gempak/source/gemlib/ip/ipcwinf., iplist.f, ipswin.f
			gempak/source/gemlib/lc/lcfstn.f
			gempak/source/gemlib/mr/mrintp.f
			gempak/source/gemlib/na/nalevl.f, narhdr.f, nartbl.f
			gempak/source/gemlib/oa/oagfil.f
			gempak/source/gemlib/pc/pcclyr.f, pcdhgt.f, pcfunc.f,
			pcmhgt.f, pcpsym.f, pcpwtr.f, pcsvrt.f
			gempak/source/gemlib/pr/prcsyt.f, prd100.f, prdwpt.f,
			prinmm.f, prwcmp.f, prwnml.f
			gempak/source/gemlib/pt/ptwtmof.
			gempak/source/gemlib/sf/sfacny.f, sfcacny.f, sfwbox.f
			gempak/source/gemlib/sn/snmerg.f
			gempak/source/gemlib/ss/ssgtim.f, ssltim.f, ssvers.f
			gempak/source/gemlib/ss/vms/ssexit.f, ssgsym.f
			gempak/source/gemlib/st/statoe.f, stc2r.f, stpelt.f
			gempak/source/gemlib/st/AIX/statoe.f, stc2r.f, 
			stetoa.f, stpelt.f
			gempak/source/gemlib/tb/tbnids.f, tbparm.f
			gempak/source/gemlib/tg/tgvald.f
			gempak/source/gemlib/ti/tidayw.f
			gempak/source/gemlib/tm/tmwcr.f

001vv.	11/5/98		gempak/source/bridge/ru/rumlvl.f

021a8i.	11/6/98		nprogs/nmap/source/vgf/nmap_pgevt.c

018yy.	11/12/98	nprogs/nmap/source/nmap_data.h, nmap_dataw.c,
			nmap_domt.c, nmap_dsrc.c
			gempak/tables/nmap/master.nmap

006ss.	11/12/98	gempak/source/gplt/contour/ccdraw.f

021a8j.	11/12/98	gempak/source/cgemlib/cds/cdswbox.c
			nprogs/nmap/source/vgf/nmap_pgmodv.c,
			nmap_pgnew.c, nmap_pgwbx.c, nmap_pgwlst.c

007ss.	11/16/98	gempak/source/device/access/dinit.f


017c.	11/16/98	gempak/source/programs/gui/nafos/nafgmpk.c

005e.	11/16/98	gempak/source/gemlib/im/imunhd.f

021a8k.	11/16/98	NEW:icons/nmap/numb_edit.xbm

			gempak/source/nxmlib/NxmTxtA.c
			nprogs/nmap/source/vgf/nmap_pgedit.c,
			nmap_pgevt.c, nmap_pgpalw.c
			gempak/include/drwids.h
			gempak/tables/pgen/funcbtn.tbl

011aa.	11/17/98	NEW:gempak/nts/gemglb.nts

			gempak/source/gemlib/ip/ipdflt.f, ipstrp.f
			gempak/utilities/hlpbld/hlpbld.f
			gempak/utilites/pdfbld/pdfbld.f
			gempak/error/ip.err
			gempak/help/*.hl1 (All hl1 files)
			gempak/pdf/gemglb.pdf
			gempak/txt/gemlib/iplib.txt
			gempak/utilites/hlpbld/hlpbld
			gempak/utilities/utilites/pdf/gd_pdfbld,
			gp_pdfbld, na_pdfbld, oa_pdfbld, sf_pdfbld,
			sn_pdfbld, util_pdfbld

001ww.	11/17/98	NEW:gempak/source/programs/dc/snmodl/*
			gempak/source/bridge/snm/*
			gempak/error/snmodl.err
			gempak/help/snbufr.hl1, snbufr.hl2
			gempak/parm/snmodl.prm
			gempak/tables/pack/sfclass1.prm, sfclass1.prm_aux,
			snclass1.prm
			gempak/txt/programs/snmodl.txt

			gempak/source/gemlib/sf/sfastn.f
			gempak/source/gemlib/sn/snastn.f
			gempak/build/bridge_compile, dc_link
			gempak/help/sfoutf.hl2, sfprmf.hl2, snprmf.hl2
			gempak/nts/gemglb.nts
			gempak/utilities/hlpbld/util_hlpbld
			gempak/utilities/pdfbld/util_pdfbld

018zz.	11/18/98	NEW:gempak/tables/nmap/ngmmos_parms.tbl,
			avnmos_parms.tbl, mrfmos_parms.tbl

			nprogs/nmap/source/nmap_dslw.c, nmap_dataw.c,
			nmap_domt.c, nmap_dsp.c, nmap_dsrc.c, 
			nmap_obs.c, nmap_sfmap.f, nmapprm.h
			gempak/tables/nmap/dcatg.nmap, dsrc.nmap,
			master.nmap
			gempak/tables/config/prmlst.tbl

021a8l.	11/18/98	NEW:nprogs/nmap/source/vgf/nmap_pgwpts.c
			gempak/tables/pgen/watchbtn.tbl
			gempak/icons/nmap/watch.xbm, wbcnty.xbm,
			wbprll.xbm

			nprogs/nmap/source/vgf/nmap_pgedit.c, 
			nmap_pgevt.c, nmap_pghdlb.c, nmap_pgmodv.c,
			nmap_pgnew.c, nmap_pgpalw.c, nmap_pgvgf.c,
			nmap_pgwbxw.c, nmap_pgwlst.c
			gempak/include/drwids.h
			gempak/tables/pgen/classbtn.tbl, prodbtn.tbl

008u.	11/18/98	gempak/parm/gpmap.prm, gptext.prm, gpclose.prm

005f.	11/18/98	gempak/source/gemlib/im/imisub.f

018a1a.	11/19/98	nprogs/nmap/source/nmap_dataw.c, nmap_obs.c

018a1b.	11/19/98	nprogs/nmap/source/nmap_mapw.c

001xx.	11/19/98	NEW:gempak/tables/pack/sfclass0.prm, sfavn.prm,
			sfmrf.prm, sfngm.prm, snavn.prm, snclass0.prm,
			snmrf.prm, snngm.prm

			gempak/source/bridge/snm/snmcfc.f

021a8m.	11/19/98	NEW:gempak/source/cgemlib/cvg/cvgfscan.c
			nprogs/nmap/source/vgf/nmap_pgdsel.c

			nprogs/nmap/source/vgf/nmap_pgedit.c, nmap_pgevt.c,
			nmap_pgpalw.c, nmap_pgsymb.c

001zz.	11/23/98	gempak/source/bridge/snm/snmcfc.f, snmopn.f
			gempak/tables/pack/snavn.prm, snmrf.prm
			gempak/error/snmodl.err

021a8n.	11/23/98	nprogs/nmap/source/vgf/nmap_pgwbxw.c

021a8o.	11/23/98	gempak/source/cgemlib/cvg/cvgfscan.c
			nprogs/nmap/source/vgf/nmap_pgdsel.c, 
			nmap_pgevt.c, nmap_pghdlb.c

021a8p.	11/24/98	nprogs/nmap/source/vgf/nmap_pgevt.c, 
			nmap_pggrpw.c, nmap_pgpalw.c

010a2i.	11/30/98	gempak/source/cgemlib/cpg/cpgfndgrp.c,
			testcpg.c

			gempak/error/cpg.err
			gempak/install/remove_links, setup_links
			nprogs/viewfax/Makefile

006tt.	11/30/98	gempak/source/device/draw/ipatln.f

001a1a.	11/30/98	NEW:gempak/source/gemlib/st/stunp1.f
			gempak/source/gemlib/st/AIX/stunp1.f

			gempak/source/programs/dc/dcamos/dcavcd.f
			gempak/source/programs/dc/dcmmos/dcmmdc.f
			gempak/source/programs/dc/dcnmos/dcnmdc.f

018a1c.	11/30/98	nprogs/nmap/source/nmap_dataw.c

011bb.	11/30/98	gempak/source/programs/gd/gdplot2/gdpltb.f

011cc.	12/1/98		gempak/source/programs/gd/grphgd/grphgd.f

001a1b.	12/2/98		NEW:gempak/source/programs/na/* (moved from
			gempak/source/programs/dc/snmodl)
			gempak/source/gemlib/jb/* (moved from
			gempak/source/bridge/snm
			gempak/error/namsnd.err
			gempak/parm/namsnd.prm
			gempak/txt/programs/namsnd.txt

			gempak/build/bridge_compile, dc_link, gemlib_compile,
			na_compile, na_link
			gempak/help/sfoutf.hl2, sfprmf.hl2, snbufr.hl2,
			snprmf.hl2
			gempak/utilities/hlpbld/na_hlpbld, util_hlpbld
			gempak/utilities/pdfbld/na_pdfbld, util_pdfbld

010a2j.	12/2/98		gempak/source/gemlib/aw/aw2clg.f, aw2cst.f, awachr.f,
			awadbt.f, awaplt.f, awgdef.f, awglsv.f, awpend.f, 
			awpidb.f, awpmap.f, awpplt.f, awprod.f, awread.f,
			awscom.f, awwxsm.f

021a8q.	12/3/98		nprogs/nmap/source/vgf/nmap_pgwlst.c

018a1d.	12/3/98		NEW:icons/nmap/hide_loop.xbm, show_loop.xbm

			nprogs/nmap/source/nmap_data.h, nmap_dsp.c, 
			nmap_loop.c
			gempak/source/driver/active/xw/xmloop.c

021a8r.	12/3/98		nprogs/nmap/source/vgf/nmap_pgggc.c
			nprogs/nmap/source/Makefile
			gempak/include/undscr.h

010a2k.	12/7/98		gempak/source/gemlib/gr/grtmfl.f, grtlst.f
			gempak/source/gemlib/gd/testgd.f

018a1e.	12/7/98		nprogs/nmap/source/nmap_dataw.c, nmap_dsp.c,
			nmap_dtmbw.c, nmap_dttm.c, nmap_dttmw.c, 
			nmap_image.c, nmap_mdl.c, nmap_obs.c,
			nmap_tmln.c, nmap_data.h, nmap_dttm.h, 
			nmapprm.h
			gempak/source/cgemlib/cst/csttims.c

010a2l.	12/8/98		gempak/source/gemlib/sf/testsf.f
			gempak/source/gemlib/pr/testpr.f
			gempak/source/cgemlib/ces/cesrtbl.c
			gempak/source/cgemlib/ces/testces.c
			gempak/source/driver/active/rbk/asymb.c

001a1c.	12/10/98	NEW:gempak/source/bridge/mm/mmclim.f,
			mmopnc.f

			gempak/source/programs/dc/dcmmos/dcmmdc.f
			gempak/error/mm.err
			gempak/help/sfparm.hl2
			gempak/tables/pack/mrfmos.pack
			gempak/txt/apx/parms/apx

021a8s.	12/14/98	NEW:nprogs/nmap/source/vgf/nmap_pgnumb.c

			nprogs/nmap/source/vgf/nmap_pgedit.c,
			nmap_pgevt.c, nmap_pgpalw.c, nmap_pgdsel.c,
			nmap_pgutls.c
			gempak/source/nxmlib/NxmTxtA.c
			gempak/include/hints.h

021a8t.	12/15/98	nprogs/nmap/source/vgf/nmap_pgedit.c,
			nmap_pgmodv.c, nmap_pgnew.c, nmap_pgpalw.c,
			nmap_pgwbxw.c, nmap_wlst.c

018a1f.	12/16/98	gempak/source/driver/active/xw/xmloop.c,
			xpgpaste.c, xg2pxm.c, xpgrfrsh.c
			nprogs/nmap/source/nmap_dataw.c, 
			nmap_dsp.c, nmap_mbotw.c, nmap_loopw.c
			nprogs/nmap/source/vgf/nmap_pgevt.c,
			nmap_pgpalw.c
			gempak/include/xwcmn.h, xwprm.h
			icons/nmap/hide_loop.xbm, show_loop.xbm

007tt.	12/16/98	gempak/source/driver/active/vg/vfill.c, vline.c,
			vspln.c, vtext.c

021a8u.	12/17/98	NEW:icons/nmap/inc_dec.xbm	
			nprogs/nmap/source/vgf/nmap_pgdsel.c, nmap_pgedit.c,
			nmap_pgevt.c, nmap_pgnumb.c, nmap_pgpalw.c, 
			nmap_pgutls.c, nmap_pghdlb.c
			gempak/include/drwids.h
			gempak/tables/pgen/funcbtn.tbl

021a8v.	12/18/98	nprogs/nmap/source/vgf/nmap_pgpalw.c

020c.	12/18/98	NEW:gempak/utilities/cities/alphainfo.c, 
			stloninfo.c, alphainfo_link, stloninfo_link,
			alphainfo, stloninfo
			gempak/tables/cities/citiesloc.tbl, citiesnam.tbl
			(moved from gempak/tables/stns)

007uu.	12/18/98	NEW:gempak/source/active/gn/hcirc.f
			gempak/source/active/nc/mdots.c
			gempak/source/active/vg/hcirc.f, vcirc.c
			gempak/source/active/xw/hcirc.f, xcirc.c, xdot.c
			gempak/source/active/ps/pcirc.c
			gempak/source/active/xwp/hcirc.f
			gempak/source/cgemlib/cds/cdscirc.c
			gempak/source/cgemlib/crg/crgsetcir.c
			gempak/source/cgemlib/cvg/cvgcirsto.c, 
			cvgsvcir.c, cvgrdcir.c

			gempak/source/testprog/atest.f
			gempak/source/device/plot/dcircl.f
			gempak/source/driver/active/fax/hinit.f
			gempak/source/driver/active/nc/hinit.f
			gempak/source/driver/active/gn/hinit.f
			gempak/source/driver/active/nc/mline.c
			gempak/source/driver/active/ps/hinit.f, psopen.c
			gempak/source/driver/active/rbk/hinit.f
			gempak/source/driver/active/utf/hinit.f
			gempak/source/driver/active/vg/hinit.f
			gempak/source/driver/active/xw/hinit.f, xline.c
			gempak/source/driver/active/xwp/hinitps.f,
			hinitxw.f
			gempak/source/cgemlib/crg/crgset.c
			gempak/source/cgemlib/ces/cesset.c,
			cesrtbl.c, cesget.c, testces.c
			gempak/source/cgemlib/crg/crgset.c
			gempak/source/cgemlib/cvg/cvgtodev.c, cvgrdele.c,
			cvgdump.f, testcvg.c, testcvg_link
			nprogs/nmap/source/vgf/nmap_pgvgf.c
			gempak/include/devchr.cmn, uscore.h, drwids.h, 
			vgstruct.h, cescmh.h
			gempak/tables/pgen/setting.tbl

001a1d.	12/21/98	gempak/source/programs/na/namsnd/namopn.f
			gempak/error/namsnd.err
			gempak/tables/pack/snclass1.prm
			gempak/txt/programs/namsnd.txt

021a8w.	12/21/98	NEW:gemapk/source/cgemlib/clo/clotdirect.c
			(renamed from clodirect.c)

			gempak/source/cgemlib/clo/testclo.c
			nprogs/nmap/source/vgf/nmap_pgolk.c

001a1e.	12/21/98	gempak/source/ldmlog/ulog.h

021a8x.	12/21/98	NEW:gempak/source/cgemlib/clo/clocityrd.c,
			clofindcity.c

			gempak/source/cgemlib/clo/cloclosest.c, 
			cloinit.c, testclo.c
			gempak/include/clocmn.h
			nprogs/nmap/source/vgf/nmap_pgwlst.c, 
			nmap_pgwpts.c

021a8y.	12/22/98	nprogs/nmap/source/vgf/nmap_pgevt.c, 
			nmap_pgnumb.c, nmap_pgpal.c
			gempak/source/driver/active/xw/xg2pgm.c
			gempak/include/hinit.h

021a8z.	12/22/98	nprogs/nmap/source/vgf/nmap_pgxrain.c

001a1f.	12/23/98	NEW:gempak/source/gemlib/pr/prwvdd.f, 
			prwvph.f

			gempak/source/bridge/ma/maintf.f
			gempak/source/gemlib/pc/pcfunc.f
			gempak/source/gemlib/pr/testpr.f
			gempak/help/sfparm.hl2
			gempak/tables/pack/msfc.pack
			gempak/tables/parms/pcconv.tbl
			gempak/txt/apx/parms.apx

021a9a.	12/23/98	nprogs/nmap/source/vgf/nmap_pgdel.c, nmap_pgevt.c,
			nmap_pghdlb.c, nmap_pgmvcp.c, nmap_pgtxt.c,
			nmap_pgundo.c, nmap_pgutls.c
			gempak/source/nxmlib/NxmTxtA.c
			gempak/source/cgemlib/cvg/cvgload.c, cvgrfrsh.c
			gempak/include/pgprm.h

017d.	12/23/98	gempak/source/programs/gui/nafos/nafos.c

010a2m.	12/24/98	gempak/source/gemlib/in/inccol.f, incolr.f
			gempak/source/gemlib/jb/jtbpdmp.f, jwbufr.f
			gempak/source/gemlib/lc/testlc.f
			gempak/source/gemlib/pc/testpc.f
			gempak/source/gemlib/pd/pdslvp.f
			gempak/source/gemlib/ti/testti.f
			gempak/source/programs/gd/gdplot2/gdpltb.f
			gempak/source/programs/gp/gptext/gptext.f
			gempak/source/programs/na/namsnd/namjen.f
			gempak/source/testprog/plotsyms.f

018a1g.	12/28/98	NEW:icons/nmap/default.xbm

			nprogs/nmap/source/nmap_dataw.c, nmap_dslw.c,
			nmap_mbtnw.c, nmap_dsrc.c, nmap_tmln.c, nmap_data.h

011dd.	12/28/98	NEW:gempak/source/gemlib/mv/Linux/*
			gempak/source/gemlib/mv/OSF1/mvbtoi.c, mvitob.c,
			testmv.f
			gempak/source/gemlib/mv/ULTRIX/mvbtoi.c, mvitob.c,
			testmv.f

			nprogs/nwx/source/srchb.c, dslw.c
			nprogs/nmap/source/nmap_mpcstw.c, nmap_mmenw.c
			nprogs/nsat/source/mmenuw.c
			gempak/source/gplt/transform/mcidas/mcnav.f
			gempak/source/driver/active/nc/mtext.c, mtextc.c,
			hline.f
			gempak/source/driver/active/xw/xenanm.c, xpgsvfrm.c,
			xclear.c, xfill.c, xinita.c, xsplot.c, xsroam.c,
			xmloop.c
			gempak/source/cgemlib/cds/cdswbox.c
			gempak/source/cgemlib/cst/cstrang.c
			gempak/source/cgemlib/cvg/cvgqkopen.c
			gempak/source/gemlib/ti/testti.f
			gempak/source/programs/gui/nafos/nafmenuw.c
			gempak/source/nxmlib/NxmBxmBtn.c, NxmTxtA.c
			gempak/include/gemprm.h
			gempak/source/driver/active/gf/xv.h

007vv.	12/29/98	gempak/source/driver/active/vg/vtext.c

013b.	12/29/98	nprogs/ntl/source/appbtn.c

001a1g.	12/29/98	gempak/source/bridge/mm/mmclim.f

018a1h.	12/30/98	gempak/source/nxmlib/NxmBxmBtn.c,
			NxmColrP.c, NxmLabel.c, NxmLineA.c, NxmPrt.c
			nprogs/nmap/source/nmap_dslw.c, nmap_mmenuw.c,
			nmap_stnmw.c vgf/nmap_pgprd.c,
			vgf/nmap_pgwlst.c, vgf/nmap_pgwndw.c

011ee.	12/31/98	gempak/include/gemprm.Linux

021a9b.	12/31/98	NEW:gempak/source/cgemlib/clo/clocitygall.c,
			clotclosest.c
			gempak/utilites/cities/locinfo.c, naminfo.c,
			locinfo, naminfo, locinfo_link, naminfo_link

			gempak/source/cgemlib/clo/clocityrd.c, clofindcity.c,
			clotdirect.c, clotgid.c, clotgltln.c, testclo.c,
			clocmn.h
			nprogs/nmap/source/vgf/nmap_pgwlst.c, nmap_pgwpts.c,
			nmap_pgxrain.c

018a1i.	1/4/99		nprogs/nmap/source/nmap_loopw.c

016c.	1/4/99		nprogs/nwx/source/srchb.c, srchw.c, guid.c,
			txtw.c

001a1h.	1/4/99		gempak/source/bridge/mt/mtrvr4.f
			gempak/txt/apx/parms.apx

018a1j.	1/6/99		nprogs/nmap/source/smgtim.f

011ff.	1/6/99		gempak/source/programs/sf/sfmap/sfmap.f
			gempak/source/programs/sn/snmap/snmap.f
			gempak/tables/pgen/grptyp.tbl

021a9c.	1/6/99		gempak/source/nxmlib/NxmTxtA.c
			nprogs/nmap/source/vgf/nmap_pgedit.c, 
			nmap_pgtxt.c
			include/Nxm.h

020d.	1/6/99		gempak/maps/programs/ssfgsf.f

011gg.	1/6/99		gempak/source/programs/gd/grphgd/grphgd.cmn

021a9d.	1/6/99		nprogs/nmap/source/vgf/nmap_pgolk.c

018a1k.	1/6/99		nprogs/nmap/source/nmap_dataw.c
			nprogs/nmap/source/vgf/nmap_pgpalw.c

021a9e.	1/8/99		NEW:nprogs/nmap/source/vgf/nmap_pgwfmt.c
			icons/nmap/wtchfmt.xbm

			nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pgpalw.c,
			nmap_pgwbxw.c, nmap_pgwlst.c
			gempak/include/drwids.h
			gempak/tables/pgen/prodbtn.tbl

006uu.	1/8/99		gempak/source/appl/plot/gtxsy.f (doc only)
			gempak/source/gplt/plot/gtxsy.f (doc only)
			gempak/source/gplt/device/plot/dtxsy.f (doc only)
			gempak/source/device/plot/dtxsy.f (doc only)
			gempak/source/device/draw/itxsy.f

013c.	1/8/99		NEW:nprogs/ncolor/NxmGmpk.c, ncolor.c, 
			Makefile
			resource/Ncolor
			icons/ncolor.xbm

			tables/ntl/ntl.tbl

021a9f.	1/11/99		nprogs/nmap/source/vgf/nmap_pgedit.c, nmap_pgevt.c,
			nmap_pgmvcp.c, nmap_pgnew.c, nmap_pgpalw.c, 
			nmap_pgrot.c, nmap_pgtxt.c, nmap_pgvgf.c

021a9g.	1/12/99		nprogs/nmap/source/vgf/nmap_pgevt.c, nmap_pghdlb.c,
			nmap_pgwbxw.c, nmap_pgwfmt.c, nmap_pgwlst.c

013d.	1/12/99		gempak/source/nxmlib/NuiColorInit.c, NxmColorBar.c
			nprogs/ncolor/source/ncolor.c
			include/Nui.h

014g.	1/13/99		nprogs/ntrans/source/process_meta.c

010a2o.	1/13/99		NEW:gempak/source/cgemlib/cgr/cgrrolseg.c
			gempak/source/cgemlib/clo/clordcity.c, clordcnty.c,
			clordstn.c, clotinltln.c, clotinpoly.c, clocmn.h

			gempak/source/cgemlib/cgr/testcgr.c
			gempak/source/cgemlib/cds/cdswbx.c
			gempak/source/cgemlib/clo/clocitygall.c, cloclosest.c,
			clocntygall.c, clocntyghot.c, clocntygpoly.c,
			clocntyphot.c, clocntyrhot.c, clofindcity.c,
			cloinit.c, clolonin.c, clotclosest.c, clotgid.c, 
			clotgltln.c, clovorgall.c, testclo.c
			nprogs/nmap/source/vgf/nmap_pgprd.c, nmap_pgwfmt.c,
			nmap_pgwlst.c, nmap_pgwpts.c, nmap_pgxrain.c
			gempak/include/gemprm.h
			gempak/install/remove_links, setup_links

021a9h.	1/13/99		nprogs/nmap/source/vgf/nmap_pgtxt.c, nmap_pgedit.c
			gempak/include/Nxm.h

010a2p.	1/13/99		gempak/source/cgemlib/cbf/cbfread.c, testcbf_link

006vv.	1/13/99		gempak/source/testprog/atest.f
			gempak/source/device/draw/itxsy.f

010a2q.	1/14/99		gempak/source/gemlib/jb/jwbufr.f

021a9i.	1/14/99		nprogs/nmap/source/vgf/nmap_pgtxt.c
			gempak/source/cgemlib/crg/crggettxtbox.c
			gempak/tables/pgen/setting.tbl

			NEW:icons/box/box07.xbm

011hh.	1/19/99		NEW:gempak/source/programs/gd/gdplot2/gdplot_vg_link

			gempak/source/gemlib/in/inline.f*  (calling sequence change)
			gempak/source/gemlib/in/testin.f
			gempak/source/gplt/contour/ccplot.f
			gempak/source/programs/gd/gdplot2/gdblev.f, gdpltb.f
			gempak/source/programs/gd/gdcross/gdxplt.f, gdxsdl.f,
			gdxlev.f
			gempak/source/programs/gd/gdcntr/gdcntr.f
			gempak/source/programs/gd/gdplot/gdblev.f, gdplot.f
			gempak/source/programs/gd/gdprof/gdpplt.f
			gempak/source/programs/gd/gdstream/gdstream.f
			gempak/source/programs/gd/gdthgt/gdtxlv.f, gdtxpl.f
			gempak/source/programs/gd/gdtser/gdtplt.f
			gempak/source/programs/gp/gpbox/gpbox.f
			gempak/source/programs/gp/gpmap/gpmap.f
			gempak/source/programs/oa/oabox/oabox.f
			gempak/source/programs/sf/sfgram/sfgram.f
			gempak/source/programs/sn/sncross/snsbor.f, snsisn.f, 
			snslev.f
			gempak/source/programs/sn/snhodo/snhodo.f
			gempak/source/programs/sn/snprof/snpprm.f, snplin.f
			gempak/source/programs/sn/sntser/sntplt.f
			gempak/help/line.hl2, line.hl1

021a9j.	1/19/99		NEW:icons/nmap/lowx.xbm, xcross.xbm

			gempak/utilities/xbm/nmapxbms.csh
			gempak/source/testprog/plotsyms.f
			gempak/source/device/draw/isymb.f
			gempak/source/device/draw/ispcl.f
			gempak/source/driver/active/utf/usymb.c
			nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgobj.c
			gempak/source/driver/active/rbk/asymb.c
			gempak/tables/pgen/symbolbtn.tbl
			gempak/include/drwids.h

001a1i.	1/20/99		gempak/source/bridge/af/afcmn.cmn, afdarp.f,
			afdcod.f, afdprp.f, afdrco.f, afifsp.f, 
			afpilr.f, afptlr.f, afrtim.f, afxbif.f

002f.	1/20/99		gempak/source/programs/na/nagrib/nagrib.f
			gempak/tables/grid/wmogrib2.tbl

011ii.	1/21/99		gempak/source/programs/gd/gdcntr/gdcntr.f
			gempak/source/programs/gd/gddelt/gddel.f
			gempak/source/programs/gd/gdmap/gdmap.f
			gempak/source/programs/gd/gdmod/gdoadd.f
			gempak/source/programs/gd/gdplot/gdplot.f, gdbtim.f
			gempak/source/programs/gd/gdprof/gdprof.f
			gempak/source/programs/gd/gdstat/gdstat.f
			gempak/source/programs/gd/gdstream/gdstream.f
			gempak/source/programs/gd/gdthgt/gdtxda.f, gdtxgl.f,
			gdtxgl.f, gdtxvv.f, gdwind.f
			gempak/source/gemlib/gd/etstgd.f
			gempak/source/gemlib/gdu/gduginp.f
			gempak/source/gemlib/gr/grlist.f

021a9k.	1/21/99		nprogs/nmap/source/vgf/nmap_pgedit.c,
			nmap_pgtxt.c, nmap_pgutls.c

011jj.	1/21/99		gempak/source/testprog/plotsyms.f

010a2r.	1/21/99		gempak/source/cgemlib/clo/clolonin.c, testclo.c

021a9l.	1/22/99		NEW:nprogs/nmap/source/vgf/nmap_pgwxd.c

			nprogs/nmap/source/vgf/nmap_pgpalw.c, nmap_pgprd.c
			icons/nmap/wxd.xbm
			gempak/include/drwids.h
			gempak/tables/pgen/prodbtn.tbl

001a1j.	1/22/99		gempak/source/bridge/mt/mtgemp.f, mtinf.f
			gempak/help/sfparm.hl2
			gempak/tables/nmap/metar_parms.tbl
			gempak/tables/pack/metar.pack
			gempak/tables/parms/pcconv.tbl
			gempak/txt/apx/parms.apx

010a2s.	1/25/99		gempak/source/gemlib/fl/flmfls.f
			gempak/source/programs/gd/gdplot2/gdpltb.f

018a1l.	1/26/99		nprogs/nmap/source/nmap.c, nmap_dataw.c, 
			nmap_disp.c

011kk.	1/26/99		gempak/source/programs/gd/grphgd/grphgd.f

021a9m.	1/27/99		nprogs/nmap/source/vgf/nmap_pgsfp.c,
			nmap_pgwxd.c

021a9n.	1/27/99		nprogs/nmap/source/vgf/nmap_pgedit.c, 
			nmap_pgevt.c, nmap_pgdsel.c, nmap_pgnumb.c,
			nmap_pgpalw.c

001a1k.	1/28/99		gempak/source/bridge/dc/dcgbul.c

018a1m.	1/29/99		nprogs/nmap/source/nmap_dataw.c

007ww.	2/2/99		gempak/source/cgemlib/ctb/ctbtiff.c, testctb.c
		        gempak/source/driver/active/tiff/hclear.f,
			hclosp.f, hdots.f, hendd.f, hfill.f, hinit.f,
			hinita.f, hline.f, hopen.f, hscolr.f, hsdatt.f,
			hsfill.f, pattern.h, tbrescirc.c, tcircpts.c,
		        tclear.c , tclosp.c, tdots.c, tendd.c, tfill.c,
			tg4.h, tg4comp.c, tiffcmn.h, tinita.c, tline.c,
			tscnfll.c, tscolr.c, tsdatt.c, tsfill.ca, tsopen.c, 
			tspan.c, ttiff.c, twrpxl.c, tiff_compile, tiff_link
			gempak/tables/pgen/tiffprod.tbl
			gempak/build/driver_complie, driver_link
			gempak/include/uscore.h

010a2t.	2/2/99		gempak/source/gemlib/gg/ggsdev.f
			gempak/help/device.hl2

021a9o.	2/2/99		nprogs/nmap/source/nmap_dataw.c
			nprogs/nmap/source/vgf/nmap_pghdlb.c, nmap_pgpalw.c
			gempak/include/drwids.h
			gempak/tables/pgen/funcbtn.tbl
			icons/nmap/showgrps.xbm

011ll.	2/3/99		gempak/source/programs/gd/gdplot2/gdpwnd.f,
			testgdp.f, testgdp_link

011mm.	2/3/99		gempak/source/programs/gd/gdplot/gdblev.f
			gempak/source/programs/gd/gdplot2/gdblev.f, gdpltb.f

020e.	2/3/99		doc/Prog_guide/shared/tools/checkSrc.sh, ptypcmpf.perl
			bin/ndirect

018a1n.	2/3/99		gempak/source/cgemlib/clo/clodirect.c, clotdirect.c
			gempak/source/cgemlib/cst/cstsplit.c
			nprogs/nmap/source/nmap.c, nmap_mbtnw.c, nmap_seekw.c
			icons/nmap/seek.xbm, gempak/include/gemprm.h

010a2u.	2/3/99		gempak/source/cgemlib/clo/clolonin.c

011nn.	2/4/99		gempak/source/programs/sf/sfmod/sfmod.f, 
			sfcopt.f, sfcinp.f; gempak/error/sfmod.err
			gempak/help/datout.hl1, datout.hl2
			gempak/parm/sfmod.prm; genpak/txt/programs/sfmod.txt
021a9p.	2/4/99		nprogs/nmap/source/vgf/nmap_pgsfp.c

021a9q.	2/4/99		nprogs/nmap/source/vgf/nmap_pgwlst.c

009d.	2/5/99		gempak/build/gd_link, sf_link

010a2v.	2/5/99		gempak/source/gemlib/fl/flmfls.f

021a9r.	2/5/99		nprogs/nmap/source/vgf/nmap_pglwst.c

010a2w.	2/5/99		gempak/source/cgemlib/css/cssdate.c, testcss.c
			gempak/source/gemlib/ti/tijtoi.f

007xx.	2/8/99		gempak/source/device/plot/dcmbo.f

018a1o.	2/8/99		nprogs/nmap/source/nmap_snmap.f

011oo.	2/8/99		gempak/source/programs/gp/gptext/gptext.f

007yy.	2/8/99		gempak/source/driver/active/tiff/tclear.c,
			tg4comp.c

021a9s.	2/8/99		nprogs/nmap/source/vgf/nmap_pgfilw.c

021a9t.	2/8/99		nprogs/nmap/source/vgf/nmap_pgobj.c,
			nmap_pgalw.c, nmap_pgsfp.c
			gempak/source/device/plot/dfrnt.f
			gempak/source/testprog/plotsyms.f
			gempak/include/drwids.h
			gempak/tables/draw/combo.tbl, splpat.tbl
			gempak/tables/pgen/funcbtn.tbl, frontbtn.tbl,
			combsymbbtn.tbl, setting.tbl, symbolbtn.tbl
			icons/nmap/lowx.xbm, squall.xbm, csymb01.xbm
			to csymb27.xbm inclusive.

001a1l.	2/8/99		gempak/source/bridge/mt/mtslp.f

005g.	2/8/99		gempak/source/gemlib/im/imcbar.f

011pp.	2/8/99		gempak/source/programs/sn/sncross/snsstm.f
			gempak/source/programs/sn/sntser/sntser.f,
			sntdat.f

021a9u.	2/9/99		gempak/source/nxmlib/NxmGeneric.c
			nprogs/nmap/source/nmap_seekw.c
			nprogs/nmap/source/vgf/nmap_pgpdel.c

021a9v.	2/9/99		nprogs/nmap/source/vgf/nmap_pgwxd.c

021a9w.	2/9/99		nprogs/nmap/source/nmap_dataw.c, nmap_loopw.c
			nprogs/nmap/source/vgf/nmap_pgpalw.c

010a2x.	2/10/99		gempak/source/gemlib/dg/dgmfil.f

010a2y.	2/10/99		gempak/source/gemlib/fl/flmfls.f

007zz.	2/10/99		gempak/source/device/plot/dtext.f

021a9x.	2/10/99		nprogs/nmap/source/vgf/nmap_pgfilw.c, nmap_pgggc.c

021a9y.	2/10/99		nprogs/nmap/source/vgf/nmap_pgevt.c

006ww.	2/10/99		gempak/source/gplt/contour/ccdraw.f, ffdriv.f,
			cldriv.f, gclgrn.f, gcfill.f, gcboxx.f
	RESTORED:	gempak/source/gplt/contour/fgtbox.f, cccrss.f,
			fgtcor.f, fgtsub.f, ccstrt.f, ccgtsb.f,
			ccoeff.f, ccchck.f, ccboxt.f

021a9z.	2/11/99		gempak/source/cgemlib/cvg/cvgcp.c, testcvg_link
			nprogs/nmap/source/vgf/nmap_pgfilw.c
			
010a2z.	2/11/99		gempak/source/cgemlib/cvg/cvgc3k3j.c, convcvg.c


008v.	2/11/99		NEW:  help/nmap/Cursor.hlp, Hide_show.hlp
			
			help/nmap/DataSelection.hlp, MapSelection.hlp,
			WatsNew.hlp, ProdGen.hlp, nmap.nlp, nmapHlp.index

009e.	2/12/99		gempak/build/nprog_make, nprog_link

010a3a.	2/12/99		gempak/source/cgemlib/cvg/cvgc3k3j.c

021b1a.	2/16/99		nprogs/nmap/source/nmap_dataw.c
			nprogs/nmap/source/vgf/nmap_pgfilw.c



